/* Event wiring tests with a minimal DOM double. These are not browser QA. */
const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('fs'),path=require('path');const Motion=require('../src/motion.js');
async function harness({reduce=false,rect={left:10,top:20,width:480,height:360}}={}){let clock=1000,queue=new Map(),id=0,renders=[];
 class Element{constructor(){this.handlers={};this.width=480;this.height=360;this.attrs={};this.checked=false;}addEventListener(n,f){this.handlers[n]=f;}getContext(){return {};}getBoundingClientRect(){return rect;}setAttribute(n,v){this.attrs[n]=v;}emit(n,e={}){this.handlers[n]?.(e);}}
 const el=Object.fromEntries(['canvas','media','status','hint','reduced','hide','reset'].map(k=>[k,new Element()]));let mq={matches:reduce,addEventListener(n,f){this.listener=f;}};const doc={hidden:false,handlers:{},getElementById:k=>el[k],createElement:()=>new Element(),addEventListener(n,f){this.handlers[n]=f;}};const context={SpoilerMotion:{...Motion,renderMedia(ctx,arg){renders.push(arg);}},document:doc,matchMedia:()=>mq,window:{},performance:{now:()=>clock},Image:class{set src(v){queueMicrotask(()=>this.onload?.());}},requestAnimationFrame:f=>{queue.set(++id,f);return id;},cancelAnimationFrame:i=>queue.delete(i)};
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/app.js'),'utf8'),context);await new Promise(r=>setImmediate(r));
 return {el,doc,mq,renders,step(t){clock=1000+t;const q=[...queue.values()];queue.clear();q.forEach(f=>f(t));},at(t){clock=1000+t;},pending:()=>queue.size};}
test('initial artwork load schedules hidden rendering',async()=>{const h=await harness();h.step(0);assert.equal(h.renders.at(-1).model.phase,'hidden');assert.equal(h.el.status.textContent,'Hidden');});
test('pointer coordinates are normalized at mobile width',async()=>{const h=await harness({rect:{left:10,top:20,width:240,height:180}});h.step(0);h.el.media.emit('click',{detail:1,clientX:70,clientY:155});h.step(20);assert.deepEqual(h.renders.at(-1).model.origin,{x:120,y:270});});
test('keyboard activation uses image center',async()=>{const h=await harness();h.step(0);h.el.media.emit('click',{detail:0,clientX:0,clientY:0});h.step(20);assert.deepEqual(h.renders.at(-1).model.origin,{x:240,y:180});});
test('reduced-motion checkbox settles reveal and stops RAF',async()=>{const h=await harness();h.step(0);h.el.media.emit('click',{detail:0});h.step(30);h.el.reduced.checked=true;h.el.reduced.emit('change');h.step(31);assert.equal(h.renders.at(-1).model.phase,'revealed');assert.equal(h.pending(),0);});
test('initial reduced preference freezes hidden render',async()=>{const h=await harness({reduce:true});h.step(0);assert.equal(h.pending(),0);assert.equal(h.renders.at(-1).model.reducedMotion,true);});
test('Hide again reverses an active reveal',async()=>{const h=await harness();h.step(0);h.el.media.emit('click',{detail:0});h.step(50);h.el.hide.emit('click');h.step(60);assert.equal(h.renders.at(-1).model.phase,'hiding');h.step(500);assert.equal(h.renders.at(-1).model.phase,'hidden');});
test('reset is reachable and restores accessible labels',async()=>{const h=await harness();h.step(0);h.el.media.emit('click',{detail:0});h.step(200);h.el.reset.emit('click');h.step(201);assert.equal(h.el.media.attrs['aria-label'],'Reveal hidden media');assert.equal(h.el.status.textContent,'Hidden');});
test('hidden document cancels animation work and resumes safely',async()=>{const h=await harness();h.step(0);h.doc.hidden=true;h.doc.handlers.visibilitychange();assert.equal(h.pending(),0);h.doc.hidden=false;h.doc.handlers.visibilitychange();assert.equal(h.pending(),1);});
test('revealed idle state does not continuously render',async()=>{const h=await harness();h.step(0);h.el.media.emit('click',{detail:0});h.step(200);assert.equal(h.pending(),0);});
