const {test}=require('node:test');const assert=require('node:assert/strict');const M=require('../src/motion.js');
const near=(a,b,e=1e-8)=>assert.ok(Math.abs(a-b)<e,`${a} ≈ ${b}`);
test('initial hidden state has zero radius',()=>{const s=M.createModel().sample(0);assert.equal(s.phase,'hidden');assert.equal(s.radius,0);});
test('reveal starts at the actual pointer',()=>{const m=M.createModel();m.reveal(10,{x:70,y:85});assert.deepEqual(m.sample(10).origin,{x:70,y:85});});
test('reveal finishes in the measured 180 ms envelope',()=>{const m=M.createModel();m.reveal(20);assert.equal(m.sample(199).phase,'revealing');assert.equal(m.sample(200).phase,'revealed');});
test('measured radial knot values',()=>{for(const [ms,r] of M.RADIUS_KNOTS)near(M.revealRadius(ms/M.REVEAL_MS,339.2),r,0.0001);});
test('radius grows monotonically over 1,801 samples',()=>{let prev=0;for(let i=0;i<=1800;i++){let r=M.revealRadius(i/1800,316);assert.ok(r>=prev);prev=r;}});
test('repeat reveal does not move the origin or restart',()=>{const m=M.createModel();m.reveal(0,{x:9,y:25});assert.equal(m.reveal(80,{x:400,y:90}),false);assert.deepEqual(m.sample(80).origin,{x:9,y:25});assert.equal(m.sample(180).phase,'revealed');});
test('hide during reveal is continuous',()=>{const m=M.createModel();m.reveal(0);const a=m.sample(50);m.hide(50);near(m.sample(50).progress,a.progress);near(m.sample(50).radius,a.radius);assert.ok(m.sample(70).radius<a.radius);});
test('reveal during hide keeps the same mask origin',()=>{const m=M.createModel();m.reveal(0,{x:50,y:70});m.hide(200);const a=m.sample(250);m.reveal(250,{x:400,y:300});near(m.sample(250).radius,a.radius);assert.deepEqual(m.sample(250).origin,{x:50,y:70});assert.equal(m.sample(500).phase,'revealed');});
test('hide finishes and next tap can pick a new origin',()=>{const m=M.createModel();m.reveal(0);m.hide(200);assert.equal(m.sample(440).phase,'hidden');m.reveal(500,{x:350,y:30});assert.deepEqual(m.sample(500).origin,{x:350,y:30});});
test('repeated hide is idempotent',()=>{const m=M.createModel();assert.equal(m.hide(10),false);m.reveal(20);m.hide(120);assert.equal(m.hide(130),false);assert.equal(m.sample(500).phase,'hidden');});
test('reset clears active state without stale animation',()=>{const m=M.createModel();m.reveal(0,{x:40,y:30});m.reset(50);assert.equal(m.sample(900).phase,'hidden');assert.deepEqual(m.sample(900).origin,{x:240,y:180});});
test('pointer is clamped to image bounds',()=>{const m=M.createModel();m.reveal(0,{x:-60,y:1000});assert.deepEqual(m.sample(0).origin,{x:0,y:360});});
test('resize preserves normalized origin and current progress',()=>{const m=M.createModel();m.reveal(0,{x:120,y:270});const p=m.sample(50).progress;m.resize(960,720);assert.deepEqual(m.sample(50).origin,{x:240,y:540});near(m.sample(50).progress,p);});
for(const [w,h] of [[240,180],[320,240],[480,360],[960,720],[600,200],[200,600]])test(`farthest corner is covered at ${w}×${h}`,()=>{const m=M.createModel({width:w,height:h});m.reveal(0,{x:w*.09,y:h*.84});const s=m.sample(180);assert.ok(s.radius>M.maxRadius(w,h,s.origin.x,s.origin.y));});
test('reduced motion is immediate',()=>{const m=M.createModel({reducedMotion:true});m.reveal(5);assert.equal(m.sample(5).phase,'revealed');m.hide(6);assert.equal(m.sample(6).phase,'hidden');});
test('enabling reduced motion during reveal settles',()=>{const m=M.createModel();m.reveal(0);m.setReducedMotion(true,35);assert.equal(m.sample(35).phase,'revealed');});
test('turning reduced motion back off does not restart',()=>{const m=M.createModel({reducedMotion:true});m.reveal(0);m.setReducedMotion(false,20);assert.equal(m.sample(20).phase,'revealed');});
test('seeded particles are deterministic',()=>{assert.deepEqual(M.makeParticles(13),M.makeParticles(13));assert.notDeepEqual(M.makeParticles(13,1),M.makeParticles(14,1));});
test('particle trajectories are coherent, bounded and finite',()=>{const ps=M.makeParticles(123,200);for(const t of [0,.016,10,600,10000])for(const p of ps){const a=M.particleAt(p,t,480,360);assert.ok(a.x>=0&&a.x<480&&a.y>=0&&a.y<360&&a.alpha>=0&&a.alpha<=1);}});
test('particles vary over time, not a static texture',()=>{const p=M.makeParticles(1,1)[0];assert.notDeepEqual(M.particleAt(p,0,480,360),M.particleAt(p,1,480,360));});
test('one-frame movement is locally small away from wraps',()=>{for(const p of M.makeParticles(7,200)){let a=M.particleAt(p,2,480,360),b=M.particleAt(p,2+1/60,480,360);const dx=Math.min(Math.abs(a.x-b.x),480-Math.abs(a.x-b.x)),dy=Math.min(Math.abs(a.y-b.y),360-Math.abs(a.y-b.y));assert.ok(Math.hypot(dx,dy)<1);}});
test('feather covers a broad continuous range',()=>{near(M.maskAlpha(100,100,60),.5);near(M.maskAlpha(40,100,60),0);near(M.maskAlpha(160,100,60),1);});
test('100 interrupted cycles settle cleanly',()=>{const m=M.createModel();for(let i=0;i<100;i++){let t=i*1000;m.reveal(t,{x:i%480,y:i%360});m.hide(t+35);m.reveal(t+40);m.hide(t+65);assert.equal(m.sample(t+900).phase,'hidden');}});
test('Gaussian disk has zero opacity at zero radius',()=>{assert.equal(M.diskAlpha(0,0,42),0);assert.equal(M.diskAlpha(100,0,42),0);});
test('Gaussian disk is radially monotone and bounded',()=>{let prev=1;for(let d=0;d<400;d++){const a=M.diskAlpha(d,150,44);assert.ok(a>=0&&a<=1);assert.ok(a<=prev+.0001);prev=a;}});
test('Gaussian-disk center calibration matches early source range approximately',()=>{const sigma=42*504/480;near(M.diskAlpha(0,25,sigma),.148,0.01);near(M.diskAlpha(0,58,sigma),.579,0.01);assert.ok(M.diskAlpha(0,119,sigma)>.97);});
test('expanded disk clears corners smoothly before terminal state',()=>{assert.ok(M.diskAlpha(339,455,44)>.99);});
