const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('crypto');const {createCanvas,loadImage}=require('@napi-rs/canvas');const M=require('../src/motion.js');const path=require('path');
const assetsPromise=Promise.all(['original-still-life.png','original-still-life-blurred.png'].map(p=>loadImage(path.join(__dirname,'../assets',p)))).then(([clear,blur])=>({clear,blur}));
async function render(time,m,options={}){const c=createCanvas(options.width||480,options.height||360);M.renderMedia(c.getContext('2d'),{model:m.sample(time),time,width:c.width,height:c.height,assets:await assetsPromise,particles:M.makeParticles(),createCanvas,...options});return c;}
const hash=c=>crypto.createHash('sha256').update(c.toBuffer('image/png')).digest('hex');
test('same seed, model and time produce identical pixels',async()=>{const m=M.createModel();assert.equal(hash(await render(500,m)),hash(await render(500,m)));});
test('hidden particle pixels evolve',async()=>{const m=M.createModel();assert.notEqual(hash(await render(100,m)),hash(await render(400,m)));});
test('reduced motion freezes hidden particle field',async()=>{const m=M.createModel({reducedMotion:true});assert.equal(hash(await render(100,m)),hash(await render(400,m)));});
test('fully revealed pixels do not keep animating',async()=>{const m=M.createModel();m.reveal(0);assert.equal(hash(await render(180,m)),hash(await render(10000,m)));});
test('intermediate reveal differs from both endpoints',async()=>{const m=M.createModel();m.reveal(100);const a=hash(await render(100,m)),b=hash(await render(150,m)),c=hash(await render(300,m));assert.notEqual(a,b);assert.notEqual(b,c);});
test('output has transparent rounded corners and opaque center',async()=>{const c=await render(0,M.createModel()),g=c.getContext('2d');assert.equal(g.getImageData(0,0,1,1).data[3],0);assert.equal(g.getImageData(240,180,1,1).data[3],255);});
for(const [w,h] of [[240,180],[480,360],[960,720]])test(`pixel render at ${w}×${h}`,async()=>{const c=await render(0,M.createModel(),{width:w,height:h});assert.equal(c.width,w);assert.equal(c.height,h);assert.ok(c.toBuffer('image/png').length>1000);});
test('soft disk begins translucent instead of a hard opaque core',()=>{const clear=createCanvas(480,360),blur=createCanvas(480,360);clear.getContext('2d').fillRect(0,0,480,360);const b=blur.getContext('2d');b.fillStyle='#fff';b.fillRect(0,0,480,360);const m=M.createModel();m.reveal(0);const c=createCanvas(480,360),g=c.getContext('2d');M.renderMedia(g,{model:m.sample(8.333),time:8.333,assets:{clear,blur},particles:[],createCanvas});let v=g.getImageData(240,180,1,1).data[0];assert.ok(v>130&&v<250,`early center luminance ${v}`);});
test('reset renders the exact original hidden state at identical time',async()=>{const m=M.createModel();m.reveal(0);m.reset(100);assert.equal(hash(await render(100,m)),hash(await render(100,M.createModel())));});
