const fs=require('fs'),path=require('path'),cp=require('child_process'),crypto=require('crypto'),{createCanvas,GlobalFonts}=require('@napi-rs/canvas'),S=require('./scene.js');
for(const w of ['Regular','Medium','Semibold'])GlobalFonts.registerFromPath(path.join(__dirname,'assets/StudySans-'+w+'.ttf'),'Replica Sans');GlobalFonts.registerFromPath(path.join(__dirname,'assets/Mono.ttf'),'Replica Mono');
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const sceneHash=sha(fs.readFileSync(path.join(__dirname,'scene.js'))),motionHash=sha(fs.readFileSync(path.join(__dirname,'motion-data.js')));
function assertSourceUnchanged(){if(sceneHash!==sha(fs.readFileSync(path.join(__dirname,'scene.js')))||motionHash!==sha(fs.readFileSync(path.join(__dirname,'motion-data.js'))))throw Error('Source changed during render');}
(async()=>{const c=createCanvas(S.W,S.H),x=c.getContext('2d'),out=path.join(__dirname,'preview');fs.mkdirSync(out,{recursive:true});for(const[label,t]of Object.entries(S.STILLS)){S.draw(x,t);fs.writeFileSync(path.join(out,label+'.png'),await c.encode('png'));}if(process.argv.includes('--stills'))return;
const enc=cp.spawn('ffmpeg',['-y','-v','error','-f','rawvideo','-pix_fmt','rgba','-s',S.W+'x'+S.H,'-r',String(S.FPS),'-i','pipe:0','-an','-c:v','libx264','-threads','2','-preset','medium','-crf','18','-pix_fmt','yuv420p','-movflags','+faststart',path.join(out,'loop.mp4')],{stdio:['pipe','inherit','inherit']}),done=new Promise((r,j)=>enc.once('exit',n=>n?j(Error('ffmpeg '+n)):r())),frames=[];
for(let n=0;n<S.DURATION*S.FPS;n++){S.draw(x,n/S.FPS);const a=x.getImageData(0,0,S.W,S.H).data,b=Buffer.from(a.buffer,a.byteOffset,a.byteLength);frames.push({n,t:n/S.FPS,rgba_sha256:sha(b)});if(!enc.stdin.write(b))await new Promise(r=>enc.stdin.once('drain',r));if(n%30===0&&global.gc)global.gc();if(n%120===0)console.log(n+'/'+S.DURATION*S.FPS);}enc.stdin.end();await done;
const palette=path.join(out,'palette.png');cp.execFileSync('ffmpeg',['-y','-v','error','-threads','2','-filter_threads','1','-i',path.join(out,'loop.mp4'),'-vf','fps=20,scale=864:-1:flags=lanczos,palettegen=stats_mode=diff','-frames:v','1',palette]);cp.execFileSync('ffmpeg',['-y','-v','error','-threads','2','-filter_complex_threads','1','-i',path.join(out,'loop.mp4'),'-i',palette,'-lavfi','fps=20,scale=864:-1:flags=lanczos[v];[v][1:v]paletteuse=dither=bayer:bayer_scale=3','-loop','0',path.join(out,'loop.gif')]);
S.draw(x,0);const first=sha(Buffer.from(x.getImageData(0,0,S.W,S.H).data));S.draw(x,S.DURATION);const last=sha(Buffer.from(x.getImageData(0,0,S.W,S.H).data));
assertSourceUnchanged();fs.writeFileSync(path.join(out,'preview.json'),JSON.stringify({renderer:'Offline Canvas 2D from the same scene used by the app; not a browser recording',width:S.W,height:S.H,fps:S.FPS,frames:S.DURATION*S.FPS,duration:S.DURATION,scene_sha256:sha(fs.readFileSync(path.join(__dirname,'scene.js'))),motion_data_sha256:sha(fs.readFileSync(path.join(__dirname,'motion-data.js'))),mp4_sha256:sha(fs.readFileSync(path.join(out,'loop.mp4'))),gif_sha256:sha(fs.readFileSync(path.join(out,'loop.gif'))),loop_endpoints_rgba_equal:first===last},null,2));fs.writeFileSync(path.join(out,'render-bindings.json'),JSON.stringify({renderer:'@napi-rs/canvas 0.1.100',scene_sha256:sha(fs.readFileSync(path.join(__dirname,'scene.js'))),motion_data_sha256:sha(fs.readFileSync(path.join(__dirname,'motion-data.js'))),loop_endpoint_hashes:[first,last],frames},null,2));console.log('Media complete');})();
