(function(root,factory){if(typeof module==='object')module.exports=factory(require('./motion-data.js'));else root.Scene=factory(root.AgentPlanMotion);})(this,function(Motion){
'use strict';
const W=1080,H=882,FPS=60,DURATION=20;
const STEPS=[
 {title:'Search competitor pricing pages',description:['Query Google for the pricing pages of our top 5 competitors and','collect URLs.'],tool:'Web',icon:'search'},
 {title:'Extract pricing tiers',description:['Read each pricing page and pull plan names, prices, and feature','lists.'],tool:'Browser',icon:'file'},
 {title:'Compare to our plans',description:['Match feature parity, find gaps, and flag pricing outliers.'],tool:'Reasoning',icon:'star'},
 {title:'Draft summary doc',description:['Write a 1-page brief with recommendations and a comparison','table.'],tool:'Notion',icon:'pencil'},
 {title:'Email draft to product team',description:['Send the brief to product@acme.co with a request for feedback by','Friday.'],tool:'Gmail',icon:'send'}
];
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const ease=v=>{v=clamp(v);return v*v*(3-2*v);};
const mix=(a,b,t)=>a+(b-a)*t;
function initial(){return{statuses:Array(5).fill('planned'),expanded:0,phase:'review',queue:[],cursor:0,elapsed:0,ran:0};}
function clean(s){return{statuses:[...s.statuses],expanded:s.expanded,phase:s.phase,queue:[...(s.queue||[])],cursor:s.cursor||0,elapsed:s.elapsed||0,ran:s.ran||0};}
function action(state,a){const s=clean(state);if(a.type==='reset')return initial();if(a.type==='tick'){if(s.phase!=='running')return s;s.elapsed+=Math.max(0,a.seconds||0);while(s.phase==='running'&&s.elapsed>=1.8){s.elapsed-=1.8;s.statuses[s.queue[s.cursor]]='done';s.ran++;s.cursor++;if(s.cursor>=s.queue.length){s.phase='complete';s.expanded=-1;}else s.statuses[s.queue[s.cursor]]='running';}return s;}if(s.phase!=='review')return s;
 if(a.type==='toggle'){s.expanded=s.expanded===a.index?-1:clamp(a.index,0,4);return s;}
 if(a.type==='approveAll'){s.statuses=s.statuses.map(()=> 'approved');return s;}
 if(a.type==='run'){s.queue=s.statuses.flatMap((v,i)=>v==='approved'?[i]:[]);if(!s.queue.length)return s;s.phase='running';s.cursor=0;s.elapsed=0;s.ran=0;s.expanded=-1;s.statuses[s.queue[0]]='running';return s;}
 if(['approve','skip','undo'].includes(a.type)){const i=clamp(a.index,0,4);s.statuses[i]=a.type==='approve'?'approved':a.type==='skip'?'skipped':'planned';s.expanded=a.type==='undo'?i:s.statuses.findIndex((v,j)=>j>i&&v==='planned');return s;}return s;
}
function counts(s){return{decided:s.statuses.filter(v=>v!=='planned').length,approved:s.statuses.filter(v=>v==='approved').length,skipped:s.statuses.filter(v=>v==='skipped').length,done:s.statuses.filter(v=>v==='done').length};}
const APPROVALS=[[.75,0],[1.883333,1],[2.933333,2],[4.1,3],[5.416667,4]];
const EXPANSIONS=[[0,0],[.84,1],[2.08,2],[3.1,3],[4.28,4],[5.56,-1]];
function weightsAt(t){const weights=Array(5).fill(0);let previous=0;for(let k=1;k<EXPANSIONS.length;k++){const [at,next]=EXPANSIONS[k];if(t<at){if(previous>=0)weights[previous]=1;return weights;}if(t<at+.32){const p=ease((t-at)/.32);if(previous>=0)weights[previous]=1-p;if(next>=0)weights[next]=p;return weights;}previous=next;}if(previous>=0)weights[previous]=1;return weights;}
function timeline(time){let t=Number((((time%DURATION)+DURATION)%DURATION).toFixed(6)),opacity=1;if(t>=18.8&&t<19.2)opacity=1-ease((t-18.8)/.4);if(t>=19.2){opacity=ease((t-19.2)/.5);t=0;}let lo=0,hi=Motion.rows.length-1;while(lo<hi){const mid=Math.ceil((lo+hi)/2);if(Motion.rows[mid].t<=Math.min(t,18.25)+.000001)lo=mid;else hi=mid-1;}const r=Motion.rows[lo],s=initial();s.recorded=true;s.time=t;s.opacity=opacity;s.motion=r;s.completeInk=r.completeInk;s.weights=[...r.weights];if(t<4.1||t>=6.5)s.weights[4]=0;if(t>=5.416667&&t<6.5){const elapsed=t-4.666667;let cr=Motion.rows[11];for(const row of Motion.rows){if(row.t>elapsed+.000002)break;cr=row;}s.weights[4]=clamp(cr.extra[0]/137);}s.completeBlend=t>=15.083333&&t<16.416667?1:r.completeAlpha;s.expanded=s.weights.some(v=>v>.1)?s.weights.indexOf(Math.max(...s.weights)):-1;s.recordedRunLabel='';
 for(const[at,i]of APPROVALS)if(t>=at)s.statuses[i]=i===4?'skipped':'approved';
 if(t>=6.783333&&t<14.783333){s.phase='running';s.expanded=-1;s.weights=Array(5).fill(0);const starts=[6.783333,8.583333,10.783333,12.383333];let k=0;for(let i=0;i<4;i++)if(t>=starts[i])k=i;s.cursor=k;s.queue=[0,1,2,3];s.statuses=s.statuses.map((v,i)=>i<k?'done':i===k?'running':v);s.ran=k;const left=4-k;s.recordedRunLabel='Running step '+Math.min(k+1,left)+' of '+left;}
 if(t>=14.783333&&t<16.416667){s.phase='complete';s.expanded=-1;s.weights=Array(5).fill(0);s.statuses=['done','done','done','running','skipped'];s.ran=0;s.recordedRunLabel='Running step 1 of 1';}
 if(t>=16.416667){s.phase='review';s.statuses=Array(5).fill(t>=18.083333?'approved':'planned');s.expanded=0;}
 return s;
}
function layout(s){const weights=s.weights||STEPS.map((_,i)=>i===s.expanded?1:0),extra=weights.reduce((a,w,i)=>a+w*(STEPS[i].description.length===1?115:137),0),complete=s.completeBlend??(s.phase==='complete'?1:0),reviewHeight=461+extra,height=mix(reviewHeight,323,complete),y=(873-height)/2,innerY=y+71,innerH=mix(312+extra,239,complete);let offset=0;const rows=STEPS.map((step,i)=>{const row={index:i,top:innerY+16+i*59+offset,titleY:innerY+42+i*59+offset,weight:weights[i]};offset+=weights[i]*(step.description.length===1?115:137);row.bottom=innerY+68+i*59+offset;return row;});if(s.motion){const r=s.motion,ry=r.y,iy=ry+70;const nativeRows=rows.map((v,i)=>({...v,top:r.titleYs[i]-26,titleY:r.titleYs[i],bottom:i<4?r.titleYs[i+1]-33:r.titleYs[4]+25+137*weights[4]}));return{x:253,y:ry,w:568,h:r.h-1,innerX:266,innerY:iy,innerW:542,innerH:r.innerH+1,rows:nativeRows,complete,weights,footerY:ry+r.h-43};}return{x:253,y,w:568,h:height,innerX:266,innerY,innerW:542,innerH,rows,complete,weights,footerY:y+height-42};}
function rr(c,x,y,w,h,r,fill,stroke){c.beginPath();c.roundRect(x,y,Math.max(.1,w),Math.max(.1,h),r);if(fill){c.fillStyle=fill;c.fill();}if(stroke){c.lineWidth=1;c.strokeStyle=stroke;c.stroke();}}
function text(c,s,x,y,size=16,col='#22252b',weight=400,align='left',family='Replica Sans',sx=1,stroke=0){c.save();c.translate(x,y);c.scale(sx,1);c.font=`${weight} ${size}px "${family}"`;c.textAlign=align;c.textBaseline='alphabetic';c.fillStyle=col;if(stroke){c.strokeStyle=col;c.lineWidth=stroke;c.strokeText(s,0,0);}c.fillText(s,0,0);c.restore();}
function line(c,x,y,X,Y,col,width=1){c.beginPath();c.moveTo(x,y);c.lineTo(X,Y);c.strokeStyle=col;c.lineWidth=width;c.stroke();}
function icon(c,type,x,y,col='#777b83',t=0,width=1.45){c.save();c.translate(x,y);c.strokeStyle=col;c.fillStyle=col;c.lineWidth=width;c.lineCap='round';c.lineJoin='round';c.beginPath();if(type==='search'){c.arc(-1,-1,4.5,0,Math.PI*2);c.moveTo(2.5,2.5);c.lineTo(6,6);c.stroke();}else if(type==='file'){c.moveTo(-4,-6);c.lineTo(1,-6);c.lineTo(5,-2);c.lineTo(5,6);c.lineTo(-4,6);c.closePath();c.moveTo(0,-6);c.lineTo(0,-1);c.lineTo(5,-1);c.moveTo(-1,2);c.lineTo(2,2);c.stroke();}else if(type==='star'){c.moveTo(0,-6);c.quadraticCurveTo(1,0,6,0);c.quadraticCurveTo(1,1,0,6);c.quadraticCurveTo(-1,1,-6,0);c.quadraticCurveTo(-1,-1,0,-6);c.fill();}else if(type==='pencil'){c.rotate(.68);c.roundRect(-2.5,-6,5,11,1);c.moveTo(-2.5,2);c.lineTo(2.5,2);c.moveTo(-2.5,5);c.lineTo(0,8);c.lineTo(2.5,5);c.stroke();}else if(type==='send'){c.moveTo(-6,-1);c.lineTo(6,-6);c.lineTo(2,7);c.lineTo(-1,1);c.closePath();c.moveTo(-1,1);c.lineTo(6,-6);c.stroke();}else if(type==='check'){c.moveTo(-5,0);c.lineTo(-1,4);c.lineTo(6,-5);c.stroke();}else if(type==='spinner'){c.rotate(t*4);c.arc(0,0,6.2,-Math.PI*.45,Math.PI*1.15);c.stroke();}else if(type==='play'){c.moveTo(-2,-4);c.lineTo(4,0);c.lineTo(-2,4);c.closePath();c.stroke();}else if(type==='undo'){c.arc(0,0,5,-2.4,2.4);c.moveTo(-5,-5);c.lineTo(-5,0);c.lineTo(0,-1);c.stroke();}c.restore();}
const STATUS={planned:['Planned','#f0f0f0','#686870'],approved:['Approved','#e7fff4','#0a825c'],skipped:['Skipped','#f2f2f4','#888b94'],running:['Running','#fffae6','#9e5809'],done:['Done','#e7fff4','#0a825c']};
function badge(c,status,y,palette){let [label,bg,ink]=STATUS[status];if(palette){bg='rgb('+palette.map(Math.round).join(',')+')';const strength=status==='running'?clamp((palette[0]-palette[2])/35):status==='approved'||status==='done'?clamp((palette[1]-palette[0])/24):0;const target=status==='running'?[158,88,9]:[10,130,92];if(status!=='planned'&&status!=='skipped')ink='rgb('+[104,104,112].map((v,i)=>Math.round(mix(v,target[i],strength))).join(',')+')';}c.font='400 12px "Replica Sans"';const w=c.measureText(label).width+(status==='approved'?22:19);rr(c,787-w,y-18,w,23,12,bg);text(c,label,787-w/2,y-1,12,ink,500,'center');}
function pill(c,x,y,w,label,kind='neutral',symbol,time=0,override){const blend=(a,b)=>'rgb('+a.map((v,i)=>Math.round(mix(v,b[i],time))).join(',')+')';const bg=override?.bg|| (kind==='enabling'?blend([222,222,229],[23,25,28]):kind==='green'?'#008e63':kind==='dark'?'#17191c':kind==='disabled'?'#dedee5':kind==='running'?'#fff5b9':'#f1f1f4'),fg=override?.fg|| (kind==='enabling'?blend([170,170,170],[255,255,255]):kind==='green'||kind==='dark'?'#fff':kind==='disabled'?'#aaa':kind==='running'?'#995500':'#565a65');rr(c,x,y,w,38,20,bg);if(symbol)icon(c,symbol,x+(symbol==='spinner'?21:18),y+19,fg,time);text(c,label,x+w/2+(symbol==='spinner'?10:symbol?6:0),y+25,14,fg,kind==='green'||kind==='dark'?500:400,'center');}
const buttonSurfaces=new WeakMap();
function approveButton(c,s,py,fill){
 if(s.recorded&&s.time>=16.416667&&s.time<16.75&&(s.completeBlend>0||s.completeInk>0)){
  let layer=buttonSurfaces.get(c.canvas);if(!layer){layer=c.canvas.ownerDocument?c.canvas.ownerDocument.createElement('canvas'):new c.canvas.constructor(90,34);layer.width=90;layer.height=34;buttonSurfaces.set(c.canvas,layer);}
  const b=layer.getContext('2d');b.clearRect(0,0,90,34);rr(b,0,0,90,34,18,fill);icon(b,'check',16,17,'#fff');text(b,'Approve',26,22,14,'#fff',400);c.drawImage(layer,325,py);
 }else{rr(c,325,py,90,34,18,fill);icon(c,'check',341,py+17,'#fff');text(c,'Approve',351,py+22,14,'#fff',400);}
}
function reviewLayer(c,s,l,t){c.save();c.globalAlpha*=1-l.complete;c.beginPath();c.roundRect(l.innerX,l.innerY,l.innerW,s.phase==='complete'?Math.max(l.innerH,312):l.innerH,23);c.clip();l.rows.forEach((r,i)=>{const step=STEPS[i],status=s.statuses[i],active=status==='approved'||status==='done',ink=status==='skipped'&&s.recorded?'rgb('+[25,26,29].map((v,j)=>Math.round(mix(v,[167,167,176][j],ease((s.time-5.416667)/.12)))).join(',')+')':status==='skipped'?'#a7a7b0':'#191a1d',symbol=status==='done'?'check':status==='running'?'spinner':step.icon;let activeInk='#00a36b',skipInk='#b6b9c3';if(s.motion&&l.complete===0){const p=s.motion.badgeColors[i],strength=clamp((p[1]-p[0])/24),old=status==='done'?[238,146,5]:[104,104,112];activeInk='rgb('+old.map((v,j)=>Math.round(mix(v,[0,163,107][j],strength))).join(',')+')';skipInk='rgb('+[104,104,112].map((v,j)=>Math.round(mix(v,[182,185,195][j],ease((s.time-5.416667)/.12)))).join(',')+')';}icon(c,symbol,299,r.titleY-4,status==='running'?'#ee9205':active?activeInk:status==='skipped'?skipInk:'#797d86',s.motion?.spinnerAngles[i]!==null&&s.motion?.spinnerAngles[i]!==undefined?s.motion.spinnerAngles[i]/4:t);text(c,step.title,325,r.titleY+1,16.5,ink,400,'left','Replica Sans',.96,.3);if(status==='skipped'){c.font='400 16px "Replica Sans"';line(c,325,r.titleY-5,325+c.measureText(step.title).width,r.titleY-5,ink,1.1);}badge(c,status,r.titleY,l.complete===0?s.motion?.badgeColors[i]:undefined);
 if(r.weight>.001){c.save();c.globalAlpha*=r.weight;c.beginPath();c.rect(315,r.titleY+10,480,Math.max(0,r.bottom-r.titleY-26));c.clip();c.translate(0,-14*(1-r.weight));step.description.forEach((v,j)=>text(c,v,325,r.titleY+35+j*22,14.5,'#65656c',400,'left','Replica Sans',1,.15));const toolY=r.titleY+(step.description.length===1?54:76);c.font='400 12px "Replica Mono"';const tw=c.measureText(step.tool).width+14;rr(c,325,toolY,tw,24,5,'#f2f3f5');text(c,step.tool,332,toolY+16,12,'#757981',400,'left','Replica Mono');const py=toolY+38;if(status==='planned'||s.recorded&&s.time<16.4){approveButton(c,s,py,s.recorded&&s.motion.cursor[0]>=325&&s.motion.cursor[0]<415&&s.motion.cursor[1]>=py&&s.motion.cursor[1]<py+34?'#08814f':'#00a169');rr(c,423,py,66,34,18,s.recorded&&s.motion.cursor[0]>=423&&s.motion.cursor[0]<489&&s.motion.cursor[1]>=py&&s.motion.cursor[1]<py+34?'#dddde2':'#f0f0f3');text(c,'× Skip',456,py+22,14,'#555a65',400,'center');}else{rr(c,325,py,56,32,16,'#f0f0f3');text(c,'Undo',353,py+22,14,'#34343b',400,'center');}c.restore();}
 if(i<4){c.save();c.setLineDash([3,3]);line(c,288,r.bottom,786,r.bottom,'#dcdcdc',.8);c.restore();}});c.restore();
 if(s.phase==='complete')return;c.save();const n=counts(s),fy=l.footerY;if(s.phase==='running'){const label=s.recordedRunLabel||'Running step '+(s.cursor+1)+' of '+s.queue.length;text(c,label,278,fy+5,14,'#666670');pill(c,673,fy-20,123,'In progress','running','spinner',s.motion?.footerSpinnerAngle!==null&&s.motion?.footerSpinnerAngle!==undefined?s.motion.footerSpinnerAngle/4:t,s.recorded?{bg:'rgb('+s.motion.footerColor.join(',')+')'}:undefined);}else{text(c,n.approved+' approved',278,fy+5,14,'#666670');if(n.decided<5){if(s.recorded&&s.motion.cursor[0]>=582&&s.motion.cursor[0]<679&&s.motion.cursor[1]>=fy-20&&s.motion.cursor[1]<fy+18){c.save();c.globalAlpha*=s.time>=17?ease((s.time-17.666667)/.1):1;rr(c,582,fy-20,97,38,20,'#dedee3');c.restore();}text(c,'Approve all',593,fy+5,14,'#454954');}pill(c,690,fy-20,106,'Run plan',n.approved?(s.recorded&&s.time<1?'enabling':'dark'):'disabled','play',s.recorded?ease((s.time-.75)/.24):1,s.recorded&&s.time>=.75&&s.time<1.1||s.recorded&&s.time>=18.083333?{bg:'rgb('+s.motion.footerColor.join(',')+')',fg:'rgb('+[0,0,0].map(()=>Math.round(255-clamp((s.motion.footerColor[0]-23)/199)*85)).join(',')+')'}:undefined);}c.restore();}
function completeLayer(c,s,l){
 const ink=s.completeInk??l.complete;if(ink<=0)return;c.save();c.globalAlpha*=ink;const y=l.innerY;
 rr(c,292,y+32,42,43,14,'#ccfee0');c.save();c.lineWidth=2.6;icon(c,'check',313,y+53,'#09a371',0,2.6);c.restore();
 text(c,'Plan executed',292,y+114,21,'#1b1e23',500,'left','Replica Sans',.96,.55);const n=counts(s);
 text(c,(s.recorded?0:s.ran)+' steps ran. '+(s.recorded?1:n.skipped)+' skipped. Output sent to your inbox.',292,y+145,14.5,'#71717b');
 const py=y+167,reset=s.recorded&&s.time>=16.416667,hover=s.recorded&&(reset&&s.time<16.8||s.motion.cursor[0]>=292&&s.motion.cursor[0]<407&&s.motion.cursor[1]>=py&&s.motion.cursor[1]<py+42);
 c.save();if(reset)c.globalAlpha*=Math.min(1,(1-ease((s.time-16.416667)/.2))/Math.max(ink,.001));rr(c,292,py,115,42,22,hover?'#dfdfe4':'#f0f0f2');c.restore();
 icon(c,'undo',314,py+21,'#45454c');text(c,'New plan',359,py+27,14,'#34343b',400,'center');c.restore();
}
function draw(c,time,assets={},manual){const s=manual||timeline(time),l=layout(s),n=counts(s),opacity=s.opacity??1;c.clearRect(0,0,W,H);c.fillStyle='#fdfdfd';c.fillRect(0,0,W,H);c.save();c.globalAlpha=opacity;c.save();c.shadowColor=`rgba(27,30,37,${.32*opacity})`;c.shadowBlur=31;c.shadowOffsetY=15;rr(c,l.x,l.y,l.w,l.h,38,'#f0f0f0');c.restore();c.save();c.shadowColor=`rgba(27,30,37,${.35*opacity})`;c.shadowBlur=2;c.shadowOffsetY=3;rr(c,l.x,l.y,l.w,l.h,38,'#f0f0f0');c.restore();text(c,'Agent plan',282,l.y+44,17.5,'#141519',600,'left','Replica Sans',.96,.15);rr(c,379,l.y+26,78,26,14,'#e2e3e9');text(c,'5 steps',418,l.y+44,12,'#6b707b',400,'center','Replica Mono');const heading=s.phase==='running'?'Running plan':s.phase==='complete'?'Plan complete':n.decided+' of 5 decided';const paintHeading=(label,alpha,dy=0,dotDy=0)=>{if(alpha<=0)return;c.save();c.globalAlpha*=alpha;text(c,label,790,l.y+42+dy,14,label==='Running plan'?'#b66000':label==='Plan complete'?'#009b68':'#5e5e68',500,'right','Replica Sans',.96);if(label==='Running plan'){c.fillStyle='#fde7be';c.beginPath();c.arc(695.5,l.y+37+dotDy,8,0,7);c.fill();c.fillStyle='#ef9309';c.beginPath();c.arc(695.5,l.y+37+dotDy,4.8,0,7);c.fill();}c.restore();};let headerTransition=null;if(s.recorded){for(const [at,oldLabel,newLabel,span]of [[6.783333,'5 of 5 decided','Running plan',.15],[14.783333,'Running plan','Plan complete',.15],[16.416667,'Plan complete','0 of 5 decided',.1]])if(s.time>=at&&s.time<at+span)headerTransition={p:ease((s.time-at)/span),oldLabel,newLabel};}if(s.motion?.runHeader)headerTransition={...s.motion.runHeader,oldLabel:'5 of 5 decided',newLabel:'Running plan'};if(headerTransition){const h=headerTransition;paintHeading(h.oldLabel,h.oldAlpha??1-h.p,h.oldDy??-2*h.p);paintHeading(h.newLabel,h.newAlpha??h.p,h.newDy??2*(1-h.p),h.newDy??0);}else paintHeading(heading,1);rr(c,l.innerX,l.innerY,l.innerW,l.innerH,23,'#fff');if(s.recorded&&s.time>=16.416667&&s.time<16.75){completeLayer(c,s,l);reviewLayer(c,s,l,time);}else{reviewLayer(c,s,l,time);completeLayer(c,s,l);}if(s.recorded&&s.motion?.cursor){const [cx,cy]=s.motion.cursor;c.save();c.translate(cx-1,cy-1);c.shadowColor=`rgba(0,0,0,${.25*opacity})`;c.shadowBlur=2;c.shadowOffsetY=1;c.beginPath();c.moveTo(0,0);c.lineTo(0,15);c.lineTo(4,11);c.lineTo(7.4,18);c.lineTo(10,16.8);c.lineTo(6.7,10);c.lineTo(12,10);c.closePath();c.lineWidth=3;c.lineJoin='round';c.strokeStyle='#fff';c.stroke();c.fillStyle='#101010';c.fill();c.restore();}c.restore();return l;}
function hitTargets(s){const l=layout(s),targets=[];if(s.phase==='complete'){targets.push({label:'New plan',x:292,y:l.innerY+167,w:115,h:42,action:{type:'reset'}});return targets;}if(s.phase==='running')return targets;for(const r of l.rows){targets.push({label:STEPS[r.index].title,x:286,y:r.titleY-25,w:502,h:42,action:{type:'toggle',index:r.index}});if(r.weight>.8){const y=r.titleY+(STEPS[r.index].description.length===1?54:76)+38;if(s.statuses[r.index]==='planned'||s.recorded&&s.time<16.4){targets.push({label:'Approve '+STEPS[r.index].title,x:325,y,w:90,h:34,action:{type:'approve',index:r.index}},{label:'Skip '+STEPS[r.index].title,x:423,y,w:66,h:34,action:{type:'skip',index:r.index}});}else targets.push({label:'Undo '+STEPS[r.index].title,x:325,y,w:56,h:32,action:{type:'undo',index:r.index}});}}const n=counts(s);if(n.decided<5)targets.push({label:'Approve all',x:580,y:l.footerY-20,w:99,h:38,action:{type:'approveAll'}});targets.push({label:'Run plan',x:690,y:l.footerY-20,w:106,h:38,disabled:!n.approved,action:{type:'run'}});return targets;}
return{W,H,FPS,DURATION,STEPS,initial,clean,action,counts,timeline,layout,draw,hitTargets,STILLS:{initial:0,review:2.6,decided:6,running:9,complete:15.8}};
});
