import {CONTROLS} from './controls.mjs';import {DIGITS,DIGIT_UNITS,TOOLTIP_TYPE} from './type.mjs';import {FLAME,INNER,SEED,STAR,ARROW,HAND,flameMarkup,projectSeed} from './art.mjs';
export const WIDTH=1144,HEIGHT=720,DURATION=14;
export const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),mix=(a,b,p)=>a+(b-a)*p;const n=x=>Number(x.toFixed(4)),clone=x=>structuredClone(x);
export function nativeState(t){const raw=clamp(t*60,0,799),p=Math.abs(raw-Math.round(raw))<.001?Math.round(raw):raw,i=Math.floor(p),j=Math.min(i+1,799),u=p-i,a=CONTROLS[i],b=CONTROLS[j],s=clone(a);for(const k of ['pill','buttonFill','buttonScale'])s[k]=a[k].map((v,q)=>mix(v,b[k][q],u));for(const k of ['alpha','textX','digitY','digitBlur','shift','dayOffset'])s[k]=mix(a[k],b[k],u);if(a.flame&&b.flame)for(const k of ['x','y','sx','sy','rotation','alpha'])s.flame[k]=mix(a.flame[k],b.flame[k],u);if(a.cursor[3]&&b.cursor[3]&&a.cursor[2]===b.cursor[2])s.cursor=[mix(a.cursor[0],b.cursor[0],u),mix(a.cursor[1],b.cursor[1],u),a.cursor[2],1];return s;}
export function demoState(t){t=((t%DURATION)+DURATION)%DURATION;const s=nativeState(t>13.4?0:Math.min(t,799/60));if(t>13.4)s.cursor=[...CONTROLS[0].cursor.slice(0,3),clamp((t-13.4)/.35)];return s;}
function roundRect(x,y,w,h,r,fill,extra=''){return `<rect x="${n(x)}" y="${n(y)}" width="${n(Math.max(0,w))}" height="${n(Math.max(0,h))}" rx="${n(r)}" fill="${fill}" ${extra}/>`;}
function cursor(c){if(!c?.[3])return '';return `<g opacity="${n(c[3])}" transform="translate(${n(c[0])} ${n(c[1])})"><path d="${c[2]===1?HAND:ARROW}" transform="translate(1 2)" fill="#000" opacity=".17" filter="url(#cursorShadow)"/><path d="${c[2]===1?HAND:ARROW}" fill="${c[2]===1?'#fff':'#050505'}" stroke="${c[2]===1?'#424242':'#fff'}" stroke-width="1.3" stroke-linejoin="round" stroke-linecap="round"/></g>`;}
export function scene(s){const [x,y,w,h]=s.pill;let out=`<svg xmlns="http://www.w3.org/2000/svg" width="1144" height="720" viewBox="0 0 1144 720"><defs><filter id="digitSoft" filterUnits="userSpaceOnUse" x="400" y="180" width="160" height="180"><feGaussianBlur stdDeviation="${n(s.digitBlur||0)}"/></filter><filter id="emberSoft"><feGaussianBlur stdDeviation=".28"/></filter><filter id="cursorShadow"><feGaussianBlur stdDeviation="1.3"/></filter><clipPath id="pill"><rect x="${n(x)}" y="${n(y)}" width="${n(w)}" height="${n(h)}" rx="${n(h/2)}"/></clipPath><clipPath id="digit"><rect x="${n(s.textX+21)}" y="${s.digitBlur>.6||s.digitY<-.2?258.45:263}" width="29" height="${s.digitBlur>.6||s.digitY<-.2?32:27}"/></clipPath><linearGradient id="dayFade"><stop offset="0" stop-color="#000"/><stop offset=".10" stop-color="#fff"/><stop offset=".89" stop-color="#fff"/><stop offset="1" stop-color="#000"/></linearGradient><mask id="days"><rect x="665" y="264" width="145" height="65" fill="url(#dayFade)"/></mask></defs><rect width="1144" height="720" fill="#fdfdfd"/><path d="M.5 719.5V.5H1143.5V719.5Z" fill="none" stroke="#d5d5d5" stroke-width=".65"/>${roundRect(x,y,w,h,h/2,'#000')}`;
 out+=`<g clip-path="url(#pill)">`;
 if(s.flame){const f=s.flame;out+=`<g opacity="${n(f.alpha)}" transform="translate(${n(f.x)} ${n(f.y)}) rotate(${n(f.rotation)}) scale(${n(f.sx)} ${n(f.sy)})">${flameMarkup(false)}</g>`;}
 if(s.inner){const [cx,cy,iw,ih,r,g,b]=s.inner;out+=`<path d="${INNER}" fill="rgb(${Math.round(r)},${Math.round(g)},${Math.round(b)})" opacity="${n(s.innerOpacity??1)}" transform="translate(${n(cx)} ${n(cy)}) scale(${n(iw/18)} ${n(ih/21)}) translate(0 -9)"/>`;}
 for(const p of s.particles){const [px,py,pw,ph,angle,r,g,b,kind]=p,fill=`rgb(${Math.round(r)},${Math.round(g)},${Math.round(b)})`;out+=`<g transform="translate(${n(px)} ${n(py)}) rotate(${n(angle)})">${kind===1?`<path d="${SEED}" fill="${fill}" transform="scale(${n(pw/2)} ${n(ph/2)})"/>`:roundRect(-pw/2,-ph/2,pw,ph,Math.min(pw,ph)*.33,fill)}</g>`;}
 if(s.ember){const e=s.ember;out+=`<path d="${projectSeed(e.pose)}" opacity="${n(s.emberOpacity??1)}" filter="url(#emberSoft)" fill="rgb(${e.rgb.map(Math.round).join(',')})"/>`;}
 for(const [v,path]of[[s.seed,SEED],[s.star,STAR]])if(v)out+=`<path d="${path}" fill="white" opacity="${n(v[4])}" transform="translate(${n(v[0])} ${n(v[1])}) rotate(${n(v[5]||0)}) scale(${n(v[2]/2)} ${n(v[3]/2)})"/>`;
 const digits=String(s.number).padStart(2,'0'),scale=33.5/DIGIT_UNITS;out+=`<g opacity="${n(s.alpha)}"><path d="${DIGITS[digits[0]]}" fill="#f8f8f8" transform="translate(${n(s.textX+1)} 288) scale(${scale} ${-scale})"/><g clip-path="url(#digit)"><g ${s.digitBlur>.01?'filter="url(#digitSoft)"':''}><path d="${DIGITS[digits[1]]}" fill="#f8f8f8" transform="translate(${n(s.textX+23)} ${n(288+s.digitY)}) scale(${scale} ${-scale})"/></g></g><text x="${n(s.textX+1)}" y="320.5" fill="#6a6a6a" font-family="Arial,Helvetica,sans-serif" font-size="18.25">Day Streak</text></g>`;
 const names=['W','T','F','S','S','M','T'],off=s.dayOffset||0;out+=`<g font-family="Arial,Helvetica,sans-serif" font-size="19" text-anchor="middle" opacity="${n(s.alpha)}">`;for(let k=0;k<5;k++){let cx=683.15+off+k*35.9-(k===0?0:s.shift*35.9),op=k===0?1-s.shift:k===4?s.shift:1,col=k<2?238:k===2?mix(137,238,s.shift):137;out+=`<text x="${n(cx)}" y="284.5" opacity="${n(op)}" fill="rgb(${n(col)},${n(col)},${n(col)})">${names[(s.step+k)%names.length]}</text>`;if(k>=2)out+=`<circle cx="${n(cx)}" cy="308.2" r="7.1" opacity="${n(op)}" fill="none" stroke="#626262" stroke-width="1.8" stroke-dasharray="2.2 3.4"/>`;}
 out+='</g>';
 for(let di=0;di<s.dots.length;di++){const d=s.dots[di];if(di===0&&d[5])out+='<g mask="url(#days)">';if(di===0&&d[5])out+=`<defs><filter id="dot${n(d[0]).toString().replace('.','_')}" x="-100%" y="-100%" width="300%" height="300%"><feGaussianBlur stdDeviation="${n(d[5])}"/></filter></defs>`;if(d[4]===2){const pts=Array.from({length:32},(_,j)=>{const a=j*Math.PI/16,r=d[2]*(1+.065*Math.cos(a*8));return [d[0]+r*Math.cos(a),d[1]+r*Math.sin(a)];});out+=`<path d="${pts.map((p,j)=>(j?'L':'M')+n(p[0])+' '+n(p[1])).join('')}Z" fill="white" opacity="${n(d[3])}"/>`;}else out+=d[4]===1?`<path d="${STAR}" fill="white" opacity="${n(d[3])}" transform="translate(${n(d[0])} ${n(d[1])}) scale(${n(d[2]*1.25)})"/>`:`<circle cx="${n(d[0])}" cy="${n(d[1])}" r="${n(d[2])}" fill="white" opacity="${n(d[3])}" ${di===0&&d[5]?`filter="url(#dot${n(d[0]).toString().replace('.','_')})"`:""}/>`;if(di===0&&d[5])out+='</g>';if(di===2&&d[5])out+=`<circle cx="${n(d[0])}" cy="${n(d[1])}" r="7.1" fill="none" stroke="rgb(${d[5]},${d[5]},${d[5]})" stroke-width="1.8" stroke-dasharray="2.2 3.4"/>`;}out+='</g>';
 for(let i=0;i<3;i++){const cx=[503,581,658][i],f=Math.round(s.buttonFill[i]),bs=s.buttonScale?.[i]??1;out+=`<g transform="translate(${cx+.25} 532) scale(${n(bs)}) translate(${-cx} -532)">`;out+=`<circle cx="${cx}" cy="532" r="30.5" fill="rgb(${f},${f},${f})" stroke="#bebebe" stroke-width="1.25"/>`;if(i===0)out+='<path d="M503 522V542M493 532H513" fill="none" stroke="#222" stroke-width="2.3" stroke-linecap="round"/>';if(i===1)out+='<path d="M581 522L577 526L582 530M577 526C585 523 590 530 588 535C585 544 574 540 574 533" fill="none" stroke="#333" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"/>';if(i===2)out+='<path d="M650 539V526Q650 523 653 523Q656 523 656 526V539Q656 542 659 542Q662 542 662 539V524M647 538L650 542L653 538M659 526L662 522L665 526" fill="none" stroke="#a5a5a8" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round"/>';out+='</g>';}
 if(s.tooltip){const [kind,tx,ty,tw,th,op]=s.tooltip,text=kind===2?'Switch animation':'Add streak',font=TOOLTIP_TYPE[text],scale=15.5/DIGIT_UNITS;out+=`<g data-label="${text}" opacity="${n(op)}">${roundRect(tx,ty,tw,th,9.5,'#1c1c1c')}<path d="${font.path}" fill="#c0c0c0" transform="translate(${n(tx+tw/2-font.width*scale/2-.5)} ${n(ty+30)}) scale(${scale} ${-scale})"/></g>`;}

 return out+cursor(s.cursor)+'</svg>';
}

export function reduce(state,a){
 if(a.type==='reset')return {mode:'demo',time:0,count:7,expanded:false,variant:0,age:0,rollAge:2,transition:null,hover:-1,pressed:-1,epoch:0};
 if(a.type==='tick'){const dt=Number.isFinite(a.dt)?clamp(a.dt,0,.1):0;if(state.mode==='demo')return {...state,time:(state.time+dt)%DURATION};return {...state,age:state.age+dt,rollAge:state.rollAge+dt,transition:state.transition?{...state.transition,age:state.transition.age+dt}:null};}
 if(a.type==='release')return {...state,pressed:-1};
 if(a.type==='press'){const current=drawState(state);return {...state,mode:'live',count:state.mode==='demo'?current.number:state.count,expanded:state.mode==='demo'?current.pill[2]>300:state.expanded,age:state.mode==='demo'?3:state.age,rollAge:state.mode==='demo'?2:state.rollAge,pressed:a.index};}
 if(a.type==='hover'){if(state.mode==='demo'&&a.index>=0){const current=drawState(state);return {...state,mode:'live',count:current.number,expanded:current.pill[2]>300,age:3,rollAge:2,transition:null,hover:a.index};}return {...state,hover:a.index};}
 if(a.type==='motion'&&a.reduced){if(state.mode==='demo')return {...state,time:0};return {...state,age:3,rollAge:2,transition:null};}
 if(['toggle','add','replay','switch'].includes(a.type)){
  const current=drawState(state),s=state.mode==='demo'?{...state,mode:'live',count:current.number,expanded:current.pill[2]>300,age:3,rollAge:2}:state;
  if(a.type==='toggle'){const target=!s.expanded;return {...s,expanded:target,transition:a.reduced?null:{from:current.pill,fromAlpha:current.alpha,to:target,age:0},age:a.reduced?3:s.age,epoch:s.epoch+1};}
  if(a.type==='add')return {...s,count:Math.min(99,s.count+1),expanded:true,age:a.reduced?3:0,rollAge:a.reduced?2:0,transition:s.expanded?null:a.reduced?null:{from:current.pill,fromAlpha:current.alpha,to:true,age:0},epoch:s.epoch+1};
  return {...s,variant:a.type==='switch'?1-s.variant:s.variant,age:a.reduced?3:0,epoch:s.epoch+1};
 }
 return state;
}
export function drawState(state){if(state.mode==='demo')return demoState(state.time);const start=state.variant===0?75:194,end=state.variant===0?170:300,idx=Math.min(end,start+state.age*60),s=nativeState(idx/60);s.cursor=[0,0,0,0];s.number=state.count;s.step=((state.count-7)%7+7)%7;s.shift=0;s.digitY=0;s.digitBlur=0;const closed=CONTROLS[0].pill,open=CONTROLS[170].pill,target=state.expanded?open:closed;let alpha=state.expanded?1:0,pill=clone(target);
 if(state.transition){const tr=state.transition,t=tr.age;let pose,p;if(tr.to){pose=nativeState((40+Math.min(50,t*60))/60);p=(pose.pill[2]-closed[2])/(open[2]-closed[2]);alpha=mix(tr.fromAlpha,1,clamp(t/.38));}else{pose=nativeState((626+Math.min(55,t*60))/60);p=(open[2]-pose.pill[2])/(open[2]-closed[2]);alpha=tr.fromAlpha*(1-clamp(t/.28));}if(t===0)p=0;if(t>=.85)p=1;pill=tr.from.map((v,i)=>mix(v,target[i],p));}
 s.pill=pill;s.alpha=alpha;s.innerOpacity=alpha;s.emberOpacity=alpha;s.textX=pill[0]+132;s.dayOffset=Math.max(pill[0]+pill[2]-837.675,pill[0]+240.6-683.15);const offset=s.dayOffset;s.dots=[[683.15+offset,308.2,8.5,alpha,0],[718.97+offset,308.2,8.5,alpha,0]];if(s.flame)s.flame.alpha*=alpha;for(const key of ['seed','star'])if(s[key])s[key][4]*=alpha;s.particles=s.particles.map(p=>p.map((v,i)=>i>=5&&i<=7?v*alpha:v));if(!alpha){s.seed=s.star=s.ember=s.inner=null;s.particles=[];}
 if(state.rollAge<.56){const roll=nativeState((85+state.rollAge*60)/60);s.step=((state.count-8)%7+7)%7;s.shift=roll.shift;s.digitY=roll.digitY;s.digitBlur=roll.digitBlur;s.dots=roll.dots.map(d=>[d[0]+offset,d[1],d[2],d[3]*alpha,d[4]]);}
 s.buttonFill=[253,253,253];s.buttonScale=[1,1,1];if(state.pressed>=0){s.buttonScale[state.pressed]=.9;s.buttonFill[state.pressed]=242;}s.tooltip=null;if(state.hover===0||state.hover===2){const k=state.hover,cx=k===0?503:658,w=k===0?104:149;s.buttonFill[k]=242;s.tooltip=[k,cx-w/2,584,w,50,1];}return s;
}
