// Entirely fictional documents. No content or identifiers from the reference image.
export const documents = {
  resume: {
    id: 'resume', title: 'Alex Morgan · Portfolio.pdf', short: 'Portfolio', type: 'pdf', width: 816, height: 1056, pages: 2,
    subtitle: 'Two-page portfolio',
    lines: [
      ['name', 'Alex Morgan'], ['role', 'PRODUCT DESIGNER'],
      ['contact', 'alex@example.com   /   Brooklyn, NY   /   alex.example.com'],
      ['summary', 'Thoughtful digital experiences, made clear.'],
      ['body', 'I turn complex workflows into useful, considered products.'],
      ['body', 'My practice connects research, interaction design, and systems thinking.'],
      ['section', 'EXPERIENCE'],
      ['job', 'Northstar Studio'], ['meta', 'Senior Product Designer                                      2023 — Present'],
      ['body', 'Designed a shared workspace for teams to read, discuss, and decide.'],
      ['bullet', 'Led the reader experience from first sketch through launch.'],
      ['bullet', 'Built a coherent navigation system across documents and conversations.'],
      ['bullet', 'Partnered with engineering on fluid, interruptible interactions.'],
      ['job', 'Outline Works'], ['meta', 'Product Designer                                              2020 — 2023'],
      ['body', 'Helped small teams bring ambitious ideas into the world.'],
      ['bullet', 'Shipped a calmer project space with a clearer information hierarchy.'],
      ['bullet', 'Created reusable patterns for complex, document-heavy workflows.'],
      ['section', 'SELECTED WORK'],
      ['job', 'A little more room to think'],
      ['body', 'A document workspace that keeps the conversation close to the work.'],
      ['body', 'Research · Interaction design · Design systems'],
      ['job', 'Every detail, connected'],
      ['body', 'A flexible library for people who collect, connect, and create.'],
      ['body', 'Product strategy · Prototyping · Front-end collaboration'],
      ['section', 'EDUCATION'], ['job', 'School of Visual Studies'],
      ['body', 'BFA, Communication Design                                       2016 — 2020'],
    ],
    pageTwo: [
      ['name', 'Selected projects'], ['role', 'ALEX MORGAN'],
      ['summary', 'From a small interaction to the whole experience.'],
      ['section', '01 / THE READING ROOM'],
      ['body', 'One quiet place for the document and the conversation around it.'],
      ['body', 'A persistent shell lets people move between files without losing context.'],
      ['bullet', 'Tabs preserve each document’s position and magnification.'],
      ['bullet', 'A floating composer keeps the next question within reach.'],
      ['bullet', 'The interface gets out of the way when the work needs more space.'],
      ['section', '02 / SMALL MOMENTS'],
      ['body', 'Transitions connect states, rather than calling attention to themselves.'],
      ['body', 'Responsive motion gives feedback while respecting reduced-motion settings.'],
      ['section', 'TOOLS & PRACTICE'],
      ['body', 'Prototyping, accessible interaction design, and design systems.'],
      ['body', 'A little patience. A lot of curiosity.'],
    ],
  },
  notes: {
    id: 'notes', title: 'A quieter workspace.md', short: 'Workspace notes', type: 'markdown', width: 816, height: 1056, pages: 1,
    subtitle: 'Reading notes',
    lines: [
      ['eyebrow', 'FIELD NOTES / OCTOBER'], ['name', 'A quieter workspace'],
      ['summary', 'Make room for the work. Keep the conversation close.'],
      ['body', 'A good workspace makes its structure easy to understand.'],
      ['body', 'You always know where you are, what is open, and what happens next.'],
      ['section', 'THE SHELL'],
      ['body', 'The narrow rail handles broad navigation. The sidebar holds context.'],
      ['body', 'Tabs sit above the document so switching feels like moving between rooms.'],
      ['quote', 'The document should stay still while the interface moves around it.'],
      ['section', 'READING & ZOOM'],
      ['body', 'Keep each file’s scroll position and zoom level when changing tabs.'],
      ['body', 'Anchor zoom to the pointer so a detail stays where you are looking.'],
      ['bullet', 'Scroll to read. Pinch or Control-scroll to zoom.'],
      ['bullet', 'Fit width adapts when the sidebar folds away.'],
      ['bullet', 'Escape dismisses a menu before it changes anything else.'],
      ['section', 'THE NEXT QUESTION'],
      ['body', 'A floating composer is available without replacing the document.'],
      ['body', 'Keep questions with their file, and let the reader return to a quiet page.'],
      ['quote', 'Calm is a consequence of clear structure.'],
    ],
  },
};
export const fileIds = Object.keys(documents);
