(function(root,factory){const value=typeof module==='object'?factory(require('./curve.js'),require('./motion-data.js')):factory(root.GraphCurve,root.GraphData);if(typeof module==='object')module.exports=value;else root.GraphScene=value;})(globalThis,function(Curve,Data){
  'use strict';
  const W=1340,H=836,DURATION=9.2;
  const clamp=x=>Math.max(0,Math.min(1,x));
  function format(minute){return `${Math.floor(minute/60)}:${String(minute%60).padStart(2,'0')} AM`;}
  function observed(time){const t=((time%DURATION)+DURATION)%DURATION;let lo=0,hi=Data.frames.length;while(lo+1<hi){const m=(lo+hi)>>1;if(Data.frames[m].pts<=t+.0000005)lo=m;else hi=m;}return{...Data.frames[lo],index:lo,time:t};}
  function live(progress){const p=clamp(progress),point=Curve.at(p),minute=455+Math.round(p*60);return{markerX:point.x-.5,markerY:point.y-1,guideX:point.x-.5,clipX:p===0?306:p===1?1034:point.x+2.5,minute,label:format(minute),cursor:null,live:true};}
  function pointer(p){if(!p)return'';return`<path transform="translate(${p.x},${p.y+1}) scale(.916666667,1)" d="M1 1V28L8 22L13 34L18 32L13 21H22Z" fill="#0a0a0a" stroke="#fafafa" stroke-width="2" stroke-linejoin="miter"/>`;}
  function render(input){const s=typeof input==='number'?observed(input):input,label=s.label||format(s.minute),metric=Data.labels[label],width=metric?.width||125,cx=s.guideX,ink=metric?.inkWidth||90,clip=Math.max(306,Math.min(1034,s.clipX??cx+3));return`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><defs><linearGradient id="grayArea" gradientUnits="userSpaceOnUse" x1="0" y1="302" x2="0" y2="624"><stop stop-color="#272727"/><stop offset="1" stop-color="#141414"/></linearGradient><linearGradient id="blueArea" gradientUnits="userSpaceOnUse" x1="0" y1="302" x2="0" y2="624"><stop stop-color="#0e284c"/><stop offset=".149" stop-color="#122745"/><stop offset=".304" stop-color="#16263e"/><stop offset=".46" stop-color="#172237"/><stop offset=".615" stop-color="#171f2d"/><stop offset=".770" stop-color="#171b23"/><stop offset=".925" stop-color="#171619"/><stop offset="1" stop-color="#141414"/></linearGradient><clipPath id="blueClip"><rect x="300" y="270" width="${clip-300}" height="355"/></clipPath></defs><rect width="${W}" height="${H}" fill="#141414"/><path d="${Curve.path}H1033.5V624H306V573.5Z" fill="url(#grayArea)"/><path d="${Curve.path}" fill="none" stroke="#454545" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><g clip-path="url(#blueClip)"><path d="${Curve.path}H1033.5V624H306V573.5Z" fill="url(#blueArea)"/><path d="${Curve.path}" fill="none" stroke="#008dff" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/></g><path d="M${cx} 247V623" stroke="white" stroke-opacity=".09" stroke-width="4" stroke-linecap="round"/><rect x="${cx-width/2}" y="199" width="${width}" height="48" rx="24" fill="#272727"/><text x="0" y="0" transform="translate(${cx+(metric?.dx??-45)},${metric?.dy??231}) scale(${metric?.sx??1},${metric?.sy??1})" font-family="Inter,Arial,sans-serif" font-size="24" font-weight="400" fill="#e2e2e2">${label}</text><circle cx="${s.markerX}" cy="${s.markerY}" r="16" fill="#0083ff" stroke="#fafafa" stroke-width="4"/>${pointer(s.cursor)}</svg>`;}
  return{W,H,DURATION,observed,live,render,format};
});
