(function(root){'use strict';const copy=p=>p.map(x=>x.slice());
function create(pose){return {hub:pose.hub.slice(),velocity:[0,0],drag:null,pointer:null,anchors:copy(pose.anchors||pose.tips),ropes:pose.paths.map(p=>({p:copy(p),old:copy(p),lengths:p.slice(1).map((v,i)=>Math.hypot(v[0]-p[i][0],v[1]-p[i][1])),anchor:p.at(-1).slice()}))};}
function hit(s,p){let best={kind:'hub',distance:Math.hypot(p[0]-s.hub[0],p[1]-s.hub[1])};for(let k=0;k<3;k++){const q=s.ropes[k].p.at(-1),d=Math.hypot(q[0]-p[0],q[1]-p[1]);if(d<best.distance)best={kind:'tip',rope:k,distance:d};}if(best.distance<34)return best;best={distance:28};for(let k=0;k<3;k++)for(let i=1;i<s.ropes[k].p.length-1;i++){const q=s.ropes[k].p[i],d=Math.hypot(q[0]-p[0],q[1]-p[1]);if(d<best.distance)best={kind:'strand',rope:k,node:i,distance:d};}return best.kind?best:null;}
function grab(s,p){s.drag=hit(s,p);s.pointer=p.slice();if(s.drag?.kind==='tip')s.ropes[s.drag.rope].anchor=null;return s.drag;}
function move(s,p){s.pointer=p.slice();}
function release(s){if(s.drag?.kind==='tip'){const r=s.ropes[s.drag.rope],tip=r.p.at(-1);let near=null,d=46;for(const q of s.anchors){const v=Math.hypot(q[0]-tip[0],q[1]-tip[1]);if(v<d){near=q.slice();d=v;}}r.anchor=near;}s.drag=null;}
function step(s,dt=1/60){const scale=Math.max(0,Math.min(2,dt*60));if(s.drag?.kind==='hub'){s.hub=s.pointer.slice();s.velocity=[0,0];}else for(let j=0;j<2;j++){const home=j?538.5:863;s.velocity[j]=(s.velocity[j]+(home-s.hub[j])*.095*scale)*Math.pow(.78,scale);s.hub[j]+=s.velocity[j]*scale;}
for(let k=0;k<3;k++){const r=s.ropes[k],p=r.p,n=p.length;for(let i=1;i<n;i++){if(i===n-1&&r.anchor)continue;const [x,y]=p[i];p[i]=[x+(x-r.old[i][0])*Math.pow(.975,scale),y+(y-r.old[i][1])*Math.pow(.975,scale)+.26*scale*scale];r.old[i]=[x,y];}
for(let iter=0;iter<14;iter++){p[0]=s.hub.slice();if(r.anchor)p[n-1]=r.anchor.slice();if(s.drag?.rope===k)p[s.drag.kind==='tip'?n-1:s.drag.node]=s.pointer.slice();for(let i=0;i<n-1;i++){const a=p[i],b=p[i+1],dx=b[0]-a[0],dy=b[1]-a[1],d=Math.max(.001,Math.hypot(dx,dy)),q=(d-r.lengths[i])/d*.5;const fixed=j=>j===0||(j===n-1&&r.anchor)||(s.drag?.rope===k&&j===(s.drag.kind==='tip'?n-1:s.drag.node)),fa=fixed(i),fb=fixed(i+1);if(!fa){a[0]+=dx*q*(fb?2:1);a[1]+=dy*q*(fb?2:1);}if(!fb){b[0]-=dx*q*(fa?2:1);b[1]-=dy*q*(fa?2:1);}}}
p[0]=s.hub.slice();if(r.anchor)p[n-1]=r.anchor.slice();for(let i=1;i<n;i++){p[i][0]=Math.max(420,Math.min(1470,p[i][0]));p[i][1]=Math.max(145,Math.min(1000,p[i][1]));}}
return pose(s);}
function pose(s){return {hub:s.hub.slice(),paths:s.ropes.map(r=>copy(r.p)),tips:s.ropes.map(r=>r.p.at(-1).slice())};}const api={create,grab,move,release,step,pose,hit};if(typeof module!=='undefined')module.exports=api;else root.ClockPhysics=api;
})(globalThis);
