(function(root){'use strict';
const D=typeof module!=='undefined'?require('./motion-data'):root.ClockMotion,S=typeof module!=='undefined'?require('./scene'):root.ClockScene,frames=D.frames,duration=20,sourceDuration=17.066667;
const lerp=(a,b,u)=>a+(b-a)*u,dist=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
function resample(points,n=49){const d=[0];for(let i=1;i<points.length;i++)d.push(d.at(-1)+dist(points[i-1],points[i]));if(!d.at(-1))return Array.from({length:n},()=>points[0].slice());let j=1;return Array.from({length:n},(_,i)=>{const q=d.at(-1)*i/(n-1);while(j<d.length-1&&d[j]<q)j++;const u=(q-d[j-1])/(d[j]-d[j-1]||1);return [0,1].map(k=>lerp(points[j-1][k],points[j][k],u));});}
function route(paths,start,end){const nodes=[],adj=[],ends=[];function add(p){nodes.push(p);adj.push([]);return nodes.length-1;}function link(a,b){const w=dist(nodes[a],nodes[b]);adj[a].push([b,w]);adj[b].push([a,w]);}for(const p of paths){const first=nodes.length;for(let i=0;i<p.length;i++){const q=add(p[i]);if(i)link(q-1,q);}if(p.length){ends.push(first,nodes.length-1);}}if(!nodes.length)return resample([start,end]);for(let i=0;i<ends.length;i++)for(let j=i+1;j<ends.length;j++)if(dist(nodes[ends[i]],nodes[ends[j]])<9)link(ends[i],ends[j]);const closest=p=>nodes.reduce((best,q,i)=>dist(q,p)<dist(nodes[best],p)?i:best,0),a=closest(start),b=closest(end),cost=nodes.map(()=>Infinity),prev=nodes.map(()=>-1),used=new Set();cost[a]=0;for(let pass=0;pass<nodes.length;pass++){let v=-1;for(let i=0;i<nodes.length;i++)if(!used.has(i)&&(v<0||cost[i]<cost[v]))v=i;if(v<0||!Number.isFinite(cost[v]))break;if(v===b)break;used.add(v);for(const [j,w] of adj[v])if(cost[v]+w<cost[j]){cost[j]=cost[v]+w;prev[j]=v;}}if(!Number.isFinite(cost[b]))return resample([start,end]);const points=[];let k=b;while(k>=0){points.push(nodes[k]);if(k===a)break;k=prev[k];}points.reverse();return resample([start,...points,end]);}
function toPhysics(p){const n=p.network;if(!n)return {hub:p.hub.slice(),paths:p.paths.map(a=>a.map(v=>v.slice())),tips:p.tips.map(a=>a.slice())};const tips=[n.blackTips[0]||n.targets[0],n.blackTips[1]||n.targets[1],n.redTip];return {hub:n.hub.slice(),tips,anchors:n.targets,paths:[route(n.physicsBlack||n.black,n.hub,tips[0]),route(n.physicsBlack||n.black,n.hub,tips[1]),route(n.red,n.hub,tips[2])]};}
function pose(d){return {hub:d.hub,network:d,tips:[...d.blackTips,d.redTip],targets:d.targets,cursor:d.cursor,cursorBlur:d.cursorBlur||0,cursorScale:d.cursorScale,cursorVector:d.cursorVector,closed:d.closed||false,f:d.f};}
let initialPhysics,lastPhysics;
function at(t){t=((t%duration)+duration)%duration;if(t<=17.7){let lo=0,hi=frames.length-1;while(lo<hi){const m=Math.ceil((lo+hi)/2);if(frames[m].t<=t+1e-6)lo=m;else hi=m-1;}return pose(frames[lo]);}if(t>=19.4)return pose(frames[0]);initialPhysics??=toPhysics(pose(frames[0]));lastPhysics??=toPhysics(pose(frames.at(-1)));const q=(t-17.7)/1.7,u=q*q*(3-2*q),mixp=(a,b)=>a.map((v,i)=>lerp(v,b[i],u));return {hub:mixp(lastPhysics.hub,initialPhysics.hub),tips:lastPhysics.tips.map((v,i)=>mixp(v,initialPhysics.tips[i])),paths:lastPhysics.paths.map((p,k)=>p.map((v,i)=>mixp(v,initialPhysics.paths[k][i]))),targets:frames.at(-1).targets.map((v,i)=>mixp(v,frames[0].targets[i])),cursor:mixp(frames.at(-1).cursor,frames[0].cursor),cursorScale:lerp(frames.at(-1).cursorScale||.9,frames[0].cursorScale||.9,u),cursorVector:frames[0].cursor.map((v,k)=>(v-frames.at(-1).cursor[k])*6*q*(1-q)/1.7/60*.9),closed:false,cursorBlur:0,f:null};}
const baseAt=at;function cursorAt(t){const s=baseAt(t),f=s.f;if(f!==null&&f!==undefined){const a=frames[Math.max(0,f-1)].cursor,b=frames[Math.min(frames.length-1,f+1)].cursor;s.cursorVelocity=[b[0]-a[0],b[1]-a[1]];}return s;}const api={at:cursorAt,toPhysics,route,resample,frames,duration,sourceDuration};if(typeof module!=='undefined')module.exports=api;else root.ClockTimeline=api;
})(globalThis);
