import test from 'node:test';import assert from 'node:assert/strict';
test('DOM-stub date drag, cancellation, keyboard, state buttons and local PDF download',async()=>{
 const all=[];let frame,downloaded=false,blobCount=0;
 const element=()=>{const e={events:{},attrs:{},style:{},dataset:{},children:[],hidden:false,capture:null,innerHTML:'',textContent:'',setAttribute(k,v){this.attrs[k]=v;},addEventListener(k,f){this.events[k]=f;},append(x){this.children.push(x);},remove(){},click(){downloaded=true;},setPointerCapture(id){this.capture=id;},hasPointerCapture(id){return this.capture===id;},releasePointerCapture(){this.capture=null;},getBoundingClientRect(){return {width:1080};}};all.push(e);return e;};
 const ids=Object.fromEntries(['art','editor','confirmation','finished','statuses','colors','mark','undo','done','download','next','announcement','replay'].map(k=>[k,element()]));
 const wheels=['day','month','year'].map(field=>{const e=element();e.dataset.field=field;return e;}),body=element(),stage=element(),events={},motion={matches:true,addEventListener(k,f){this.change=f;}};
 globalThis.document={body,getElementById:k=>ids[k],createElement:()=>element(),querySelector:()=>stage,querySelectorAll:q=>q==='[data-field]'?wheels:q==='[data-status]'?ids.statuses.children:ids.colors.children,addEventListener(k,f){events[k]=f;}};
 globalThis.matchMedia=()=>motion;globalThis.requestAnimationFrame=f=>{frame=f;};const oldCreate=URL.createObjectURL,oldRevoke=URL.revokeObjectURL;URL.createObjectURL=()=>{blobCount++;return 'blob:local-test';};URL.revokeObjectURL=()=>{};
 try{await import('../src/main.mjs');assert.equal(ids.editor.hidden,false);wheels[0].events.keydown({key:'ArrowUp',preventDefault(){}});assert.equal(wheels[0].attrs['aria-valuenow'],'14');wheels[0].events.pointerdown({pointerId:2,clientY:400});assert.equal(wheels[0].capture,2);wheels[0].events.pointermove({pointerId:2,clientY:362});wheels[0].events.pointercancel({pointerId:2});assert.equal(wheels[0].capture,null);assert.equal(wheels[0].attrs['aria-valuenow'],'15');ids.colors.children[2].events.click();assert.equal(ids.colors.children[2].attrs['aria-pressed'],'true');ids.mark.events.click();assert.equal(ids.confirmation.hidden,false);ids.done.events.click();assert.equal(ids.finished.hidden,false);ids.download.events.click();assert(downloaded&&blobCount===1);ids.next.events.click();assert.equal(ids.editor.hidden,false);events.keydown({key:'Escape'});assert.equal(wheels[0].attrs['aria-valuenow'],'13');const before=ids.art.innerHTML;frame(0);frame(100);assert.equal(ids.art.innerHTML,before);}
 finally{URL.createObjectURL=oldCreate;URL.revokeObjectURL=oldRevoke;}
});
