(function(root,factory){const v=typeof module==='object'?factory(require('./motion-data.js'),require('./model.js'),require('./type-fit.js')):factory(root.TagMotionData,root.TagModel,root.TagTypeFit);if(typeof module==='object')module.exports=v;else root.TagScene=v;})(typeof globalThis==='object'?globalThis:this,function(DATA,MODEL,TYPE){
  'use strict';
  const W=1200,H=1248,DURATION=23.035;
  const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
  const ease=x=>1-Math.pow(1-clamp(x),3);
  const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function frameAt(t){let lo=0,hi=DATA.pts.length;while(lo+1<hi){const m=(lo+hi)>>1;if(DATA.pts[m]<=t+0.0000005)lo=m;else hi=m;}return lo;}
  function selectedAt(f){let s=['H','M'];for(const e of DATA.events){if(f<e.frame)break;s=e.selected;}return [...s];}
  function observed(t){const time=((t%DURATION)+DURATION)%DURATION,f=frameAt(time);let query='';for(const [i,q]of DATA.queries)if(f>=i)query=q;const mode=f>=175&&f<353?'create':'list';if(f>=353)query='';const created=f>=353;const labels=MODEL.BASE.map(a=>({id:a[0],name:a[1],color:a[2],width:a[3]}));if(created)labels.splice(2,0,{id:'D',name:'design',color:'#e11483',width:154});let color=0;for(const [i,c]of DATA.colors)if(f>=i)color=c;const row={time,f,labels,selected:selectedAt(f),open:f>=59&&f<970,mode,query,draft:'design',created,color,colorQuery:'',live:false};if(time>=22.035){row.tail=clamp((time-22.2)/.55);if(row.tail>.5){row.selected=['H','M'];row.created=false;row.labels=labels.filter(x=>x.id!=='D');}}return row;}
  function layout(selected,labels){const list=labels.filter(x=>selected.includes(x.id));const width=list.reduce((v,x)=>v+x.width,0)+Math.max(0,list.length-1)*12+(list.length?26:0)+144;let x=622-width/2;const chips=list.map(item=>{const r={...item,x,y:460,alpha:1,dy:0,blur:0};x+=item.width+12;return r;});return{chips,buttonX:list.length?x+14:x};}
  function topLayout(row){const fresh=layout(row.selected,row.labels);if(row.live)return fresh;if(row.tail!==undefined){const a=layout(['A'],row.labels),b=layout(['H','M'],row.labels);return{chips:[...a.chips.map(c=>({...c,alpha:1-row.tail})),...b.chips.map(c=>({...c,alpha:row.tail}))],buttonX:a.buttonX+(b.buttonX-a.buttonX)*row.tail};}const f=row.f,t=row.time;let prev=['H','M'],event=null;for(const e of DATA.events){if(f<e.frame)break;event={...e,previous:prev};prev=e.selected;}if(event){const age=t-DATA.pts[event.frame];if(age<.38){const adding=event.selected.length>event.previous.length,ink=ease(age/(adding?.19:.12)),shift=adding?1:ease((age-.12)/.2);const old=layout(event.previous,row.labels),next=fresh;const ids=[...new Set([...old.chips.map(x=>x.id),...next.chips.map(x=>x.id)])];fresh.chips=ids.map(id=>{const a=old.chips.find(x=>x.id===id),b=next.chips.find(x=>x.id===id),z={...(b||a)};z.x=a&&b?a.x+(b.x-a.x)*shift:(b||a).x;z.alpha=a&&b?1:b?ink:1-ink;z.dy=b&&!a?(1-ink)*5:0;z.blur=a&&b?0:(b?1-ink:ink)*2;return z;});fresh.buttonX=old.buttonX+(next.buttonX-old.buttonX)*shift;}}if(DATA.tracks?.[f]?.chips)fresh.chips=DATA.tracks[f].chips;if(DATA.tracks?.[f]?.buttonX!==undefined)fresh.buttonX=DATA.tracks[f].buttonX;return fresh;}
  const text=(x,y,value,size=26,weight=400,fill='#111',extra='')=>{const f=TYPE[weight+':'+value];return f?`<text x="0" y="0" transform="translate(${x+f.dx},${y+f.dy}) scale(${f.sx},${f.sy})" font-size="${size}" font-weight="${weight}" fill="${fill}" ${extra}>${esc(value)}</text>`:`<text x="${x}" y="${y}" font-size="${size}" font-weight="${weight}" fill="${fill}" ${extra}>${esc(value)}</text>`;};
  const tagIcon=(x,y)=>`<path d="M${x-6} ${y-8}h12q2 0 3 2l6 6-6 6q-1 2-3 2h-12q-3 0-3-3v-10q0-3 3-3Z" fill="none" stroke="#858585" stroke-width="1.8" stroke-linejoin="round"/><circle cx="${x-4}" cy="${y}" r="1.5" fill="#858585"/>`;
  function chip(c){return`<g opacity="${c.alpha}" transform="translate(${c.x},${460+c.dy})" ${c.blur>.05?`filter="url(#chipBlur${c.id})"`:''}><rect x=".5" y=".5" width="${c.width-1}" height="53" rx="26.5" fill="white" stroke="#ddd" filter="url(#chipShadow)"/><circle cx="31" cy="27" r="10" fill="${c.color}"/>${text(53,36,c.name,26,500)}</g>`;}
  function check(x,y,amount,hover=0){return `<rect x="${x}" y="${y-16}" width="32" height="32" rx="10" fill="none" stroke="#dcdcdc" stroke-width="1.2" opacity="${hover*(1-amount)}"/><g opacity="${amount}"><rect x="${x}" y="${y-16}" width="32" height="32" rx="10" fill="#191919"/><path d="M${x+8} ${y}l5 5 11-12" stroke="white" stroke-width="2.6" fill="none" stroke-linecap="round" stroke-linejoin="round"/></g>`;}
  function pointer(row){const p=!row.suppressPointer&&!row.live&&row.tail===undefined?DATA.tracks?.[row.f]?.pointer:null;if(!p)return '';const [x,y]=p.bounds;let shape='';if(p.kind==='hand')shape='<path d="M8.7 17.7V3.3C8.7 .4 13.7 .4 13.7 3.3V15.4C13.7 12.1 18.2 12.1 18.2 15.4V17C18.2 13.7 22.4 14.1 22.4 17.3V19C22.4 15.9 26.5 16.6 26.5 20V25.6C26.5 33 22.5 36 15.7 36C9.7 36 6.5 31.7 4.3 27L1.2 20.6C.1 17.5 4.6 15.6 6.1 19L8.7 23Z" fill="white" stroke="#080808" stroke-width="1.9" stroke-linejoin="round" filter="url(#pointerShadow)"/>';
    else if(p.kind==='ibeam'){const d='M1 1C5 1 6 3 6 5V28C6 31 3 32 1 32M11 1C7 1 6 3 6 5M6 28C6 31 9 32 11 32';shape=`<path d="${d}" fill="none" stroke="white" stroke-width="3.2"/><path d="${d}" fill="none" stroke="#111" stroke-width="1.4"/>`;}
    else {const d='M0 0V25L6.4 20.2L11.3 31.5L15.4 29.6L10.6 18.5L18 17.5Z';shape=`<g filter="url(#pointerShadow)"><path d="${d}" fill="black" stroke="white" stroke-width="2.8" stroke-linejoin="round"/><path d="${d}" fill="black"/></g>`;}
    return `<g transform="translate(${x+.5},${y+.5}) ${p.kind==='arrow'?'scale(.94,.90625)':''}">${shape}</g>`;
  }
  function panel(row){if(!row.open)return'';const f=row.f,create=row.mode==='create';const rows=row.labels.filter(x=>x.name.toLowerCase().includes(row.query.toLowerCase()));const canCreate=row.query.trim()&&!row.labels.some(x=>x.name.toLowerCase()===row.query.trim().toLowerCase());const count=rows.length+(canCreate?1:0);let h=create?667:109+68*count;if(!row.live&&f===175)h=661;if(!row.live&&f===176)h=665;if(!row.live&&f===353)h=577;if(!row.live&&f===354)h=575;const ai=!row.live&&f>=59&&f<=69?DATA.openAlpha[f-59]:1;const blur=!row.live&&f>=59&&f<=69?DATA.openBlur[f-59]:0;let out=`<g opacity="${ai}" ${blur>.02?'filter="url(#panelSoft)"':''}><rect x="349.5" y="532.5" width="545" height="${h}" rx="26" fill="${create?(DATA.tracks?.[f]?.outerFill?'rgb('+DATA.tracks[f].outerFill+','+DATA.tracks[f].outerFill+','+DATA.tracks[f].outerFill+')':'#f4f4f4'):(!row.live&&f>=353&&f<=356?['#f8f8f8','#fafafa','#fcfcfc','#fdfdfd'][f-353]:'white')}" stroke="#d0d0d0" filter="url(#panelShadow)"/>`;
    if(create){const ix=f-176;let ca=!row.live&&ix>=0&&ix<14?DATA.createTitle[ix]:[1,0,0],pa=!row.live&&ix>=0&&ix<14?DATA.createPreview[ix]:[1,0,0];if(!row.live&&f===175)ca=pa=[0,0,0];out+=`<g opacity="${ca[0]}" transform="translate(0,${ca[1]})" filter="url(#createTitleSoft)">${tagIcon(393,577)}${text(440,586,'Create',26,400,'#898989')}</g><g opacity="${pa[0]}" transform="translate(0,${pa[1]})" filter="url(#createPreviewSoft)"><rect x="535" y="550" width="154" height="54" rx="27" fill="white" stroke="#ddd"/><circle cx="566" cy="577" r="10" fill="${MODEL.PALETTE[row.color][1]}"/>${text(588,586,row.draft||row.query,26,500)}</g>`;
      const ba=!row.live?clamp((f-175)/4):1;out+=`<g opacity="${ba}" filter="url(#createBodySoft)"><rect x="355.5" y="621.5" width="533" height="572" rx="24" fill="white" stroke="#d8d8d8"/><path d="M356 705.5h532" stroke="#eee"/>${text(384,674,row.colorQuery||'Pick a color',27,400,row.colorQuery?'#111':'#888')}`;const colors=MODEL.PALETTE.map((x,i)=>({name:x[0],color:x[1],index:i})).filter(x=>x.name.toLowerCase().includes((row.colorQuery||'').toLowerCase()));colors.forEach((c,j)=>{const y=751+68*j;const hover=row.live?(row.highlight===j?1:0):(DATA.tracks?.[f]?.hover?.[j]??(c.index===row.color?1:0));out+=`<rect x="368" y="${y-34}" width="486" height="68" rx="12" fill="#f2f2f2" opacity="${hover}"/><circle cx="394" cy="${y}" r="10" fill="${c.color}"/>${text(424,y+10,c.name)}`;});out+='<rect x="872" y="711" width="12" height="407" rx="6" fill="#b5b5b5"/></g>';
    }else{out+=text(378,587,row.query||'Add or find a label...',26,400,row.query?'#111':'#969696')+'<path d="M350 616.5h544" stroke="#eee"/>';rows.forEach((item,j)=>{const y=663+j*68;const hover=row.live?(row.highlight===j?1:0):(DATA.tracks?.[f]?.hover?.[j]??0);out+=`<rect x="362" y="${y-34}" width="${row.created?498:520}" height="68" rx="12" fill="#f2f2f2" opacity="${hover}"/>${check(378,y,row.live?(row.selected.includes(item.id)?1:0):(DATA.tracks?.[f]?.checks?.[j]??(row.selected.includes(item.id)?1:0)),hover)}<circle cx="440" cy="${y}" r="10" fill="${item.color}"/>${text(470,y+10,item.name)}`;});if(canCreate){const y=663+rows.length*68;out+=`<rect x="362" y="${y-34}" width="${row.created?498:520}" height="68" rx="12" fill="#f2f2f2"/><path d="M386 ${y}h16m-8-8v16" stroke="#555" stroke-width="2"/>${text(428,y+9,'Create new label: ')}${text(643,y+9,'“'+row.query+'”',26,400,'#888')}`;}if(row.created)out+='<rect x="877" y="622" width="11" height="470" rx="5.5" fill="#b5b5b5"/>';}
    if(!row.live&&DATA.tracks?.[f]?.caret){const cx=DATA.tracks[f].caret,cy=create?647:555;out+=`<path d="M${cx} ${cy}v34" stroke="#222" stroke-width="1.4"/>`;}return out+'</g>';
  }
  function render(input){const row=typeof input==='number'?observed(input):input,top=topLayout(row),f=row.f||0,ix=f-176;const ca=!row.live&&ix>=0&&ix<14?DATA.createTitle[ix]:[1,0,0],pa=!row.live&&ix>=0&&ix<14?DATA.createPreview[ix]:[1,0,0];const blur=!row.live&&f>=59&&f<=69?DATA.openBlur[f-59]:0;
    return`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1248" viewBox="0 0 1200 1248"><defs><filter id="pointerShadow" x="-40%" y="-30%" width="180%" height="180%"><feDropShadow dx="0" dy="2" stdDeviation="1.5" flood-opacity=".3"/></filter><filter id="chipShadow" x="-20%" y="-30%" width="140%" height="180%"><feDropShadow dx="0" dy="2" stdDeviation="1.5" flood-opacity=".08"/></filter><filter id="panelShadow" x="-20%" y="-20%" width="140%" height="150%"><feGaussianBlur in="SourceAlpha" stdDeviation="3" result="b1"/><feOffset in="b1" dy="2" result="o1"/><feFlood flood-opacity=".1"/><feComposite in2="o1" operator="in" result="s1"/><feGaussianBlur in="SourceAlpha" stdDeviation="10" result="b2"/><feOffset in="b2" dy="12" result="o2"/><feFlood flood-opacity=".025"/><feComposite in2="o2" operator="in" result="s2"/><feMerge><feMergeNode in="s2"/><feMergeNode in="s1"/><feMergeNode in="SourceGraphic"/></feMerge></filter><filter id="panelSoft" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="${blur}"/></filter><filter id="createTitleSoft" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="${ca[2]}"/></filter><filter id="createPreviewSoft" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="${pa[2]}"/></filter><filter id="createBodySoft" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="${!row.live&&f===176?2:!row.live&&f===177?1.6:0}"/></filter>${top.chips.map(c=>`<filter id="chipBlur${c.id}" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="${c.blur}"/></filter>`).join('')}</defs><rect width="1200" height="1248" fill="#fafafa"/><g font-family="Inter,Arial,sans-serif">${top.chips.map(chip).join('')}<rect x="${top.buttonX}" y="456" width="144" height="62" rx="31" fill="${!row.live&&row.tail===undefined?`rgb(${DATA.tracks?.[f]?.buttonFill??242},${DATA.tracks?.[f]?.buttonFill??242},${DATA.tracks?.[f]?.buttonFill??242})`:'#f2f2f2'}"/>${text(top.buttonX+21,497,'+ Label',28,500)}${panel(row)}</g>${pointer(row)}</svg>`;
  }
  function hitboxes(row){const top=topLayout(row),a=top.chips.map(c=>({kind:'toggle',id:c.id,label:'Remove '+c.name,x:c.x,y:460,w:c.width,h:54}));a.push({kind:'open',label:'Add label',x:top.buttonX,y:456,w:144,h:62});if(row.open){if(row.mode==='create'){a.push({kind:'colorQuery',label:'Find a color',x:378,y:635,w:474,h:62});MODEL.PALETTE.map((x,i)=>({name:x[0],index:i})).filter(x=>x.name.toLowerCase().includes((row.colorQuery||'').toLowerCase())).forEach((c,j)=>a.push({kind:'color',id:c.index,label:c.name,x:364,y:718+j*68,w:502,h:65}));}else{a.push({kind:'query',label:'Find or create a label',x:378,y:550,w:488,h:60});const rows=row.labels.filter(x=>x.name.toLowerCase().includes(row.query.toLowerCase()));rows.forEach((x,j)=>a.push({kind:'toggle',id:x.id,label:x.name,selected:row.selected.includes(x.id),x:363,y:630+j*68,w:510,h:65}));if(row.query.trim()&&!row.labels.some(x=>x.name.toLowerCase()===row.query.trim().toLowerCase()))a.push({kind:'create',label:'Create '+row.query,x:363,y:630+rows.length*68,w:510,h:65});}}return a;}
  return{W,H,DURATION,frameAt,observed,layout,render,hitboxes,pointer};
});
