(()=>{'use strict';const scene=document.getElementById('scene'),canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d'),video=document.getElementById('film'),seek=document.getElementById('seek'),progress=document.getElementById('progress'),pause=document.getElementById('pause'),media=matchMedia('(prefers-reduced-motion: reduce)');let p=media.matches?.7:0,manual=false,paused=false,inView=true,dead=false,raf=null,w=0,h=0,fallbackTime=0,last=null,frameVersion=0;const clean=[];
function on(el,event,fn,options){el.addEventListener(event,fn,options);clean.push(()=>el.removeEventListener(event,fn,options))}
function size(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);w=r.width;h=r.height;canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0);render()}
function calc(){if(!manual&&!media.matches){const r=scene.getBoundingClientRect();p=Math.max(0,Math.min(1,(52-r.top)/Math.max(1,r.height-(innerHeight-52))))}render()}
function render(){if(dead)return;ctx.clearRect(0,0,w,h);if(media.matches||video.error||video.readyState<2)MotionScene.renderBackgroundLayer(ctx,w,h,p,{time:media.matches?0:fallbackTime});const current=MotionScene.renderOverlay(ctx,w,h,p,{paused:paused||media.matches,reducedMotion:media.matches});video.style.transform='translateY('+(current.backgroundOffset*h/690)+'px)';seek.value=String(Math.round(p*1000));progress.value=Math.round(p*100)+'%';pause.setAttribute('aria-label',paused?'Play background video':'Pause background video')}
// Only an active missing-video fallback needs RAF; static states repaint on events.
function needsFrame(){return !dead&&!paused&&!media.matches&&inView&&!document.hidden&&(video.readyState<2||!!video.error)}
// Invalidate cancelled callbacks and discard idle time before any restart.
function stopFrame(){if(raf!==null)cancelAnimationFrame(raf);raf=null;last=null;frameVersion++}
function syncFrames(){if(!needsFrame()){stopFrame();return}if(raf===null){const version=frameVersion;raf=requestAnimationFrame(now=>tick(now,version))}}
function playMedia(){if(dead)return;syncFrames();if(media.matches||paused||!inView||document.hidden){video.pause();return}video.play().catch(()=>{})}
function tick(now,version){if(dead||version!==frameVersion)return;raf=null;if(!needsFrame()){stopFrame();return}const dt=last===null?0:Math.min(.1,(now-last)/1000);last=now;fallbackTime=(fallbackTime+dt)%6;render();syncFrames()}
on(window,'scroll',calc,{passive:true});on(window,'resize',()=>{size();calc()});on(seek,'input',()=>{manual=true;p=Number(seek.value)/1000;render()});on(document.getElementById('scroll'),'click',()=>{manual=false;calc()});on(document.getElementById('reset'),'click',()=>{manual=true;p=0;fallbackTime=0;last=null;video.currentTime=0;render()});on(pause,'click',()=>{paused=!paused;playMedia();render()});on(media,'change',()=>{if(media.matches){manual=true;p=.7}playMedia();render()});on(document,'visibilitychange',()=>{playMedia();render()});for(const event of ['loadstart','loadedmetadata','loadeddata','canplay','canplaythrough','emptied','waiting','stalled','error'])on(video,event,()=>{syncFrames();render()});
let observer=new IntersectionObserver(entries=>{if(dead)return;inView=entries[0].isIntersecting;if(!inView){video.pause();video.currentTime=0;fallbackTime=0}playMedia();render()},{threshold:0});observer.observe(scene);clean.push(()=>observer.disconnect());document.getElementById('claims').innerHTML=MotionScene.claims.map(a=>'<li>'+a.join(' ')+'</li>').join('');
window.MOTION={setProgress(value){manual=true;p=Math.max(0,Math.min(1,Number(value)||0));render()},getState(){return {...MotionScene.state(p),paused,reducedMotion:media.matches,manual,mediaTime:video.currentTime,fallbackTime}},destroy(){if(dead)return;dead=true;stopFrame();video.pause();clean.forEach(fn=>fn())},setPaused(value){paused=!!value;playMedia();render()}};size();calc();playMedia()})();
