import test from 'node:test';import assert from 'node:assert/strict';
import {completionAt,clampDisplaySize,fitDisplaySize,nativeSpec,springProgress} from '../src/native-spec.mjs';
test('native clamp and aspect fit preserve source geometry',()=>{assert.equal(clampDisplaySize(NaN),200);assert.equal(clampDisplaySize(0),1);assert.equal(clampDisplaySize(1000),400);assert.deepEqual(fitDisplaySize(960,600,400),{width:400,height:250})});
test('native completion stages are at zero, one and cumulative 2.5 seconds',()=>{assert.equal(completionAt(0).stage,'applicationIcon');assert.equal(completionAt(.999).stage,'applicationIcon');assert.equal(completionAt(1).stage,'fullCheckmark');assert.equal(completionAt(2.499).stage,'fullCheckmark');assert.equal(completionAt(2.5).stage,'miniCheckmark')});
test('missing application icon skips icon and never enters mini badge',()=>{assert.equal(completionAt(0,{hasIcon:false}).stage,'fullCheckmark');assert.equal(completionAt(40,{hasIcon:false}).stage,'fullCheckmark');assert.equal(completionAt(40,{hasIcon:false}).badgeOpacity,0)});
test('settled completion values match source constants',()=>{const s=completionAt(5);assert.equal(s.scrim,.17);assert.equal(s.icon,1);assert.equal(s.dim,0);assert.equal(s.badgeOpacity,1);assert.ok(Math.abs(s.offset-18)<1e-8);assert.ok(Math.abs(s.checkScale-.5)<1e-8)});
test('completion spring has source stiffness and damping',()=>{assert.equal(nativeSpec.completionSpring.stiffness,170);assert.equal(nativeSpec.completionSpring.damping,18);assert.equal(springProgress(0),0);assert.ok(springProgress(.3)>1)});
test('invalid aspect sizes fall back to square and thin dimension floors at one point',()=>{assert.deepEqual(fitDisplaySize(NaN,600,400),{width:400,height:400});assert.deepEqual(fitDisplaySize(1,10000,100),{width:1,height:100})});
test('missing icon does not create a phantom dim-mask square',()=>{assert.equal(completionAt(2,{hasIcon:false}).dim,0);assert.equal(completionAt(2,{hasIcon:false}).icon,0);assert.equal(completionAt(2,{hasIcon:false}).checkOpacity,1)});
