import {gunzipSync} from 'node:zlib';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {PresentationStack,nativeRestOffset,nativeSpringStep,motionSpring,meanRenderedStackAnchor,snapReleaseVelocity} from '../src/stack-behavior.mjs';
const near=(a,b,message='')=>assert.ok(Math.abs(a-b)<1e-8,`${message}: ${a} != ${b}`);
const point=(a,b,message='')=>{near(a.x,b.x,message+' x');near(a.y,b.y,message+' y')};
const traceURL=new URL('../artifacts/snapping/trajectory-trace.json',import.meta.url);
const trace=JSON.parse(fs.existsSync(traceURL)?fs.readFileSync(traceURL,'utf8'):gunzipSync(Buffer.from(fs.readFileSync(new URL('../artifacts/snapping/trajectory-trace.json.gz.b64',import.meta.url),'utf8'),'base64')).toString('utf8'));

test('release mean uses actual initialized contributors and preserved rest offsets',()=>{assert.deepEqual(meanRenderedStackAnchor([{position:{x:100,y:200},restOffset:{x:-400,y:-250}},{position:{x:300,y:400},restOffset:{x:-428,y:-272}},{position:{x:999,y:999},restOffset:{x:0,y:0},initialized:false},{position:{x:999,y:999},restOffset:{x:0,y:0},contributes:false}]),{x:614,y:561});assert.deepEqual(meanRenderedStackAnchor([],{x:24,y:676}),{x:24,y:676})});
test('release impulse threshold is inclusive120, quarter speed and distance attenuated',()=>{assert.deepEqual(snapReleaseVelocity({x:119.999,y:0}),{x:0,y:0});assert.deepEqual(snapReleaseVelocity({x:120,y:0}),{x:30,y:0});point(snapReleaseVelocity({x:400,y:-200},2),{x:100/1.9,y:-50/1.9});point(snapReleaseVelocity({x:400,y:-200},-1),{x:100/1.45,y:-50/1.45})});
test('grabbing an already-moving item uses actual origin rather than stale target',()=>{const s=new PresentationStack({maxDisplaySize:400});s.registerHost({id:'h',frame:{x:0,y:0,width:1000,height:700}});s.setAnchor('h:2');s.upsert({id:'front',threadID:'t'});s.recordRenderedPosition('front',{x:300,y:300});assert.equal(s.beginDrag('front',{x:350,y:350},0),true);const state=s.updateDrag({x:351,y:350},1/60);assert.deepEqual(state.currentAnchor,{x:701,y:550});assert.equal(state.hasMoved,false)});
test('after rear-card promotion its impulse becomes lead impulse, followers decay by new order',()=>{const s=new PresentationStack({maxDisplaySize:400});s.registerHost({id:'h',frame:{x:0,y:0,width:1000,height:700}});s.setAnchor('h:2');s.upsert({id:'rear',threadID:'t'});s.upsert({id:'front',threadID:'t'});s.recordRenderedPosition('front',{x:576,y:426});s.recordRenderedPosition('rear',{x:548,y:404});s.beginDrag('rear',{x:600,y:450},0);s.updateDrag({x:650,y:450},1/60);const state=s.endDrag();assert.deepEqual(s.order,['rear','front']);assert.equal(state.shouldFocus,false);assert.equal(state.programmaticMove,false);point(state.releaseVelocities[0].velocity,snapReleaseVelocity(state.velocity,0));point(state.releaseVelocities[1].velocity,snapReleaseVelocity(state.velocity,1));assert.equal(state.releaseVelocities[0].id,'rear')});
test('removed presentations cannot leave a stale rendered anchor contribution',()=>{const s=new PresentationStack();s.registerHost({id:'h',frame:{x:0,y:0,width:1000,height:700}});s.setAnchor('h:2');s.upsert({id:'a',threadID:'t'});s.recordRenderedPosition('a',{x:500,y:500});s.remove('a');assert.equal(s.renderedPositions.size,0);assert.deepEqual(s.renderedAnchor(),{x:976,y:676})});

for(const name of ['slow','fast'])test(`integrated PresentationStack reproduces independently verified ${name} trace`,()=>{
 const expected=trace[name],size={width:240,height:150},stack=new PresentationStack({maxDisplaySize:240}),host={id:'fixture-host',frame:{x:46,y:214,width:1188,height:478}};
 stack.registerHost(host);stack.setAnchor('fixture-host:2');for(let index=2;index>=0;index--)stack.upsert({id:String(index),threadID:'fixture-thread'});
 const initial=stack.currentAnchor().point,motion=new Map();for(let index=0;index<3;index++){const offset=nativeRestOffset(2,index,size),position={x:initial.x+offset.x,y:initial.y+offset.y};motion.set(String(index),{position,velocity:{x:0,y:0}});stack.recordRenderedPosition(String(index),position)}
 let active=false,released=false,settledAt=null;
 for(const frame of expected.history){const time=frame.time;let held=false;
  if(time>=expected.start-1e-9&&time<=expected.release+1e-9){held=true;if(!stack.drag)stack.beginDrag('0',{x:initial.x-120,y:initial.y-75},expected.start);stack.updateDrag(frame.pointer,time);active=true;}
  if(!released&&time>=expected.release-1e-9){held=false;released=true;const release=stack.endDrag();point(release.actualAnchor,expected.releaseState.anchor,'mean anchor');assert.equal(release.target.alignment,expected.releaseState.target.alignment);assert.equal(release.programmaticMove,false);for(const injection of release.releaseVelocities){const state=motion.get(injection.id);state.velocity={...injection.velocity};point(state.velocity,expected.releaseState.injectedVelocities[Number(injection.id)],'injected velocity');}active=true;}
  const anchor=stack.drag?.snapshot().currentAnchor??stack.currentAnchor().point,alignment=stack.currentAnchor().alignment;
  if(active){let all=true;for(const [index,id]of stack.order.entries()){const state=motion.get(id),offset=nativeRestOffset(alignment,index,size),target={x:anchor.x+offset.x,y:anchor.y+offset.y},step=nativeSpringStep({...state,target},1/60,motionSpring({index,dragging:held,programmatic:false}));state.position=step.position;state.velocity=step.velocity;stack.recordRenderedPosition(id,state.position);all&&=step.settled;}if(released&&all){active=false;settledAt??=time;}}
  assert.equal(active,frame.running);for(const item of frame.items){const actual=motion.get(String(item.index));point(actual.position,item.position,`${name} frame${time} position`);point(actual.velocity,item.velocity,`${name} frame${time} velocity`);}
 }
 near(settledAt,expected.settledAt);assert.equal(stack.currentAnchor().alignment,name==='slow'?2:0);
});
