(function(root,factory){if(typeof module==='object')module.exports=factory();else root.Scene=factory();})(this,function(){
'use strict';
const W=1080,H=882,FPS=60,DURATION=20;
const STEPS=[
 {title:'Search competitor pricing pages',description:['Query Google for the pricing pages of our top 5 competitors and','collect URLs.'],tool:'Web',icon:'search'},
 {title:'Extract pricing tiers',description:['Read each pricing page and pull plan names, prices, and feature','lists.'],tool:'Browser',icon:'file'},
 {title:'Compare to our plans',description:['Match feature parity, find gaps, and flag pricing outliers.'],tool:'Compute',icon:'star'},
 {title:'Draft summary doc',description:['Write a 1-page brief with recommendations and a comparison','table.'],tool:'Docs',icon:'pencil'},
 {title:'Email draft to product team',description:['Send the brief to product@acme.co with a request for feedback by','Friday.'],tool:'Gmail',icon:'send'}
];
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const ease=v=>{v=clamp(v);return v*v*(3-2*v);};
const mix=(a,b,t)=>a+(b-a)*t;
function initial(){return{statuses:Array(5).fill('planned'),expanded:0,phase:'review',queue:[],cursor:0,elapsed:0,ran:0};}
function clean(s){return{statuses:[...s.statuses],expanded:s.expanded,phase:s.phase,queue:[...(s.queue||[])],cursor:s.cursor||0,elapsed:s.elapsed||0,ran:s.ran||0};}
function action(state,a){const s=clean(state);if(a.type==='reset')return initial();if(a.type==='tick'){if(s.phase!=='running')return s;s.elapsed+=Math.max(0,a.seconds||0);while(s.phase==='running'&&s.elapsed>=1.8){s.elapsed-=1.8;s.statuses[s.queue[s.cursor]]='done';s.ran++;s.cursor++;if(s.cursor>=s.queue.length){s.phase='complete';s.expanded=-1;}else s.statuses[s.queue[s.cursor]]='running';}return s;}if(s.phase!=='review')return s;
 if(a.type==='toggle'){s.expanded=s.expanded===a.index?-1:clamp(a.index,0,4);return s;}
 if(a.type==='approveAll'){s.statuses=s.statuses.map(()=> 'approved');return s;}
 if(a.type==='run'){s.queue=s.statuses.flatMap((v,i)=>v==='approved'?[i]:[]);if(!s.queue.length)return s;s.phase='running';s.cursor=0;s.elapsed=0;s.ran=0;s.expanded=-1;s.statuses[s.queue[0]]='running';return s;}
 if(['approve','skip','undo'].includes(a.type)){const i=clamp(a.index,0,4);s.statuses[i]=a.type==='approve'?'approved':a.type==='skip'?'skipped':'planned';s.expanded=a.type==='undo'?i:s.statuses.findIndex((v,j)=>j>i&&v==='planned');return s;}return s;
}
function counts(s){return{decided:s.statuses.filter(v=>v!=='planned').length,approved:s.statuses.filter(v=>v==='approved').length,skipped:s.statuses.filter(v=>v==='skipped').length,done:s.statuses.filter(v=>v==='done').length};}
const APPROVALS=[[.66,0],[1.9,1],[2.93,2],[4.1,3],[5.43,4]];
const EXPANSIONS=[[0,0],[.84,1],[2.08,2],[3.1,3],[4.28,4],[5.56,-1]];
function weightsAt(t){const weights=Array(5).fill(0);let previous=0;for(let k=1;k<EXPANSIONS.length;k++){const [at,next]=EXPANSIONS[k];if(t<at){if(previous>=0)weights[previous]=1;return weights;}if(t<at+.32){const p=ease((t-at)/.32);if(previous>=0)weights[previous]=1-p;if(next>=0)weights[next]=p;return weights;}previous=next;}if(previous>=0)weights[previous]=1;return weights;}
function timeline(time){let t=((time%DURATION)+DURATION)%DURATION,opacity=1;if(t>=18.8&&t<19.2)opacity=1-ease((t-18.8)/.4);if(t>=19.2){opacity=ease((t-19.2)/.5);t=0;}
 const s=initial();s.recorded=true;s.time=t;s.opacity=opacity;s.weights=weightsAt(t);s.completeBlend=0;s.recordedRunLabel='';
 for(const [at,i]of APPROVALS)if(t>=at)s.statuses[i]=i===4?'skipped':'approved';
 let expanded=0;for(const [at,i]of EXPANSIONS)if(t>=at)expanded=i;s.expanded=expanded;
 if(t>=6.86&&t<14.9){s.phase='running';s.expanded=-1;s.weights=Array(5).fill(0);const starts=[6.86,8.66,10.43,12.39];let current=0;for(let i=0;i<4;i++)if(t>=starts[i])current=i;s.cursor=current;s.queue=[0,1,2,3];s.statuses=s.statuses.map((v,i)=>i<current?'done':i===current?'running':v);s.ran=current;const remaining=4-current;s.recordedRunLabel='Running step '+Math.min(current+1,remaining)+' of '+remaining;}
 if(t>=14.9&&t<16.42){s.phase='complete';s.expanded=-1;s.weights=Array(5).fill(0);s.statuses=['done','done','done','done','skipped'];s.completeBlend=ease((t-14.9)/.33);s.ran=0;}
 if(t>=16.42){Object.assign(s,initial());s.recorded=true;s.time=t;s.opacity=opacity;s.weights=[1,0,0,0,0];s.completeBlend=1-ease((t-16.42)/.35);if(t>=18.07)s.statuses=Array(5).fill('approved');}
 return s;
}
function layout(s){const weights=s.weights||STEPS.map((_,i)=>i===s.expanded?1:0),extra=weights.reduce((a,w,i)=>a+w*(STEPS[i].description.length===1?115:137),0),complete=s.completeBlend??(s.phase==='complete'?1:0),reviewHeight=461+extra,height=mix(reviewHeight,323,complete),y=(873-height)/2,innerY=y+71,innerH=mix(312+extra,239,complete);let offset=0;const rows=STEPS.map((step,i)=>{const row={index:i,top:innerY+16+i*59+offset,titleY:innerY+42+i*59+offset,weight:weights[i]};offset+=weights[i]*(step.description.length===1?115:137);row.bottom=innerY+68+i*59+offset;return row;});return{x:253,y,w:568,h:height,innerX:266,innerY,innerW:542,innerH,rows,complete,weights,footerY:y+height-42};}
function rr(c,x,y,w,h,r,fill,stroke){c.beginPath();c.roundRect(x,y,Math.max(.1,w),Math.max(.1,h),r);if(fill){c.fillStyle=fill;c.fill();}if(stroke){c.lineWidth=1;c.strokeStyle=stroke;c.stroke();}}
function text(c,s,x,y,size=16,col='#22252b',weight=400,align='left',family='Replica Sans'){c.font=`${weight} ${size}px "${family}"`;c.textAlign=align;c.textBaseline='alphabetic';c.fillStyle=col;c.fillText(s,x,y);}
function line(c,x,y,X,Y,col,width=1){c.beginPath();c.moveTo(x,y);c.lineTo(X,Y);c.strokeStyle=col;c.lineWidth=width;c.stroke();}
function icon(c,type,x,y,col='#777b83',t=0){c.save();c.translate(x,y);c.strokeStyle=col;c.fillStyle=col;c.lineWidth=1.45;c.lineCap='round';c.lineJoin='round';c.beginPath();if(type==='search'){c.arc(-1,-1,4.5,0,Math.PI*2);c.moveTo(2.5,2.5);c.lineTo(6,6);c.stroke();}else if(type==='file'){c.moveTo(-4,-6);c.lineTo(1,-6);c.lineTo(5,-2);c.lineTo(5,6);c.lineTo(-4,6);c.closePath();c.moveTo(0,-6);c.lineTo(0,-1);c.lineTo(5,-1);c.moveTo(-1,2);c.lineTo(2,2);c.stroke();}else if(type==='star'){c.moveTo(0,-6);c.quadraticCurveTo(1,0,6,0);c.quadraticCurveTo(1,1,0,6);c.quadraticCurveTo(-1,1,-6,0);c.quadraticCurveTo(-1,-1,0,-6);c.fill();}else if(type==='pencil'){c.rotate(.68);c.roundRect(-2.5,-6,5,11,1);c.moveTo(-2.5,2);c.lineTo(2.5,2);c.moveTo(-2.5,5);c.lineTo(0,8);c.lineTo(2.5,5);c.stroke();}else if(type==='send'){c.moveTo(-6,-1);c.lineTo(6,-6);c.lineTo(2,7);c.lineTo(-1,1);c.closePath();c.moveTo(-1,1);c.lineTo(6,-6);c.stroke();}else if(type==='check'){c.moveTo(-5,0);c.lineTo(-1,4);c.lineTo(6,-5);c.stroke();}else if(type==='spinner'){c.rotate(t*4);c.arc(0,0,6,-Math.PI*.45,Math.PI*1.15);c.stroke();}else if(type==='play'){c.moveTo(-2,-4);c.lineTo(4,0);c.lineTo(-2,4);c.closePath();c.stroke();}else if(type==='undo'){c.arc(0,0,5,-2.4,2.4);c.moveTo(-5,-5);c.lineTo(-5,0);c.lineTo(0,-1);c.stroke();}c.restore();}
const STATUS={planned:['Planned','#f2f2f4','#7c7f86'],approved:['Approved','#e5fcf2','#218f70'],skipped:['Skipped','#f2f2f4','#888b94'],running:['Running','#fff5d4','#c59121'],done:['Done','#e5fcf2','#218f70']};
function badge(c,status,y){const [label,bg,ink]=STATUS[status];c.font='400 12px "Replica Sans"';const w=c.measureText(label).width+22;rr(c,787-w,y-19,w,25,13,bg);text(c,label,787-w/2,y-1,12,ink,400,'center');}
function pill(c,x,y,w,label,kind='neutral',symbol){const bg=kind==='green'?'#008e63':kind==='dark'?'#17191c':kind==='disabled'?'#dedee5':kind==='running'?'#fff5b9':'#f1f1f4',fg=kind==='green'||kind==='dark'?'#fff':kind==='disabled'?'#aaa':kind==='running'?'#a86c08':'#565a65';rr(c,x,y,w,38,20,bg);if(symbol)icon(c,symbol,x+18,y+19,fg,0);text(c,label,x+w/2+(symbol?6:0),y+25,14,fg,kind==='green'||kind==='dark'?500:400,'center');}
function reviewLayer(c,s,l,t){c.save();c.globalAlpha*=1-l.complete;c.beginPath();c.roundRect(l.innerX,l.innerY,l.innerW,l.innerH,23);c.clip();l.rows.forEach((r,i)=>{const step=STEPS[i],status=s.statuses[i],active=status==='approved'||status==='done',ink=status==='skipped'?'#aaaeb8':'#24272d',symbol=status==='done'?'check':status==='running'?'spinner':step.icon;icon(c,symbol,299,r.titleY-5,status==='running'?'#d99413':active?'#00a77b':status==='skipped'?'#b6b9c3':'#797d86',t);text(c,step.title,325,r.titleY,16,ink);if(status==='skipped'){c.font='400 16px "Replica Sans"';line(c,325,r.titleY-5,325+c.measureText(step.title).width,r.titleY-5,'#a8aab4',1.2);}badge(c,status,r.titleY);
 if(r.weight>.001){c.save();c.globalAlpha*=ease(r.weight);c.beginPath();c.rect(315,r.titleY+10,480,Math.max(0,r.bottom-r.titleY-10));c.clip();step.description.forEach((v,j)=>text(c,v,325,r.titleY+34+j*22,14,'#777b87'));const toolY=r.titleY+(step.description.length===1?54:76);c.font='400 12px "Replica Mono"';const tw=c.measureText(step.tool).width+14;rr(c,325,toolY,tw,24,5,'#f2f3f5');text(c,step.tool,332,toolY+16,12,'#9599a3',400,'left','Replica Mono');const py=toolY+38;if(status==='planned'){rr(c,325,py,90,34,18,'#008e63');icon(c,'check',341,py+17,'#fff');text(c,'Approve',351,py+22,14,'#fff',500);rr(c,423,py,66,34,18,'#f0f0f3');text(c,'× Skip',456,py+22,14,'#555a65',400,'center');}else{rr(c,325,py,59,30,16,'#f0f0f3');text(c,'Undo',354.5,py+20,12,'#656b77',400,'center');}c.restore();}
 if(i<4){c.save();c.setLineDash([2,3]);line(c,288,r.bottom,786,r.bottom,'#d8dce2',1);c.restore();}});c.restore();
 c.save();c.globalAlpha*=1-l.complete;const n=counts(s),fy=l.footerY;if(s.phase==='running'){const label=s.recordedRunLabel||'Running step '+(s.cursor+1)+' of '+s.queue.length;text(c,label,278,fy+5,14,'#7b7f8b');pill(c,673,fy-20,123,'In progress','running','spinner');}else{text(c,n.approved+' approved',278,fy+5,14,'#7b7f8b');if(n.decided<5)text(c,'Approve all',593,fy+5,14,'#454954');pill(c,690,fy-20,106,'Run plan',n.approved?'dark':'disabled','play');}c.restore();}
function completeLayer(c,s,l){if(l.complete<=0)return;c.save();c.globalAlpha*=l.complete;const y=l.innerY;rr(c,292,y+32,42,43,14,'#d3fbe9');icon(c,'check',313,y+53,'#15b68a');text(c,'Plan executed',292,y+114,22,'#1b1e23',500);const n=counts(s);text(c,(s.recorded?0:s.ran)+' steps ran, '+n.skipped+' skipped. Output sent to your inbox.',292,y+145,14,'#8b8e9b');pill(c,292,y+165,114,'New plan','neutral','undo');c.restore();}
function draw(c,time,assets={},manual){const s=manual||timeline(time),l=layout(s),n=counts(s),opacity=s.opacity??1;c.clearRect(0,0,W,H);c.fillStyle='#fdfdfd';c.fillRect(0,0,W,H);c.save();c.globalAlpha=opacity;c.save();c.shadowColor=`rgba(27,30,37,${.18*opacity})`;c.shadowBlur=31;c.shadowOffsetY=15;rr(c,l.x,l.y,l.w,l.h,38,'#f0f0f0');c.restore();c.save();c.shadowColor=`rgba(27,30,37,${.16*opacity})`;c.shadowBlur=3;c.shadowOffsetY=2;rr(c,l.x,l.y,l.w,l.h,38,'#f0f0f0','#e2e3e6');c.restore();text(c,'Agent plan',282,l.y+44,18,'#1a1d22',500);rr(c,379,l.y+26,78,26,14,'#e2e3e9');text(c,'5 steps',418,l.y+44,12,'#6b707b',400,'center','Replica Mono');const heading=s.phase==='running'?'Running plan':s.phase==='complete'?'Plan complete':n.decided+' of 5 decided';text(c,heading,790,l.y+44,14,s.phase==='running'?'#c8890d':s.phase==='complete'?'#00a77d':'#696e79',500,'right');if(s.phase==='running'){c.fillStyle='#d9a236';c.beginPath();c.arc(695,l.y+38,3,0,7);c.fill();}rr(c,l.innerX,l.innerY,l.innerW,l.innerH,23,'#fff');reviewLayer(c,s,l,time);completeLayer(c,s,l);c.restore();return l;}
function hitTargets(s){const l=layout(s),targets=[];if(s.phase==='complete'){targets.push({label:'New plan',x:292,y:l.innerY+165,w:114,h:38,action:{type:'reset'}});return targets;}if(s.phase==='running')return targets;for(const r of l.rows){targets.push({label:STEPS[r.index].title,x:286,y:r.titleY-25,w:502,h:42,action:{type:'toggle',index:r.index}});if(r.weight>.8){const y=r.titleY+(STEPS[r.index].description.length===1?54:76)+38;if(s.statuses[r.index]==='planned'){targets.push({label:'Approve '+STEPS[r.index].title,x:325,y,w:90,h:34,action:{type:'approve',index:r.index}},{label:'Skip '+STEPS[r.index].title,x:423,y,w:66,h:34,action:{type:'skip',index:r.index}});}else targets.push({label:'Undo '+STEPS[r.index].title,x:325,y,w:59,h:30,action:{type:'undo',index:r.index}});}}const n=counts(s);if(n.decided<5)targets.push({label:'Approve all',x:580,y:l.footerY-20,w:99,h:38,action:{type:'approveAll'}});targets.push({label:'Run plan',x:690,y:l.footerY-20,w:106,h:38,disabled:!n.approved,action:{type:'run'}});return targets;}
return{W,H,FPS,DURATION,STEPS,initial,clean,action,counts,timeline,layout,draw,hitTargets,STILLS:{initial:0,review:2.6,decided:6,running:9,complete:15.8}};
});
