#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path');const R=require('./render.cjs'),M=require('../src/motion.js'),S=require('../src/scene.js');
async function main(){const a=R.args(process.argv.slice(2));if(!a.source)throw new Error('Pass --source with the independently downloaded official MP4');const before=R.coreHashes();const source=path.resolve(a.source),out=path.join(R.ROOT,'preview'),frames=path.join(out,'comparison-frames');fs.mkdirSync(frames,{recursive:true});const ref=R.sourceTimeline(source,0,7.5);if(ref.source.sha256!==M.referenceSpec.sourceSha256)throw new Error('Unexpected source hash');const sourceFrames=path.join(out,'source-frames');fs.mkdirSync(sourceFrames,{recursive:true});R.run('ffmpeg',['-v','error','-threads','1','-i',source,'-t','7.5','-fps_mode','passthrough','-start_number','0','-y',path.join(sourceFrames,'%06d.png')]);
const label=Buffer.from('<svg width="1000" height="48" xmlns="http://www.w3.org/2000/svg"><rect width="1000" height="48" fill="#202b31"/><g font-family="sans-serif" font-size="16" fill="#fff"><text x="18" y="29">Things 3 · Cultured Code · official 2017</text><text x="519" y="29">Reconstruction · original text · shared SVG scene</text></g></svg>');
const header=await R.sharp(label).png().toBuffer();const observations=[];const normal=JSON.parse(fs.readFileSync(path.join(out,'render-manifest.json')));if(JSON.stringify(normal.core)!==JSON.stringify(before))throw new Error('Normal export is stale');
for(const f of ref.frames){const existing=path.join(out,'frames',f.file);const ours=fs.existsSync(existing)?fs.readFileSync(existing):await R.sharp(Buffer.from(S.render(M.referenceAt(f.time)))).png().toBuffer();if(R.bufferHash(ours)!==normal.frames[f.index].rasterSha256)throw new Error('Raster differs from normal export');const original=path.join(sourceFrames,f.file),p=path.join(frames,f.file);await R.sharp({create:{width:1000,height:936,channels:4,background:'#fff'}}).composite([{input:header,left:0,top:0},{input:original,left:0,top:48},{input:ours,left:500,top:48}]).png().toFile(p);observations.push({pts:f.pts,time:f.time,sourceRasterSha256:R.sha256(original),reconstructionRasterSha256:R.bufferHash(ours),comparisonRasterSha256:R.sha256(p)});}
const media=R.encodeSequence(frames,path.join(out,'comparison'),{fps:ref.fps,timeBase:'1/30000',width:1000,height:936,frameCount:ref.frames.length});
if(JSON.stringify(R.coreHashes())!==JSON.stringify(before))throw new Error('Core changed during comparison');const report={method:'Side-by-side source frames and reconstruction at identical source PTS; neither panels retimed; original excerpt is review-only and attributed',source:ref.source,range:{start:0,endExclusive:7.5},core:R.coreHashes(),harnessSha256:R.sha256(__filename),timing:R.timingManifest(ref.frames,media),frames:observations,outputs:Object.fromEntries(['comparison.gif','comparison.mp4'].map(p=>[p,R.sha256(path.join(out,p))]))};fs.writeFileSync(path.join(out,'comparison-manifest.json'),JSON.stringify(report,null,2)+'\n');await R.sharp(path.join(frames,'000045.png')).png().toFile(path.join(out,'comparison-poster.png'));fs.rmSync(frames,{recursive:true});fs.rmSync(sourceFrames,{recursive:true});console.log(JSON.stringify({comparisonFrames:ref.frames.length,outputs:report.outputs}));}
main().catch(e=>{console.error(e);process.exitCode=1});
