import test from'node:test';import assert from'node:assert/strict';
async function harness(reduced,tag){
 const nodes=new Map();for(const id of['stage','art','replay','open','download'])nodes.set(id,{hidden:false,innerHTML:'',listeners:{},attributes:{},addEventListener(name,fn){this.listeners[name]=fn;},setAttribute(k,v){this.attributes[k]=v;},getBoundingClientRect(){return{left:0,top:0,width:824,height:720};}});
 const globals={document:globalThis.document,matchMedia:globalThis.matchMedia,requestAnimationFrame:globalThis.requestAnimationFrame,addEventListener:globalThis.addEventListener};const handlers={},frames=[];
 globalThis.document={querySelector:s=>nodes.get(s.slice(1))};globalThis.matchMedia=()=>({matches:reduced});globalThis.requestAnimationFrame=fn=>frames.push(fn);globalThis.addEventListener=(name,fn)=>handlers[name]=fn;
 await import(`../src/main.mjs?dom-test=${tag}`);
 return{nodes,handlers,frames,restore(){for(const[k,v]of Object.entries(globals)){if(v===undefined)delete globalThis[k];else globalThis[k]=v;}}};
}
test('DOM bindings keep reduced-motion open, Escape and replay stationary',async()=>{const h=await harness(true,'reduced');try{const stage=h.nodes.get('stage');assert.equal(stage.attributes['data-state'],'closed');assert.equal(h.frames.length,0);h.nodes.get('open').listeners.click({stopPropagation(){}});assert.equal(stage.attributes['data-state'],'open');assert.equal(h.nodes.get('download').hidden,false);h.handlers.keydown({key:'Escape'});assert.equal(stage.attributes['data-state'],'closed');assert.equal(h.nodes.get('download').hidden,true);h.nodes.get('replay').listeners.click();assert.equal(stage.attributes['data-state'],'closed');assert.ok(h.nodes.get('art').innerHTML.startsWith('<svg'));}finally{h.restore();}});
test('Escape on the initial replay pose remains closed on the next animation tick',async()=>{const h=await harness(false,'motion');try{const stage=h.nodes.get('stage');assert.equal(stage.attributes['data-state'],'demo');h.handlers.keydown({key:'Escape'});assert.equal(stage.attributes['data-state'],'closed');h.frames.shift()();assert.equal(stage.attributes['data-state'],'closed');h.nodes.get('open').listeners.click({stopPropagation(){}});assert.equal(stage.attributes['data-state'],'opening');h.handlers.keydown({key:'Escape'});assert.ok(['closing','closed'].includes(stage.attributes['data-state']));}finally{h.restore();}});
