import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{createRequire}from'node:module';const require=createRequire(import.meta.url);const{parseHTML}=require('linkedom');
test('DOM event harness: error retry, success, Escape, replay and pause',async()=>{
 const{document,window}=parseHTML(fs.readFileSync(new URL('../index.html',import.meta.url),'utf8'));let time=0,next;
 const gradient={addColorStop(){}};const ctx=new Proxy({}, {get(o,k){if(k==='measureText')return text=>({width:text.length*22});if(k==='createLinearGradient')return()=>gradient;return o[k]||(()=>{});},set(o,k,v){o[k]=v;return true;}});
 document.getElementById('scene').getContext=()=>ctx;document.fonts={ready:Promise.resolve(),load:async()=>[]};Object.assign(globalThis,{document,location:{search:''},matchMedia:()=>({matches:false,addEventListener(){}}),requestAnimationFrame:fn=>{next=fn;},performance:{now:()=>time*1000}});
 await import('../src/app.mjs');const $=id=>document.getElementById(id);const step=t=>{time=t;const f=next;next=null;assert.ok(f);f();};const click=id=>$(id).dispatchEvent(new window.Event('click'));const input=(value,t)=>{time=t;$('code').value=value;$('code').dispatchEvent(new window.Event('input'));};
 step(0);click('live');step(.1);assert.match($('status').textContent,/Enter six digits/);input('213212',.2);step(1.65);assert.match($('status').textContent,/not accepted/);step(2.6);assert.equal($('code').value,'');assert.match($('status').textContent,/Enter six digits/);input('123456',2.7);step(4.2);assert.match($('status').textContent,/verified/);
 const escape=new window.Event('keydown');escape.key='Escape';$('code').dispatchEvent(escape);step(4.3);assert.match($('status').textContent,/Click Enter/);assert.equal($('code').value,'');click('replay');step(4.4);click('pause');assert.equal($('pause').textContent,'Resume');click('pause');assert.equal($('pause').textContent,'Pause');step(20);assert.equal($('pause').textContent,'Play again');click('pause');step(20.01);assert.equal($('pause').textContent,'Pause');click('live');step(20.02);assert.match($('status').textContent,/Enter six digits/);
});
