import fs from'node:fs/promises';import path from'node:path';import{spawnSync}from'node:child_process';import{createRequire}from'node:module';import{renderScene}from'../src/scene.mjs';
const require=createRequire(import.meta.url);const sharp=require('sharp');const root=new URL('..',import.meta.url).pathname;const out=path.join(root,'deliverables');const frames=path.join(root,'evidence/replica-native');await fs.mkdir(frames,{recursive:true});await fs.mkdir(out,{recursive:true});
const timestamps=JSON.parse(await fs.readFile(path.join(root,'evidence/native-timestamps.json'))).frames.map(f=>+f.best_effort_timestamp_time);const cursors=JSON.parse(await fs.readFile(path.join(root,'src/cursor-timeline.json')));
function cursorAt(t){let hi=cursors.findIndex(p=>p[0]>t);if(hi<0)return cursors.at(-1).slice(1);if(hi===0)return cursors[0].slice(1);const a=cursors[hi-1],b=cursors[hi],v=(t-a[0])/(b[0]-a[0]);return[a[1]+(b[1]-a[1])*v,a[2]+(b[2]-a[2])*v]}
const args=process.argv.slice(2);const only=args.includes('--keys');let inds=only?[0,35,48,60,100,135,142,200,220,250,314,395,410,490,534,545,575]:timestamps.map((_,i)=>i);
for(const i of inds){await sharp(Buffer.from(renderScene(timestamps[i],{cursor:cursorAt(timestamps[i])}))).png().toFile(path.join(frames,`${String(i).padStart(4,'0')}.png`));}if(only){console.log('Keys rendered');process.exit()}
let concat='';for(let i=0;i<timestamps.length;i++)concat+=`file '${path.join(frames,`${String(i).padStart(4,'0')}.png`)}'\noption framerate 90000\nduration ${i<timestamps.length-1?(Math.round(timestamps[i+1]*1e6)-Math.round(timestamps[i]*1e6))/1e6:(10005933-Math.round(timestamps[i]*1e6))/1e6}\n`;concat+=`file '${path.join(frames,'0575.png')}'\noption framerate 90000\n`;await fs.writeFile(path.join(root,'evidence/concat.txt'),concat);
function ff(a){const r=spawnSync('ffmpeg',['-hide_banner','-loglevel','error','-y',...a],{stdio:'inherit'});if(r.status)throw Error(`ffmpeg ${r.status}`)}
ff(['-f','concat','-safe','0','-i',path.join(root,'evidence/concat.txt'),'-fps_mode','vfr','-enc_time_base','1/90000','-video_track_timescale','90000','-c:v','libx264','-crf','16','-pix_fmt','yuv420p','-movflags','+faststart','-t','10.005933',path.join(out,'micro-progress-button.mp4')]);
ff(['-i',path.join(out,'micro-progress-button.mp4'),'-filter_complex','fps=30,split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=sierra2_4a','-loop','0',path.join(out,'micro-progress-button.gif')]);
await fs.copyFile(path.join(frames,'0100.png'),path.join(out,'poster.png'));console.log('Clean offline MP4 and GIF rendered from shared scene.mjs; not a browser recording.');
