import {createRequire}from'node:module';const require=createRequire(import.meta.url);const{createCanvas,loadImage,GlobalFonts}=require('@napi-rs/canvas');GlobalFonts.registerFromPath(new URL('../assets/StudySans.ttf',import.meta.url).pathname,'StudySans');
import fs from'node:fs/promises';import path from'node:path';import{spawnSync}from'node:child_process';import{frameAt,DURATION}from'../src/geometry.mjs';import{ASSET_NAMES,makeTextures,drawRibbon}from'../src/scene.mjs';import{MOTION}from'../src/motion.mjs';
const root=new URL('..',import.meta.url).pathname;const textures=makeTextures(await Promise.all(ASSET_NAMES.map(n=>loadImage(path.join(root,'assets',n)))),createCanvas);for(let i=0;i<textures.length;i++){if(textures[i].toBuffer)textures[i]=await loadImage(textures[i].toBuffer('image/png'));}const w=1512,h=982,c=createCanvas(w,h),g=c.getContext('2d');const out=path.join(root,'deliverables');await fs.mkdir(out,{recursive:true});
const frames=path.join(root,'evidence/replica-native');await fs.mkdir(frames,{recursive:true});
const keys=process.argv.includes('--keys');const times=JSON.parse(await fs.readFile(path.join(root,'evidence/native-timestamps.json'),'utf8')).frames.map(f=>+f.best_effort_timestamp_time);const indexes=keys?[0,24,64,84,159,249,344,418,495,567,659,678]:times.map((_,i)=>i);
for(const i of indexes){drawRibbon(g,textures,frameAt(times[i],MOTION),{width:w,height:h});await fs.writeFile(path.join(frames,`${String(i).padStart(4,'0')}.png`),c.toBuffer('image/png'));if(i%100===0)console.log('Rendered',i);}
await fs.copyFile(path.join(frames,'0000.png'),path.join(out,'poster.png'));if(keys)process.exit();
let concat='';for(let i=0;i<times.length;i++)concat+=`file '${path.join(frames,`${String(i).padStart(4,'0')}.png`)}'\noption framerate 60000\nduration ${i+1<times.length?times[i+1]-times[i]:DURATION-times[i]}\n`;concat+=`file '${path.join(frames,'0678.png')}'\noption framerate 60000\n`;await fs.writeFile(path.join(root,'evidence/concat.txt'),concat);
function ff(args){const r=spawnSync('ffmpeg',['-hide_banner','-loglevel','error','-y',...args],{stdio:'inherit'});if(r.status)throw new Error(`ffmpeg failed ${r.status}`);}
ff(['-f','concat','-safe','0','-i',path.join(root,'evidence/concat.txt'),'-frames:v','679','-fps_mode','vfr','-enc_time_base','1/60000','-video_track_timescale','60000','-c:v','libx264','-bf','0','-crf','17','-pix_fmt','yuv420p','-movflags','+faststart','-t',String(DURATION),path.join(root,'evidence/encoded-no-b.mp4')]);
ff(['-i',path.join(root,'evidence/encoded-no-b.mp4'),'-c','copy','-bsf:v',"setts=duration='if(eq(N,678),1000,DURATION)'",'-movflags','+faststart',path.join(out,'curved-portfolio-ribbon.mp4')]);
ff(['-i',path.join(out,'curved-portfolio-ribbon.mp4'),'-filter_complex','fps=30,scale=1008:654,split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=sierra2_4a','-loop','0',path.join(out,'curved-portfolio-ribbon.gif')]);console.log('Native-timed offline MP4 and clean 30 fps GIF complete.');
