(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./motion.js'));else root.LyricsScene=factory(root.LyricsMotion);})(typeof globalThis!=='undefined'?globalThis:this,function(M){
'use strict';
const n=v=>Number(v.toFixed(4)),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const attrs=o=>Object.entries(o).map(([k,v])=>`${k}="${v}"`).join(' ');
function attributes(state){
 const out={};for(const l of state.lines){
  const id=String(l.id).replace(/[^a-zA-Z0-9_-]/g,'_');
  out['row-'+id]={transform:`translate(${n(l.x)} ${n(l.y)}) scale(${n(l.scale)})`,visibility:l.visible?'visible':'hidden'};
  out['base-'+id]={opacity:n(l.opacity)};out['lit-'+id]={opacity:n(l.litOpacity??(l.active?1:l.opacity))};
  out['highlight-'+id]={width:n(Math.max(0,l.w*l.highlight))};
  out['blur-'+id]={stdDeviation:n(Math.max(0,l.blur))};
  out['text-'+id]={textLength:n(Math.max(1,l.w-8)),y:n(l.fontSize*.9), 'font-size':n(l.fontSize)};
  out['textlit-'+id]={textLength:n(Math.max(1,l.w-8)),y:n(l.fontSize*.9), 'font-size':n(l.fontSize)};
 }return out;
}
function render(state){
 const W=state.width,H=state.height,a=attributes(state),d=id=>`id="${id}" ${attrs(a[id]||{})}`;
 const defs=state.lines.map(l=>{const id=String(l.id).replace(/[^a-zA-Z0-9_-]/g,'_');return`<filter id="soft-${id}" x="-15%" y="-40%" width="135%" height="180%"><feGaussianBlur ${d('blur-'+id)}/></filter><clipPath id="wipe-${id}"><rect ${d('highlight-'+id)} x="-1" y="-10" height="${l.fontSize*1.7}"/></clipPath>`;}).join('');
 const rows=state.lines.map(l=>{const id=String(l.id).replace(/[^a-zA-Z0-9_-]/g,'_'),text=(lit=false)=>`<text ${d((lit?'textlit-':'text-')+id)} x="4" lengthAdjust="spacingAndGlyphs" font-weight="${l.weight}" fill="#fff">${escape(l.text)}</text>`;return`<g ${d('row-'+id)} filter="url(#soft-${id})"><g ${d('base-'+id)}>${text()}</g><g ${d('lit-'+id)} clip-path="url(#wipe-${id})">${text(true)}</g></g>`;}).join('');
 return`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-label="Original text in an Apple Music lyrics motion study" style="font-family:Inter,Arial,sans-serif"><defs><clipPath id="screen"><rect width="${W}" height="${H}" rx="53"/></clipPath><linearGradient id="back" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#151315"/><stop offset=".52" stop-color="#301821"/><stop offset="1" stop-color="#191619"/></linearGradient><radialGradient id="mauve"><stop stop-color="#865170" stop-opacity=".75"/><stop offset="1" stop-color="#5a2c4a" stop-opacity="0"/></radialGradient><radialGradient id="rose"><stop stop-color="#713348" stop-opacity=".55"/><stop offset="1" stop-color="#713348" stop-opacity="0"/></radialGradient><linearGradient id="fade" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="black"/><stop offset=".075" stop-color="white"/><stop offset=".85" stop-color="white"/><stop offset="1" stop-color="black"/></linearGradient><mask id="lyrics-mask"><rect x="0" y="180" width="${W}" height="${H-192}" fill="url(#fade)"/></mask>${defs}</defs><g clip-path="url(#screen)"><rect width="${W}" height="${H}" fill="url(#back)"/><ellipse cx="384" cy="315" rx="196" ry="283" fill="url(#mauve)"/><ellipse cx="75" cy="494" rx="188" ry="294" fill="url(#rose)"/><ellipse cx="278" cy="694" rx="200" ry="204" fill="url(#mauve)" opacity=".57"/><text x="63" y="36" font-size="19" font-weight="700" fill="white">9:41</text><rect x="153" y="15" width="135" height="38" rx="21" fill="#000"/><g fill="white"><rect x="315" y="31" width="4" height="6" rx="1"/><rect x="321" y="28" width="4" height="9" rx="1"/><rect x="327" y="24" width="4" height="13" rx="1"/><rect x="333" y="21" width="4" height="16" rx="1"/></g><path d="M346 26Q354 19 362 26M349 30Q354 25 359 30M352 34L354 36L357 33" fill="none" stroke="#fff" stroke-width="2.7"/><rect x="374" y="24" width="25" height="13" rx="4" stroke="#fff" fill="none"/><rect x="376" y="26" width="21" height="9" rx="2" fill="#fff"/><rect x="400" y="28" width="2" height="5" fill="#fff"/><rect x="202" y="69" width="39" height="5" rx="3" fill="#9a858d" opacity=".55"/><rect x="42" y="97" width="65" height="65" rx="5" fill="#11151b"/><path d="M48 145L70 110L96 138L78 153Z" fill="#9178ad"/><path d="M52 144L72 120L89 136L76 147Z" fill="#dfbdd3"/><circle cx="88" cy="113" r="5" fill="#c99887"/><text x="120" y="122" font-size="19.5" font-weight="700" fill="#fff">Notes in Motion</text><text x="120" y="146" font-size="19" fill="#d6bbc7">Original type study</text><circle cx="386" cy="128" r="16" fill="#cdb5c3" opacity=".17"/><g fill="#fff"><circle cx="380" cy="128" r="1.7"/><circle cx="386" cy="128" r="1.7"/><circle cx="392" cy="128" r="1.7"/></g><g mask="url(#lyrics-mask)">${rows}</g><rect x="144" y="${H-14}" width="152" height="6" rx="3" fill="#fff"/></g></svg>`;
}
function patch(root,state){for(const[id,values]of Object.entries(attributes(state))){const node=root.querySelector('#'+id);if(node)for(const[k,v]of Object.entries(values))node.setAttribute(k,String(v));}}
return{render,patch,attributes};
});
