import {CONTROLS} from './controls.mjs';import {n,path,rounded,circle,text,stamp,invoice,project} from './art.mjs';
export const WIDTH=1080,HEIGHT=720,DURATION=10;
export const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),mix=(a,b,p)=>a+(b-a)*p;
export function nativeState(t){return structuredClone(CONTROLS[Math.min(522,Math.max(0,Math.round(t*60)))]);}
export function demoState(t){t=((t%DURATION)+DURATION)%DURATION;if(t<9)return nativeState(Math.min(t,8.7));if(t<9.6)return {crossfade:(t-9)/.6,from:nativeState(8.7),to:nativeState(0)};return nativeState(0);}
function physicalShadow(v){if(!v)return '';const [cx,cy,sx,sy,amp,p]=v,x=cx-3*sx,y=cy-3*sy,w=6*sx,h=6*sy,stops=Array.from({length:65},(_,j)=>{const a=j/64*6-3;return `<stop offset="${j/64}" stop-color="white" stop-opacity="${n(Math.exp(-.5*Math.abs(a)**p))}"/>`;}).join('');return `<defs><linearGradient id="shadeX">${stops.replaceAll('stop-color="white"','stop-color="black"')}</linearGradient><linearGradient id="shadeY" x1="0" y1="0" x2="0" y2="1">${stops}</linearGradient><mask id="shadeMask" maskUnits="userSpaceOnUse" x="${n(x)}" y="${n(y)}" width="${n(w)}" height="${n(h)}"><rect x="${n(x)}" y="${n(y)}" width="${n(w)}" height="${n(h)}" fill="url(#shadeY)"/></mask></defs><rect x="${n(x)}" y="${n(y)}" width="${n(w)}" height="${n(h)}" fill="url(#shadeX)" mask="url(#shadeMask)" opacity="${n(amp/251)}"/>`;}
function button(label,x,y,w,black=false,h=36){return path(rounded(x,y,w,h,h/2),black?'#19191a':'#e8e7eb')+text(label,x+w/2,y+h/2+4,12.5,black?'white':'#151515','SemiBold','middle');}
export function scene(s){if(s.crossfade!==undefined)return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="720" viewBox="0 0 1080 720">${scene(s.from)}<g opacity="${n(s.crossfade)}">${scene(s.to).replaceAll('id="','id="reset-').replaceAll('url(#','url(#reset-')}</g></svg>`;const i=s.frame,day=s.day??15,month=s.month??9,year=s.year??2026,status=s.status??'Paid',date=new Date(Date.UTC(year,month-1,Math.round(day))),dateLabel=date.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}),ink=s.ink??'#cb3031',q=s.stamp,base=s.base,b=s.bg;let out=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="720" viewBox="0 0 1080 720"><defs><linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">${b.map((v,j)=>`<stop offset="${j/(b.length-1)}" stop-color="rgb(${v.map(Math.round).join(',')})"/>`).join('')}</linearGradient><linearGradient id="face" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#fff"/><stop offset="1" stop-color="rgb(${(s.faceBottom||[244,243,246]).map(Math.round).join(',')})"/></linearGradient><linearGradient id="body" gradientUnits="userSpaceOnUse" x1="0" y1="${q?q[4]+1:0}" x2="0" y2="${base?base[3]-Math.max(.35,Math.min(14,.25+(base[3]-q[4])*.105))-1:1}">${(s.wallColors||[[247,246,249],[206,204,212]]).map((v,j,a)=>`<stop offset="${j/(a.length-1)}" stop-color="rgb(${v.map(Math.round).join(',')})"/>`).join('')}</linearGradient><filter id="faceSoft" x="-10%" y="-10%" width="120%" height="120%"><feGaussianBlur stdDeviation=".38"/></filter><filter id="paperShadow" x="-50%" y="-30%" width="200%" height="180%"><feDropShadow dx="0" dy="14" stdDeviation="16" flood-opacity=".075"/></filter><filter id="groundShadow" x="-100%" y="-200%" width="300%" height="500%"><feGaussianBlur stdDeviation="${s.shadowBlur??20}"/></filter><filter id="buttonShadow" x="-100%" y="-100%" width="300%" height="300%"><feDropShadow dx="0" dy="9" stdDeviation="9" flood-opacity=".12"/></filter><filter id="wheelSoft"><feGaussianBlur stdDeviation="2.5"/></filter><filter id="initialShadow" x="-60%" y="-40%" width="220%" height="240%"><feDropShadow dx="10" dy="48" stdDeviation="35" flood-opacity=".095"/><feDropShadow dx="0" dy="3" stdDeviation="2" flood-opacity=".06"/></filter></defs><rect width="1080" height="720" fill="url(#bg)"/>`;
 if(s.paper)out+=`<g opacity="${s.paperOpacity??1}" filter="url(#paperShadow)">${invoice(s.paper,i>=199,day,s.ink?ink:'#d6504d',month,year,status)}</g>`;
 const header=s.header??0;if(header>0){const y=(i<150?0:-39)+(s.headerY||0),title=`<g transform="translate(540 0) scale(.95 1) translate(-540 0)">${text('Invoice FUI-0067',540,119,27,'#19191a','Bold','middle')}</g>`,kicker=text('NORTHWIND PTY LTD  ·  $1,572.50',540,87,9,'#777','Medium','middle',null,1.3);if(i<150)out+=`<g opacity="${n(header)}" transform="translate(0 ${y})">${kicker}${title}${text("Choose the payment date. It's printed on the invoice and saved to its history.",540,143,13,'#707074','Regular','middle')}</g>`;else out+=`<g opacity="${n(header)}" transform="translate(0 ${y})">${title}</g><g opacity="${n(s.finalKicker??1)}" transform="translate(0 ${-39+(s.finalKickerY||0)})">${kicker}</g><g opacity="${n(s.finalCaption??1)}" transform="translate(0 ${-39+(s.finalCaptionY||0)})">${text(`Marked as ${status.toLowerCase()} on ${dateLabel}`,546,143,13,'#666','Regular','middle')}${path(circle(390,138,3),'#cc3031')}</g>`;}

 if(q){if(i<132)out+=physicalShadow([560,410,230,155,19,4]);if(i>=132)out+=physicalShadow(s.shadowFit);out+=`<g ${i<132?'filter="url(#initialShadow)"':''}>${stamp(q,base,day,ink,month,year,status)}</g>`;}
 if(s.form>0){out+=`<defs><filter id="formSoft" x="-20%" y="-20%" width="140%" height="160%"><feGaussianBlur stdDeviation="${s.formBlur||0}"/></filter></defs><g opacity="${s.form}" transform="translate(0 ${s.formY??0})" filter="url(#formSoft)">${text(s.mode==='live'?dateLabel:`${i<55?'Sunday, 13':i<84?'Monday, 14':'Tuesday, 15'} September 2026`,540,503,12.5,'#111','SemiBold','middle')}${path(rounded(306,527,255,36,7),'#dedde1')}${path(rounded([307,359,433,515][['Paid','Received','Approved','Due'].indexOf(status)],529,[50,74,82,45][['Paid','Received','Approved','Due'].indexOf(status)],32,5),'white')}${text('Paid',332,549,10.5,'#111','Medium','middle')}${text('Received',395,549,10.5,'#555','Regular','middle')}${text('Approved',473,549,10.5,'#555','Regular','middle')}${text('Due',535,549,10.5,'#555','Regular','middle')}<path d="M579 534V556" stroke="#d4d3d7"/>${['#cc3031','#2464d6','#20945f','#7846d5','#353538'].map((col,j)=>path(circle(614+j*36,545,9),col)).join('')}${path(circle(614+36*Math.max(0,['#cb3031','#2464d6','#20945f','#7846d5','#353538'].indexOf(ink)),545,12.5),'none',null,`stroke="${s.ink??'#cc3031'}" stroke-width="1.5"`)}<g transform="translate(540 609) scale(${(s.markScale||[1,1]).join(' ')}) translate(-540 -609)" filter="url(#buttonShadow)">${button(`Mark as ${status.toLowerCase()}`,464,588,152,true,42)}</g>${text('or press Enter',540,650,10,'#999','Regular','middle')}</g>`;}
 if(s.confirm>0||s.confirmPaper>0){const label=text(`Marked as ${status.toLowerCase()}  ·  ${Math.round(day)} ${date.toLocaleDateString('en-GB',{month:'short',timeZone:'UTC'})} ${year}`,482,668,12.5,'#424247','Medium','middle');out+=`<defs><filter id="confirmationSoft" x="-10%" y="-30%" width="120%" height="160%"><feGaussianBlur stdDeviation="${s.confirmBlur||0}"/></filter></defs><g transform="translate(0 ${s.confirmY??0})"><g opacity="${s.confirmPaper}" transform="translate(0 ${(s.confirmShellY??s.confirmY??0)-(s.confirmY??0)})" filter="url(#buttonShadow)">${path(rounded(351,640,378,48,24),'#f9f9f9')}</g><g opacity="${s.confirm}">${path(circle(371,664,3.5),ink)}</g><g filter="url(#confirmationSoft)"><g opacity="${s.confirmLabel??s.confirm}">${label}</g><g opacity="${s.confirmUndo??s.confirm}">${button('Undo',584,648,64,false,33)}</g><g opacity="${s.confirmDone??s.confirm}">${button('Done',657,648,65,true,33)}</g></g></g>`;}
 if(s.finalButtons>0)out+=`<g opacity="${s.finalButtons}" transform="translate(0 ${s.finalButtonsY||0})">${button('Download PDF',415,653,128,false)}${button('Next invoice',551,653,114,true)}</g>`;

 if(s.cursor&&s.cursor[3]>.004){const [cx,cy,r,op]=s.cursor;out+=`<g opacity="${n(op)}"><circle cx="${n(cx)}" cy="${n(cy+3)}" r="${n(r)}" fill="black" opacity=".1" filter="url(#wheelSoft)"/><circle cx="${n(cx)}" cy="${n(cy)}" r="${n(r)}" fill="#888" fill-opacity=".17" stroke="white" stroke-opacity=".82" stroke-width="1.4"/></g>`;}return out+'</svg>';
}
