import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import crypto from 'node:crypto';
import {stateAt,renderSVG,DURATION,FPS,track} from '../motion.js';
import {ASSETS} from '../assets.js';
import {createPlayer} from '../controller.js';
import {runAdapterTests} from './adapter.test.mjs';
const results=[];
function test(name,fn){fn();results.push({name,status:'pass'});}
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
test('150 reference-time samples cover exactly 7.50 s',()=>assert.equal(DURATION*FPS,150));
test('Time clamps correctly',()=>{assert.equal(stateAt(-1).t,0);assert.equal(stateAt(100).t,7.5);});
test('Nonfinite input is safe',()=>assert.equal(stateAt(NaN).t,0));
test('Opening count holds before descent',()=>assert.equal(stateAt(.15).countY,139));
test('Count reaches final anchor at 550 ms',()=>assert.equal(stateAt(.55).countY,224));
test('Character is absent before 700 ms',()=>assert.equal(stateAt(.65).alpha,0));
test('Character is fully visible at 850 ms',()=>assert.equal(stateAt(.85).alpha,1));
test('Anticipation visibly squashes body',()=>{assert.ok(stateAt(1.75).sx>1);assert.ok(stateAt(1.75).sy<.8);});
test('Jump precedes charge and rises above starting pose',()=>{assert.ok(stateAt(2.3).y<stateAt(1.2).y);assert.equal(stateAt(2.3).charge,0);});
test('Charge uses bounded measured transition timing',()=>{assert.equal(stateAt(3.7).charge,.42);assert.equal(stateAt(3.8).charge,1);});
test('Hands lift during the celebration',()=>assert.ok(stateAt(4).arm>120));
test('Starburst expands then clears',()=>{assert.ok(stateAt(3.9).burst>.5);assert.equal(stateAt(4.75).burst,0);});
test('Landing squat resolves by final hold',()=>{assert.ok(stateAt(5.5).sy<.8);assert.equal(stateAt(6.2).sy,1);});
test('Completion controls fade between 5.65 and 5.95 s',()=>{assert.equal(stateAt(5.65).controls,0);assert.equal(stateAt(5.95).controls,1);});
test('Reduced motion uses final static state',()=>assert.equal(renderSVG(0,{reducedMotion:true}),renderSVG(7.5)));
test('All 150 source-time SVG samples are deterministic',()=>{for(let i=0;i<150;i++)assert.equal(renderSVG(i/20),renderSVG(i/20));});
test('750 subframe samples have valid finite SVG state',()=>{for(let i=0;i<=750;i++)assert.ok(!/NaN|Infinity|undefined/.test(renderSVG(i/100)));});
test('Runtime contains no former brand title or artwork geometry',()=>{const s=fs.readFileSync(path.join(root,'motion.js'),'utf8');assert.ok(!/Duo|Duolingo|fullWing|fireOwl|greenOwl|bodyPath/.test(s));});
test('Exactly eight genuine source components are used',()=>assert.equal(Object.keys(ASSETS).length,8));
test('All bundled component hashes match manifest and embedded bytes',()=>{const m=JSON.parse(fs.readFileSync(path.join(root,'assets/manifest.json'),'utf8'));for(const f of m.files){const b=fs.readFileSync(path.join(root,'assets',f.filename));assert.equal(crypto.createHash('sha256').update(b).digest('hex'),f.sha256);assert.deepEqual(Buffer.from(ASSETS[f.filename].url.split(',')[1],'base64'),b);assert.equal(f.modified_source_bytes,false);assert.equal(f.license,'CC0 1.0');}});
test('Bundled original license names creator, pack and CC0',()=>{const s=fs.readFileSync(path.join(root,'assets/Kenney-License.txt'),'utf8');assert.ok(s.includes('Monster Builder Pack'));assert.ok(s.includes('Kenney'));assert.ok(s.includes('CC0'));});
test('SVG images are embedded actual source parts, never fetched remotely',()=>{const svg=renderSVG(4);assert.ok(svg.includes('data:image/png;base64,'));assert.ok(!/href="https?:/.test(svg));});
test('Interpolation endpoints are bounded',()=>{assert.equal(track(-1,[[0,3],[1,4]]),3);assert.equal(track(2,[[0,3],[1,4]]),4);});
let stamp=0,id=0,queue=new Map(),snapshots=[];
const p=createPlayer({now:()=>stamp,requestFrame:cb=>{queue.set(++id,cb);return id;},cancelFrame:i=>queue.delete(i),onFrame:(t,s)=>snapshots.push([t,s])});
const advance=ms=>{stamp=ms;const work=[...queue.values()];queue.clear();work.forEach(cb=>cb(ms));};
test('Starts stopped at zero',()=>{assert.equal(p.getState().time,0);assert.equal(p.getState().playing,false);});
test('Playback advances against monotonic time',()=>{p.play();advance(1000);assert.equal(p.getState().time,1);assert.equal(queue.size,1);});
test('Rapid replay cancels earlier frame callbacks',()=>{const stale=[...queue.values()][0];p.replay();p.replay();stale(3000);assert.equal(p.getState().time,0);assert.equal(queue.size,1);});
test('Paused state schedules no animation work',()=>{p.pause();assert.equal(queue.size,0);assert.equal(p.getState().playing,false);});
test('Scrub clamps, preserves paused state',()=>{p.seek(3.8);assert.equal(p.getState().time,3.8);assert.equal(p.getState().playing,false);p.seek(-5);assert.equal(p.getState().time,0);});
test('End stops exactly at 7.50 s',()=>{p.play();advance(10000);assert.equal(p.getState().time,7.5);assert.equal(p.getState().playing,false);assert.equal(queue.size,0);});
test('Play from end restarts sequence',()=>{p.play();assert.equal(p.getState().time,0);assert.equal(p.getState().playing,true);});
test('Toggling reduced motion cancels active replay',()=>{p.setReducedMotion(true);assert.equal(p.getState().time,7.5);assert.equal(queue.size,0);p.replay();assert.equal(queue.size,0);assert.equal(p.getState().playing,false);});
test('Reduced motion cannot be bypassed through seek',()=>{p.seek(0);assert.equal(p.getState().time,7.5);});
test('Disabling reduced motion returns to stopped opening',()=>{p.setReducedMotion(false);assert.equal(p.getState().time,0);assert.equal(p.getState().playing,false);});
test('Speed changes preserve time and are bounded',()=>{p.seek(2);p.setSpeed(2);assert.equal(p.getState().time,2);assert.equal(p.getState().speed,2);p.setSpeed(999);assert.equal(p.getState().speed,2);});
test('Destroy cancels all queued callbacks',()=>{p.play();p.destroy();assert.equal(queue.size,0);assert.equal(p.getState().playing,false);});
runAdapterTests(test);
console.log(JSON.stringify({passed:results.length,failed:0,browserQA:'Not run; renderer, injected-clock controller and simulated DOM adapter tests only',results},null,2));
