const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawnSync}=require('node:child_process');
const {raster}=require('./raster.cjs'),Scene=require('./scene.js'),Data=require('./motion-data.js'),sharp=require('sharp');
sharp.concurrency(1);sharp.cache(false);
const args=process.argv.slice(2),out=path.resolve(args[0]||'export'),encodeOnly=args.includes('--encode-only'),renderOnly=args.includes('--render-only'),limitAt=args.indexOf('--limit'),limit=limitAt>=0?Number(args[limitAt+1]):Infinity;
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),readJSON=p=>JSON.parse(fs.readFileSync(p,'utf8'));
function inputs(){const result={};for(const name of['scene.js','model.js','motion-data.js','pointer.js','raster.cjs','fonts.conf',...fs.readdirSync(path.join(__dirname,'assets')).filter(x=>x.endsWith('.ttf')).map(x=>'assets/'+x)])result[name]=sha(fs.readFileSync(path.join(__dirname,name)));return result;}
const timeline=Data.pts.map((t,i)=>({index:i,kind:'native',sourceIndex:i,ticks:Math.round(t*60000)}));for(let i=0;i<120;i++)timeline.push({index:timeline.length,kind:'authored-return',sourceIndex:null,ticks:Math.round(Data.duration*60000)+i*1000});for(const row of timeline){row.pts=row.ticks/60000;row.file='frames/'+String(row.index).padStart(5,'0')+'.png';}
function run(command,commandArgs){if(command==='ffmpeg')commandArgs=['-hide_banner','-filter_threads','1','-filter_complex_threads','1',...commandArgs];const p=spawnSync(command,commandArgs,{encoding:'utf8',maxBuffer:16*1024*1024});if(p.status!==0)throw Error(`${command} failed (${p.status}): ${p.stderr||p.error||''}`);return p.stdout;}
function concat(rows,extraLast=false){const lines=['ffconcat version 1.0'];for(let i=0;i<rows.length;i++){const row=rows[i],next=rows[i+1]?.ticks??Math.round(Scene.DURATION*60000);lines.push(`file '${row.file}'`,'option framerate 60000',`duration ${((Math.round(next*1e6/60000)-Math.round(row.ticks*1e6/60000))/1e6).toFixed(6)}`);}if(extraLast)lines.push(`file '${rows.at(-1).file}'`,'option framerate 60000','duration 0.016666667');return lines.join('\n')+'\n';}
(async()=>{
 fs.mkdirSync(path.join(out,'frames'),{recursive:true});const bindingPath=path.join(out,'frame-bindings.json');let binding;
 if(!encodeOnly){
  if(fs.existsSync(bindingPath))throw Error('Use a new output directory for a new render.');const code=inputs(),frames=[];
  for(const row of timeline.slice(0,limit)){const state=Scene.observed(row.pts);if(row.kind==='native'&&state.index!==row.sourceIndex)throw Error('Native timestamp/index mismatch at '+row.index);const svg=Scene.render(state,2),png=await raster(state,{scale:2}),rgba=await sharp(png).ensureAlpha().raw().toBuffer();fs.writeFileSync(path.join(out,row.file),png);frames.push({...row,svgSHA256:sha(Buffer.from(svg)),pngSHA256:sha(png),rgbaSHA256:sha(rgba)});if(row.index%24===0)console.log(JSON.stringify({rendered:row.index+1,total:timeline.length}));}
  if(JSON.stringify(inputs())!==JSON.stringify(code))throw Error('Visual inputs changed during rendering.');binding={case:'new100-041',kind:'offline SVG raster; not browser execution',sourceSHA256:'f76d21c21660ee2420283446f11cb2dea90e401fd157cb1e7207207d983bf00d',nativeCount:Data.nativeCount,authoredCount:120,width:3024,height:1896,duration:Scene.DURATION,timeBase:'1/60000',complete:frames.length===timeline.length,inputs:code,frames};fs.writeFileSync(bindingPath,JSON.stringify(binding,null,2)+'\n');
 }else binding=readJSON(bindingPath);
 if(renderOnly)return;
 if(!binding.complete||binding.frames.length!==timeline.length)throw Error('A complete native and tail render is required before encoding.');if(JSON.stringify(inputs())!==JSON.stringify(binding.inputs))throw Error('Cached render belongs to different visual inputs.');for(const row of binding.frames)if(sha(fs.readFileSync(path.join(out,row.file)))!==row.pngSHA256)throw Error('Cached frame changed: '+row.file);
 const nativeConcat=path.join(out,'frames.ffconcat'),gifConcat=path.join(out,'gif-frames.ffconcat');fs.writeFileSync(nativeConcat,concat(binding.frames));fs.writeFileSync(gifConcat,concat(binding.frames,true));fs.mkdirSync(path.join(out,'preview'),{recursive:true});const mp4=path.join(out,'preview/full.mp4'),gif=path.join(out,'preview/loop.gif'),palette=path.join(out,'preview/palette.png');if(fs.existsSync(mp4)||fs.existsSync(gif))throw Error('Preview files already exist; use a fresh output directory.');
 run('ffmpeg',['-v','error','-f','concat','-safe','0','-threads','1','-i',nativeConcat,'-fps_mode','vfr','-c:v','libx264','-x264-params','fps=60/1','-preset','medium','-crf','18','-pix_fmt','yuv420p','-threads','2','-enc_time_base','1:60000','-bsf:v','setts=pts=PTS:dts=DTS:duration=1000','-video_track_timescale','60000','-movflags','+faststart',mp4]);
 run('ffmpeg',['-v','error','-f','concat','-safe','0','-threads','1','-i',gifConcat,'-vf','fps=30,scale=1134:711:flags=lanczos,palettegen=max_colors=256:stats_mode=diff','-frames:v','1','-threads','1','-update','1',palette]);
 run('ffmpeg',['-v','error','-f','concat','-safe','0','-threads','1','-i',gifConcat,'-i',palette,'-filter_complex','[0:v]fps=30,scale=1134:711:flags=lanczos[x];[x][1:v]paletteuse=dither=bayer:bayer_scale=3:diff_mode=rectangle','-t',String(Scene.DURATION),'-threads','1','-loop','0',gif]);
 run('ffmpeg',['-v','error','-i',mp4,'-f','null','-']);run('ffmpeg',['-v','error','-i',gif,'-f','null','-']);
 const probe=JSON.parse(run('ffprobe',['-v','error','-select_streams','v:0','-show_entries','frame=best_effort_timestamp_time:stream=width,height,nb_frames,duration:format=duration','-of','json',mp4]));const actual=probe.frames.map(f=>Math.round(Number(f.best_effort_timestamp_time)*60000));if(actual.length!==timeline.length||actual.some((v,i)=>v!==timeline[i].ticks))throw Error('Encoded native/tail timestamps differ from the exact timeline.');const media={sourceCount:Data.nativeCount,authoredCount:120,encodedCount:actual.length,maximumTimestampErrorTicks:0,mp4:{sha256:sha(fs.readFileSync(mp4)),bytes:fs.statSync(mp4).size,probe:probe.streams[0]},gif:{sha256:sha(fs.readFileSync(gif)),bytes:fs.statSync(gif).size},fullMediaDecode:true,browserExecuted:false};fs.writeFileSync(path.join(out,'media-check.json'),JSON.stringify(media,null,2)+'\n');console.log(JSON.stringify(media));
})().catch(error=>{console.error(error.stack);process.exitCode=1;});
