'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),{createCanvas}=require('@napi-rs/canvas'),crypto=require('crypto');
const scene=require('./scene.js'),isHero=scene.phases.length===6;
const out=[];function test(name,fn){fn();out.push({name,passed:true})}
function hash(p,w=900,h=576){let c=createCanvas(w,h);scene.render(c.getContext('2d'),w,h,p);return crypto.createHash('sha256').update(c.toBuffer('image/png')).digest('hex')}
function finite(obj){if(typeof obj==='number')assert(Number.isFinite(obj));else if(Array.isArray(obj))obj.forEach(finite);else if(obj&&typeof obj==='object')Object.values(obj).forEach(finite)}
test('UMD API, finite state, and clamped progress',()=>{assert.equal(scene.duration,7);assert.equal(scene.state(-1).progress,0);assert.equal(scene.state(5).progress,1);assert.equal(scene.state(NaN).progress,0);for(let i=0;i<=100;i++)finite(scene.state(i/100))});
test('Reverse seeking recreates identical pixels',()=>{const before=hash(.55);hash(1);hash(0);assert.equal(hash(.55),before)});
test('Responsive renders at 390×844, 900×576, 1440×900',()=>{for(let [w,h] of [[390,844],[900,576],[1440,900]])for(let p of [0,.2,.4,.6,.8,1])assert(hash(p,w,h).length===64)});
test('Source mechanism endpoints and stagger bounds',()=>{if(isHero){assert.equal(scene.state(0).yaw,0);assert.equal(scene.state(.267).yaw,Math.PI);assert.equal(scene.state(.267).hardwareFrame,42);assert.equal(scene.state(1).environmentFrame,110);assert(scene.state(1).specs.every(x=>x===1));const x=scene.state(.91).specs;assert(x.every((v,i)=>v>=0&&v<=1&&(!i||v<=x[i-1])));assert.equal(scene.state(1).staggerSeconds,.09);assert.equal(scene.state(1).itemDurationSeconds,.3)}else{assert.equal(scene.state(0).imageScale,1.4);assert.equal(scene.state(1).imageScale,1);assert.equal(scene.state(1).headlineY,-.5);assert.equal(scene.state(1).copyOpacity,1)}});
function runtime(reduced=false){
 const target=(extra={})=>Object.assign({events:{},attrs:{},addEventListener(k,fn){(this.events[k]??=[]).push(fn)},removeEventListener(k,fn){this.events[k]=(this.events[k]||[]).filter(x=>x!==fn)},setAttribute(k,v){this.attrs[k]=v},fire(k,x={}){for(let f of this.events[k]||[])f(x)}},extra);
 const cn=createCanvas(900,576),els={},classes=new Set();let scroll=0;const can=target({getContext:()=>cn.getContext('2d'),getBoundingClientRect:()=>({width:900,height:576})});for(let id of ['seek','play','reset','repeat','phase','percent'])els[id]=target({value:0,textContent:'',tagName:id==='seek'?'INPUT':'BUTTON'});
 const track={offsetTop:0,offsetHeight:3500,getBoundingClientRect:()=>({top:-scroll})},mq=target({matches:reduced}),doc=target({querySelector:q=>q==='canvas'?can:track,getElementById:id=>els[id],documentElement:{classList:{toggle(c,on){on?classes.add(c):classes.delete(c)}}},activeElement:{tagName:'BODY'},hidden:false});
 let seq=0,raf=new Map();const win=target({MotionScene:scene,devicePixelRatio:1,innerHeight:576,matchMedia:()=>mq,scrollTo:({top})=>{scroll=top}}),sandbox={window:win,document:doc,ResizeObserver:class{observe(){}disconnect(){}},requestAnimationFrame:fn=>{raf.set(++seq,fn);return seq},cancelAnimationFrame:id=>raf.delete(id),Math,Number};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(__dirname+'/motion.js','utf8'),sandbox);return {win,els,mq,doc,classes,raf,scrollTo(y){scroll=y;win.fire('scroll')},frame(t){let jobs=[...raf.values()];raf.clear();jobs.forEach(fn=>fn(t))}};
}
test('Browser adapter seek, scroll resume, reset, repeat and destroy (DOM harness)',()=>{let r=runtime(),m=r.win.MOTION;assert.equal(m.getState().progress,0);m.setProgress(.65);assert.equal(m.getState().progress,.65);r.scrollTo((3500-576)*.3);assert.equal(m.getState().mode,'scroll');assert(Math.abs(m.getState().progress-.3)<1e-12);r.els.repeat.fire('click');assert.equal(m.getState().repeat,true);r.els.reset.fire('click');assert.equal(m.getState().progress,0);m.play();r.frame(1);r.frame(3501);assert.equal(m.getState().progress,.5);m.pause();assert.equal(m.getState().playing,false);m.destroy();assert.equal(m.getState().destroyed,true);assert.equal(r.win.events.scroll.length,0)});
test('Reduced-motion static fallback and manual inspection (DOM harness)',()=>{let r=runtime(true),m=r.win.MOTION;assert.equal(m.getState().progress,1);assert.equal(m.getState().reducedMotion,true);m.play();assert.equal(m.getState().playing,false);r.scrollTo(600);assert.equal(m.getState().progress,1);m.setProgress(.3);assert.equal(m.getState().progress,.3);assert(r.classes.has('reduced-motion'));m.destroy()});
console.log(JSON.stringify({scene:isHero?'05-hero':'06-parallax',tests:out,limits:'Offline Canvas2D and DOM harness verification. Browser/physical-device QA was not run.'},null,2));
