import {glyphs,unitsPerEm} from './glyphs.mjs';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function observedPose(asset,index){if(!Number.isFinite(index))throw new TypeError('Finite frame required');const frame=clamp(Math.trunc(index),0,asset.frames.length-1),r=asset.frames[frame];return {frame,rings:r.rings,marks:asset.marks.subarray(frame*asset.slots*(asset.stride||4),(frame+1)*asset.slots*(asset.stride||4)),overlay:r.overlay,opacity:1};}
export function offsetPose(asset,control){const s=observedPose(asset,control.frame);if(!control.anchor)return {...s,opacity:control.opacity};const a=control.anchor,ref=observedPose(asset,control.referenceFrame);const rings=s.rings.map((r,k)=>[a.rings[k][0]+r[0]-ref.rings[k][0],a.rings[k][1]+r[1]-ref.rings[k][1]]);const marks=new Float32Array(s.marks.length);for(let j=0;j<marks.length;j+=(asset.stride||4)){marks[j]=s.marks[j];marks[j+1]=clamp(a.marks[j+1]+s.marks[j+1]-ref.marks[j+1],0,255);marks[j+2]=s.marks[j+2];marks[j+3]=clamp(a.marks[j+3]+s.marks[j+3]-ref.marks[j+3],0,255);if(asset.stride===6){marks[j+4]=clamp(a.marks[j+4]+s.marks[j+4]-ref.marks[j+4],0,255);marks[j+5]=clamp(a.marks[j+5]+s.marks[j+5]-ref.marks[j+5],0,255);}}return {frame:s.frame,rings,marks,opacity:1,live:true,overlay:control.pointer?{pointer:{x:control.pointer.x,y:control.pointer.y,kind:'hand'},label:{x:control.pointer.x+22,y:control.pointer.y+24,w:control.label==='RELEASE'?67:114,h:23,text:control.label}}:null};}
export function createScene(Path,makeSurface=null){const surface=makeSurface?makeSurface(1728,1728):null,labelSurface=makeSurface?makeSurface(132,40):null;const paths=new Map(Object.entries(glyphs).map(([ch,g])=>[ch,new Path(g.path)]));const hand=new Path('M-1.2 1 C-1.2 -1 2.2 -1 2.2 1 V9.5 C2.2 7.2 5.5 7.1 5.5 9.5 V11 C5.5 7.4 8.7 7.5 8.7 10 V11.8 C8.7 8.8 13 9.3 13 11.7 V18.7 C13 26.7 1.8 29 -3.1 22 L-7.3 12.7 C-9.4 9.4 -6.3 7.7 -4.2 10.6 L-1.2 16.3 Z');const arrow=new Path('M0 0 L0 21 L5.4 16 L9.7 25 L13.1 23.4 L8.5 14.2 L16 13.8 Z');
 function type(ctx,text,x,baseline,size,color,weight=.2){ctx.fillStyle=color;for(const ch of text){const g=glyphs[ch];if(!g)continue;ctx.save();ctx.translate(x,baseline);ctx.scale(size/unitsPerEm,-size/unitsPerEm);ctx.fill(paths.get(ch));if(weight){ctx.strokeStyle=color;ctx.lineWidth=weight*unitsPerEm/size;ctx.lineJoin='round';ctx.stroke(paths.get(ch));}ctx.restore();x+=g.advance*size/unitsPerEm;}}
 return function draw(target,asset,pose){const ctx=surface?surface.getContext('2d'):target;ctx.resetTransform();ctx.globalAlpha=1;ctx.fillStyle='#1f1f1f';ctx.fillRect(0,0,1728,1728);let slot=0;ctx.save();ctx.globalAlpha=pose.opacity;
  for(let k=0;k<asset.counts.length;k++){const N=asset.counts[k],[r,phase]=pose.rings[k],size=asset.fontSizes[k];for(let j=0;j<N;j++,slot++){const th=phase-j*2*Math.PI/N,x=asset.center[0]+r*Math.cos(th),y=asset.center[1]+r*Math.sin(th);if(x< -40||y< -40||x>1768||y>1768)continue;const p=slot*(asset.stride||4),gs=pose.marks[p]/(asset.scaleDen||200),ga=pose.marks[p+1]/220,dr=pose.marks[p+2]/100,da=pose.marks[p+3]/220;let hover=1;if(pose.live&&pose.overlay?.pointer){const pointer=pose.overlay.pointer,distance=Math.hypot(x-pointer.x,y-pointer.y),h=clamp((distance-70)/70,0,1);hover=h*h*(3-2*h);}const dotAlpha=da+.32*(1-hover)*(1-da);ctx.save();ctx.translate(x,y);ctx.rotate(th-Math.PI/2);ctx.fillStyle='#fff';if(dotAlpha>.002){ctx.globalAlpha=clamp(dotAlpha,0,1)*pose.opacity;ctx.beginPath();ctx.arc(0,0,dr||.75,0,Math.PI*2);ctx.fill();}if(ga>.002&&gs>0){const ch=asset.characters[slot],g=glyphs[ch];if(g){ctx.globalAlpha=clamp(ga,0,1)*pose.opacity*hover;const fs=size*gs;if(asset.stride===6)ctx.translate((pose.marks[p+4]-128)/(asset.offsetDen||20),(pose.marks[p+5]-128)/(asset.offsetDen||20));ctx.translate(0,fs*.31);ctx.scale(fs/unitsPerEm,-fs/unitsPerEm);ctx.translate(-g.advance/2,0);ctx.fill(paths.get(ch));}}ctx.restore();}}
  const o=pose.overlay;if(o?.label){const l=o.label;ctx.globalAlpha=pose.opacity*(l.alpha??1);if(labelSurface){const lc=labelSurface.getContext('2d');lc.resetTransform();lc.globalAlpha=1;lc.clearRect(0,0,132,40);lc.fillStyle='#fff';lc.fillRect(6,6,l.w,l.h);type(lc,l.text,7,22.1,15.54,'#151515');ctx.save();ctx.filter=`blur(${l.blur??.08}px)`;ctx.drawImage(labelSurface,l.x-6,l.y-6);ctx.restore();}else{ctx.fillStyle='#fff';ctx.fillRect(l.x,l.y,l.w,l.h);type(ctx,l.text,l.x+1,l.y+16.1,15.54,'#151515');}}if(o?.pointer){const p=o.pointer;ctx.save();ctx.globalAlpha=pose.opacity;ctx.translate(p.x,p.y);ctx.lineJoin='round';ctx.lineCap='round';if(p.kind==='arrow'){ctx.fillStyle='#101010';ctx.strokeStyle='#eee';ctx.lineWidth=1.5;ctx.fill(arrow);ctx.stroke(arrow);}else{ctx.fillStyle='#fff';ctx.strokeStyle='#101010';ctx.lineWidth=1.7;ctx.fill(hand);ctx.stroke(hand);}ctx.restore();}ctx.restore();if(surface){target.save();target.resetTransform();target.globalAlpha=1;target.filter='none';target.fillStyle='#1f1f1f';target.fillRect(0,0,1728,1728);target.filter='blur(0.4px)';target.drawImage(surface,0,0);target.restore();}
 };
}
