/* Optional local analysis using an authorized external MP4, which is not bundled.
   Outputs contain source pixels and must not be added to the public bundle.
   Never used by the interactive demo. */
const fs=require('fs'),path=require('path'),{createCanvas,loadImage,GlobalFonts}=require('@napi-rs/canvas');const {execFileSync}=require('child_process');const {loadAssets,gifFrom}=require('./render.cjs');const M=require('../src/motion.js');const root=path.join(__dirname,'..');
async function main(){const arg=process.argv[2];if(!arg)throw Error('Pass a local authorized source MP4 path');const reference=path.resolve(arg),out=path.join(root,'evidence'),frames=path.join(out,'comparison-frames'),source=path.join(out,'source-crops');fs.mkdirSync(frames,{recursive:true});fs.mkdirSync(source,{recursive:true});
 // 22 original frames, exact native timestamps: 7.483333…7.833333 s.
 execFileSync('ffmpeg',['-v','error','-y','-i',reference,'-vf',"select='between(n,449,470)',crop=504:386:347:195",'-vsync','0',path.join(source,'%04d.png')]);
 const assets=await loadAssets(),particles=M.makeParticles(),m=M.createModel({width:504,height:386});const estimatedOnset=7.541666667;m.reveal(estimatedOnset*1000,{x:245,y:219});const all=[];
 for(let i=0;i<22;i++){const pts=(449+i)/60,art=createCanvas(504,386);M.renderMedia(art.getContext('2d'),{model:m.sample(pts*1000),time:pts*1000,width:504,height:386,assets,particles,createCanvas});const c=createCanvas(1048,508),g=c.getContext('2d');g.fillStyle='#f0f1ed';g.fillRect(0,0,1048,508);g.font='bold 14px "Study Sans"';g.fillStyle='#34463f';g.fillText('Official Telegram video · source crop',14,24);g.fillText('Independent recreation · original artwork',534,24);g.font='11px "Study Sans"';g.fillStyle='#738478';g.fillText(`Source PTS ${pts.toFixed(3)} s · native frame ${449+i}`,14,45);g.fillText(`Matched relative time · seed 20221230 · shared runtime`,534,45);const s=await loadImage(path.join(source,`${String(i+1).padStart(4,'0')}.png`));g.drawImage(s,14,62);g.drawImage(art,534,62);g.font='11px "Study Sans"';g.fillStyle='#76877a';g.fillText('White ring on the left = tutorial pointer; intentionally omitted on the right.',14,473);g.fillText('Different artwork and stochastic particles: timing/geometry comparison, not pixel-equivalence. Offline render.',14,493);const buffer=c.toBuffer('image/png');fs.writeFileSync(path.join(frames,`${String(i).padStart(4,'0')}.png`),buffer);if([0,4,6,8,10,12,15,21].includes(i)){fs.writeFileSync(path.join(out,`comparison-${449+i}.png`),buffer);all.push({index:i,pts});}}
 // Slow-motion review: retain every original 60 fps frame, play at 15 fps (4× slower).
 gifFrom(frames,path.join(out,'source-comparison-slow.gif'),15);
 const sheet=createCanvas(1048,508*4),sg=sheet.getContext('2d');for(let j=0;j<4;j++){const i=[4,6,8,12][j];sg.drawImage(await loadImage(path.join(frames,`${String(i).padStart(4,'0')}.png`)),0,j*508);}fs.writeFileSync(path.join(out,'source-comparison-contact.png'),sheet.toBuffer('image/png'));
 fs.writeFileSync(path.join(out,'comparison-manifest.json'),JSON.stringify({kind:'source-video crop versus deterministic offline reconstruction',sourceClipFrames:{firstZeroBased:449,lastZeroBased:470},sourceFps:60,comparisonPlaybackFps:15,slowdown:4,estimatedOnsetSeconds:estimatedOnset,onsetIsBracketMidpoint:true,sourceCrop:{x:347,y:195,width:504,height:386},reproductionClick:{x:245,y:219},inheritedLimitations:['No browser rendering/performance verification','Source tutorial touch ring overlaps reveal','Original artwork differs, so whole-image pixel error is not a valid fidelity score','Seeded particles approximate texture and motion, not native trajectories']},null,2));console.log('comparison saved');}
main();
