/* Deterministic offline rendering of the shared interaction runtime; NOT a browser capture. */
const fs=require('fs'),path=require('path'),{execFileSync}=require('child_process');const {createCanvas,loadImage,GlobalFonts}=require('@napi-rs/canvas');GlobalFonts.registerFromPath('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf','Study Sans');GlobalFonts.registerFromPath('/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf','Study Sans');const M=require('../src/motion.js');const root=path.join(__dirname,'..');const Timeline=require('./preview-timeline.cjs');
function rr(g,x,y,w,h,r,fill){g.fillStyle=fill;g.beginPath();g.roundRect(x,y,w,h,r);g.fill();}
function txt(g,s,x,y,size,color,weight='normal'){g.font=`${weight} ${size}px "Study Sans"`;g.fillStyle=color;g.fillText(s,x,y);}
async function loadAssets(){return{clear:await loadImage(path.join(root,'assets/original-still-life.png')),blur:await loadImage(path.join(root,'assets/original-still-life-blurred.png'))};}
function drawPreview({time,model,assets,particles}){const c=createCanvas(640,810),g=c.getContext('2d');const b=g.createLinearGradient(0,0,640,810);b.addColorStop(0,'#e6eeea');b.addColorStop(1,'#f0e8de');g.fillStyle=b;g.fillRect(0,0,640,810);txt(g,'TELEGRAM  /  MEDIA SPOILER',80,42,10,'#557d72','600');txt(g,'A little mystery.',80,90,37,'#2e4840','600');txt(g,'Tap to reveal. The image stays still.',80,116,12,'#778b80');
 g.shadowColor='#4a675124';g.shadowBlur=25;g.shadowOffsetY=12;rr(g,62,142,516,600,22,'#ffffff');g.shadowColor='transparent';g.shadowBlur=0;g.shadowOffsetY=0;
 rr(g,62,205,516,480,0,'#dce6db');for(let y=214;y<625;y+=20)for(let x=72;x<573;x+=20){g.fillStyle='#90aa9a24';g.beginPath();g.arc(x,y,1,0,Math.PI*2);g.fill();}
 rr(g,82,157,34,34,17,'#7aa28f');txt(g,'S',92,181,21,'#ffffff');txt(g,'Studio notes',128,170,13,'#385147','600');txt(g,'Original artwork · motion study',128,186,9,'#97a299');
 rr(g,279,218,82,18,9,'#a5b9ab');txt(g,'Today',304,231,9,'#ffffff');rr(g,80,248,237,32,[11,11,11,3],'#fff');txt(g,'Something for the studio',91,268,11,'#40554a');txt(g,'09:41',282,270,7,'#a7b1a8');
 const media=createCanvas(480,360);M.renderMedia(media.getContext('2d'),{model,time,width:480,height:360,assets,particles,createCanvas});g.drawImage(media,80,286,480,360);
 rr(g,80,646,480,40,[0,0,4,12],'#fff'); // The artwork frame overlaps upward into its source-sized chat card.
 txt(g,'A few things worth waiting for',91,671,12,'#3c5045');txt(g,'09:41  ✓✓',500,672,8,'#84a898');
 // Overlay footer below the media; keeps offline framing explicit and readable.
 rr(g,80,704,77,23,6,'#eef4ed');txt(g,'Hide again',92,719,9,'#648774');rr(g,165,704,51,23,6,'#eef4ed');txt(g,'Reset',178,719,9,'#648774');txt(g,model.phase.toUpperCase(),478,719,8,'#8da293');
 txt(g,'1× · 50 fps · deterministic offline render · shared JS runtime',80,783,10,'#82948a');return c;}
function gifFrom(dir,out,fps){const args=['-v','error','-y','-framerate',String(fps),'-i',path.join(dir,'%04d.png'),'-filter_complex','[0:v]split[a][b];[a]palettegen=max_colors=192:stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=4','-loop','0',out];execFileSync('ffmpeg',args);}
async function main(){const assets=await loadAssets(),particles=M.makeParticles();const dir=path.join(root,'preview/frames');fs.mkdirSync(dir,{recursive:true});const fps=Timeline.fps,count=Timeline.frameCount;const m=M.createModel();m.reveal(Timeline.revealAtMs,Timeline.click);
 for(let i=0;i<count;i++){const time=Timeline.frameTimeMs(i);let model;if(time<Timeline.revealAtMs){model=M.createModel().sample(time);}else if(time>=Timeline.resetAtMs){model=M.createModel().sample(time);}else model=m.sample(time);const c=drawPreview({time,model,assets,particles});fs.writeFileSync(path.join(dir,`${String(i).padStart(4,'0')}.png`),c.toBuffer('image/png'));if(i===0||i===66||i===68||i===75)fs.writeFileSync(path.join(root,'preview',`frame-${i}.png`),c.toBuffer('image/png'));}
 gifFrom(dir,path.join(root,'preview/telegram-media-spoiler.gif'),fps);fs.writeFileSync(path.join(root,'evidence/render-manifest.json'),JSON.stringify({kind:'deterministic offline canvas render',notBrowserCapture:true,runtime:'src/motion.js',fps,frames:count,durationSeconds:count/fps,seed:20221230,revealAtMs:Timeline.revealAtMs,resetAtMs:Timeline.resetAtMs,revealStateEnvelopeMs:M.REVEAL_MS,exportSpeed:1,firstVisibleSampleAfterTriggerMs:1000/120,width:640,height:810},null,2));console.log('Rendered preview/telegram-media-spoiler.gif');}
if(require.main===module)main();module.exports={loadAssets,drawPreview,gifFrom};
