import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{pose,configs,SPEED,PERIOD,ROUTE_START,ROUTE_END}=require('./horse-motion.js');
const html=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
let maxSlip=0,maxGroundError=0,maxBoneError=0,maxReachAdjustment=0,minSupport=4,maxSupport=0,foreMin=180,foreMax=0,pasternMin=Infinity,pasternMax=0;
for(let i=0;i<4000;i++){
 const t=i/100,a=pose(t),b=pose(t+.001);let support=0;
 for(const[id,value]of[...Object.entries(a.transforms),...Object.entries(a.paths)]){assert(html.includes(`id="${id}"`));assert(!/NaN|Infinity/.test(value));}
 for(const c of configs){const l=a.diagnostics.limbs[c.id],m=b.diagnostics.limbs[c.id];if(l.stance){support++;maxGroundError=Math.max(maxGroundError,Math.abs(l.toeWorld[1]-(687+c.ground)));if(c.id.startsWith('front')){foreMin=Math.min(foreMin,180-l.actualFlex);foreMax=Math.max(foreMax,180-l.actualFlex);}}
 if(l.stance&&m.stance&&Math.abs(b.diagnostics.x-a.diagnostics.x)<1)maxSlip=Math.max(maxSlip,Math.abs(l.toeWorld[0]-m.toeWorld[0]));
 const lengths=[Math.hypot(l.joint[0]-l.hip[0],l.joint[1]-l.hip[1]),Math.hypot(l.knee[0]-l.joint[0],l.knee[1]-l.joint[1]),Math.hypot(l.fetlock[0]-l.knee[0],l.fetlock[1]-l.knee[1]),Math.hypot(l.coronary[0]-l.fetlock[0],l.coronary[1]-l.fetlock[1])];
 lengths.forEach((v,j)=>maxBoneError=Math.max(maxBoneError,Math.abs(v-l.lengths[j])));pasternMin=Math.min(pasternMin,lengths[3]);pasternMax=Math.max(pasternMax,lengths[3]);maxReachAdjustment=Math.max(maxReachAdjustment,Math.abs(l.reachAdjustment));assert(l.coronary[0]>l.fetlock[0]);}
 minSupport=Math.min(minSupport,support);maxSupport=Math.max(maxSupport,support);
}
let maxAngularDerivativeJump=0;const eps=1e-6;
for(const c of configs)for(const q of [0,.5,.6,.635,.72,.82,.93]){const t=(q+c.onset+1)*PERIOD;const angle=dt=>pose(t+dt).diagnostics.limbs[c.id].hoofAngle;const left=(angle(0)-angle(-eps))/eps,right=(angle(eps)-angle(0))/eps;maxAngularDerivativeJump=Math.max(maxAngularDerivativeJump,Math.abs(left-right));}
assert(maxSlip<1e-8);assert(maxGroundError<1e-8);assert(maxBoneError<1e-7);assert(maxReachAdjustment<1e-6);assert.equal(minSupport,2);assert.equal(maxSupport,3);assert(foreMin>159);assert(maxAngularDerivativeJump<.1);assert(Math.abs(pose(7).diagnostics.x-pose(0).diagnostics.x-7*SPEED)<1e-8);assert(ROUTE_START+155<0);assert(ROUTE_END+8>1671);
function runtime(prefersReduced){const nodes=new Map([...Object.keys(pose(0).transforms),...Object.keys(pose(0).paths)].map(id=>[id,{attributes:{},setAttribute(k,v){this.attributes[k]=v}}]));const button={textContent:'',attributes:{},listeners:{},setAttribute(k,v){this.attributes[k]=v},addEventListener(k,v){this.listeners[k]=v}};const document={hidden:false,listeners:{},getElementById(id){return nodes.get(id)},querySelector(selector){return selector==='#motion-toggle'?button:null},addEventListener(k,v){this.listeners[k]=v}};const window={listeners:{},addEventListener(k,v){this.listeners[k]=v}};const media={matches:prefersReduced,listeners:{},addEventListener(k,v){this.listeners[k]=v}};let seq=0;const pending=new Map();const requestAnimationFrame=fn=>{pending.set(++seq,fn);return seq};const cancelAnimationFrame=id=>pending.delete(id);vm.runInNewContext(fs.readFileSync(new URL('./horse-motion.js',import.meta.url),'utf8'),{document,window,matchMedia:()=>media,requestAnimationFrame,cancelAnimationFrame});function advance(t){const[id,fn]=pending.entries().next().value;pending.delete(id);fn(t)}return{nodes,button,document,window,media,pending,advance};}
const r=runtime(false);assert.equal(r.button.textContent,'Pause motion');r.advance(1000);r.advance(1020);const x=r.nodes.get('horse-travel').attributes.transform;r.button.listeners.click();r.advance(1040);assert.equal(r.nodes.get('horse-travel').attributes.transform,x);r.button.listeners.click();r.advance(1060);r.advance(1080);assert.notEqual(r.nodes.get('horse-travel').attributes.transform,x);r.window.listeners.pagehide();assert.equal(r.pending.size,0);r.window.listeners.pageshow();assert.equal(r.pending.size,1);r.media.listeners.change({matches:true});assert.equal(r.button.textContent,'Play motion');assert.equal(runtime(true).button.textContent,'Play motion');
const report={period_seconds:PERIOD,speed_pixels_per_second:SPEED,preview_travel_pixels:7*SPEED,max_stance_toe_slip_pixels:maxSlip,max_ground_error_pixels:maxGroundError,max_fixed_link_length_error_pixels:maxBoneError,explicit_pastern_length_range:[pasternMin,pasternMax],loaded_fore_carpus_degrees:[foreMin,foreMax],max_hoof_angular_velocity_discontinuity_degrees_per_second:maxAngularDerivativeJump,max_ik_reach_adjustment:maxReachAdjustment,supporting_hooves:[minSupport,maxSupport],runtime_browser_tested:false,meaning:'Structural regression checks; not a certification of natural-looking motion.'};fs.writeFileSync(new URL('./preview/kinematic-checks.json',import.meta.url),JSON.stringify(report,null,2));console.log('PASS',report);
