const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function mount(reduced=false){
 const nodes={},docEvents={},timers=[];for(const id of ['stage','art','paper','undo','play','status','replay'])nodes[id]={style:{},hidden:false,textContent:'',innerHTML:'',events:{},captures:new Set(),getBoundingClientRect:()=>({left:0,top:0,width:1920,height:1360}),addEventListener(type,fn){this.events[type]=fn;},setPointerCapture(id){this.captures.add(id)},hasPointerCapture(id){return this.captures.has(id)},releasePointerCapture(id){this.captures.delete(id)}};
 const document={getElementById:id=>nodes[id],addEventListener:(name,fn)=>docEvents[name]=fn};let clock=0;const context={document,matchMedia:()=>({matches:reduced}),performance:{now:()=>clock},requestAnimationFrame:fn=>timers.push(fn),TossScene:require('../scene.js'),TossModel:require('../model.js')};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../app.js'),'utf8'),context);
 const fire=(id,type,extra={})=>nodes[id].events[type]?.({pointerId:1,clientX:938,clientY:936,timeStamp:clock,preventDefault(){},...extra});const tick=(seconds)=>{for(let i=0;i<seconds*20;i++){clock+=50;timers.shift()?.(clock)}};
 return {nodes,fire,tick,key:key=>docEvents.keydown({key})};
}
test('Escape and pointer cancellation release capture and reject stale pointer events',()=>{const m=mount();m.fire('paper','pointerdown');m.fire('paper','pointermove',{clientX:1150,clientY:940,timeStamp:40});assert.equal(m.nodes.paper.captures.size,1);m.key('Escape');assert.equal(m.nodes.paper.captures.size,0);const html=m.nodes.art.innerHTML;m.fire('paper','pointerup');m.fire('paper','pointermove',{clientX:0,clientY:0,timeStamp:80});assert.equal(m.nodes.art.innerHTML,html);m.fire('paper','pointerdown');m.fire('paper','pointercancel');assert.equal(m.nodes.paper.captures.size,0);assert.equal(m.nodes.status.textContent,'Drag or flick the example file');});
test('Replay during a drag clears capture before resuming the recorded sequence',()=>{const m=mount();m.fire('paper','pointerdown');m.fire('replay','click');assert.equal(m.nodes.paper.captures.size,0);assert.equal(m.nodes.status.textContent,'Recorded motion');const html=m.nodes.art.innerHTML;m.fire('paper','pointermove',{clientX:100,clientY:100,timeStamp:30});assert.equal(m.nodes.art.innerHTML,html);m.tick(.2);assert.notEqual(m.nodes.art.innerHTML,html);});
test('Reduced motion pauses autoplay and keyboard delete plus Undo remain usable repeatedly',()=>{const m=mount(true);assert.equal(m.nodes.play.textContent,'Play');const first=m.nodes.art.innerHTML;m.tick(.5);assert.equal(m.nodes.art.innerHTML,first);for(let i=0;i<2;i++){m.fire('paper','keydown',{key:'Enter'});assert.equal(m.nodes.status.textContent,'Example file deleted');assert.equal(m.nodes.undo.hidden,false);m.fire('undo','click');assert.equal(m.nodes.paper.hidden,false);assert.equal(m.nodes.undo.hidden,true);assert.equal(m.nodes.status.textContent,'Drag or flick the example file');}});
