const test=require('node:test'),assert=require('node:assert/strict'),{Router,POLICIES}=require('../model.js'),Scene=require('../scene.js'),Data=require('../motion-data.js');
test('fallback source selection swaps a conflicting destination',()=>{const m=new Router();m.selectSource(1);assert.equal(m.source,1);assert.equal(m.destination,0);m.selectSource(0);assert.equal(m.source,0);assert.equal(m.destination,1);});
test('disabled fallback closes the menu and prevents selection',()=>{const m=new Router();m.toggleMenu();assert.equal(m.menu,true);m.toggleFallback();assert.equal(m.menu,false);m.selectSource(1);assert.equal(m.source,0);m.toggleMenu();assert.equal(m.menu,false);});
test('policy and fallback changes track the live baseline',()=>{const m=new Router();assert.equal(m.dirty,false);m.selectPolicy(0);assert.equal(m.dirty,true);m.deploy();assert.equal(m.dirty,false);m.toggleFallback();assert.equal(m.dirty,true);m.reset();assert.equal(m.dirty,false);});
test('invalid values leave valid controls unchanged',()=>{const m=new Router();m.selectPolicy(8);m.selectSource(-1);m.hoverRoute(9);assert.equal(m.policy,1);assert.equal(m.source,0);assert.equal(m.hover,-1);assert.ok(POLICIES.every(p=>p.shares.reduce((a,b)=>a+b)===100));});
test('all source timestamps have a finite independent SVG scene',()=>{assert.equal(Data.pts.length,1142);for(const [i,t] of Data.pts.entries()){const s=Scene.observed(t);assert.equal(s.index,i);assert.ok(!/NaN|undefined|Infinity/.test(Scene.render(s)));assert.ok(Math.abs(s.shares.reduce((a,b)=>a+b)-100)<.0001);}});

test('recorded control selections preserve the paired fallback invariant',()=>{for(const [i,t] of Data.pts.entries()){const s=Scene.observed(t);assert.notEqual(s.source,s.destination);assert.equal(s.fallback,i>=678&&i<714?0:1);assert.ok(s.menu>=0&&s.menu<=1);assert.ok(s.knobX>=508&&s.knobX<=524);}});
test('fast policy selection and allocation count-up remain independently timed',()=>{const s=Scene.observed(Data.pts[140]);assert.ok(s.thumbGeometry.x<801);assert.ok(s.price>.0026);assert.ok(s.shares[0]>6);});

test('authored return preserves the last recorded pose and reaches the exact first scene',()=>{const a=Scene.observed(Data.pts.at(-1)),b=Scene.observed(0),start=Scene.observed(Data.duration),end=Scene.observed(Scene.DURATION-.02);assert.equal(start.authored,true);assert.equal(start.requests,a.requests);assert.equal(end.requests,b.requests);assert.deepEqual(end.heads,b.heads);assert.deepEqual(end.cursor,b.cursor);assert.equal(Scene.render(end),Scene.render(b));});

test('brief late row hovers dim other routes without removing their moving particles',()=>{for(const [i,selected] of [[895,3],[1071,0]]){const s=Scene.observed(Data.pts[i]);for(let k=0;k<4;k++){assert.ok(s.heads[k].length>=4);if(k===selected){assert.equal(s.routeAlpha[k],1);assert.equal(s.rowAlpha[k],1);}else{assert.ok(s.routeAlpha[k]>.33&&s.routeAlpha[k]<.6);assert.ok(s.rowAlpha[k]>s.routeAlpha[k]&&s.rowAlpha[k]<.7);}}}});
