(async function(){'use strict';const M=window.CircleMotion,S=window.CircleScene,$=id=>document.getElementById(id),canvas=$('scene'),ctx=canvas.getContext('2d'),media=matchMedia('(prefers-reduced-motion: reduce)');let system=media.matches,manual=false,s=M.initial(system,'2026'),raf=0,last=0,pointer=null;
function paint(){S.draw(ctx,M.pose(s));canvas.dataset.mode=s.mode;canvas.dataset.progress=s.p.toFixed(6);canvas.dataset.pts=s.pts.toFixed(6);canvas.dataset.target=s.target||'';canvas.dataset.playing=String(s.playing);$('timeline').min=s.profile==='2026'?'4.6':'3.5';$('timeline').max=s.profile==='2026'?'7.1':'6.7';$('timeline').value=s.pts;$('select').textContent=s.profile==='2026'?'Select outfit ↗':'Select sunglasses ↗';$('profile').value=s.profile;$('time').textContent=s.pts.toFixed(2)+' s';$('replay').disabled=s.reduced;$('timeline').disabled=s.reduced;$('reduced').checked=s.reduced;$('reduced').disabled=system;$('reduced-note').hidden=!s.reduced;$('status').textContent=s.message;}
function schedule(){if(raf||document.hidden||!M.active(s))return;last=performance.now();raf=requestAnimationFrame(frame);}function frame(now){raf=0;s=M.tick(s,(now-last)/1000);last=now;paint();if(M.active(s)&&!document.hidden)raf=requestAnimationFrame(frame);}function dispatch(e){s=M.action(s,e);if(raf&&!M.active(s)){cancelAnimationFrame(raf);raf=0;}paint();schedule();}
const point=e=>M.pointFromClient(e.clientX,e.clientY,canvas.getBoundingClientRect());
canvas.addEventListener('pointerdown',e=>{if(e.button!==0||pointer!==null)return;const p=point(e);if(p.x<58||p.x>342||p.y<110||p.y>575)return;pointer=e.pointerId;canvas.setPointerCapture(pointer);e.preventDefault();canvas.focus({preventScroll:true});dispatch({type:'start',point:p});});
canvas.addEventListener('pointermove',e=>{if(e.pointerId!==pointer)return;for(const q of (e.getCoalescedEvents?e.getCoalescedEvents():[e]))dispatch({type:'move',point:point(q)});});
function end(e,cancel=false){if(e.pointerId!==pointer)return;pointer=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);dispatch({type:cancel?'cancel':'release'});}
canvas.addEventListener('pointerup',e=>end(e));canvas.addEventListener('pointercancel',e=>end(e,true));canvas.addEventListener('lostpointercapture',e=>{if(pointer!==null)end(e,true);});
$('profile').addEventListener('change',e=>dispatch({type:'profile',profile:e.target.value}));$('select').addEventListener('click',()=>dispatch({type:'select'}));$('replay').addEventListener('click',()=>dispatch({type:'replay'}));$('cancel').addEventListener('click',()=>dispatch({type:'cancel'}));$('reverse').addEventListener('click',()=>dispatch({type:'reverse'}));$('timeline').addEventListener('input',e=>dispatch({type:'seek',pts:Number(e.target.value)}));$('reduced').addEventListener('change',e=>{manual=e.target.checked;dispatch({type:'reduced',enabled:system||manual});});
document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='Escape'){const held=pointer;pointer=null;if(held!==null&&canvas.hasPointerCapture(held))canvas.releasePointerCapture(held);e.preventDefault();dispatch({type:'cancel'});return;}if(e.target.closest('input,button,a,textarea,select,[contenteditable]'))return;if(e.key==='Enter'||e.code==='Space'){e.preventDefault();dispatch({type:'select'});}if(e.key.toLowerCase()==='r')dispatch({type:'replay'});});
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(raf)cancelAnimationFrame(raf);raf=0;if(pointer!==null){const held=pointer;pointer=null;if(canvas.hasPointerCapture(held))canvas.releasePointerCapture(held);dispatch({type:'cancel'});}}else schedule();});media.addEventListener('change',e=>{system=e.matches;dispatch({type:'reduced',enabled:system||manual});});
await Promise.all([document.fonts.load('400 12px "Study Sans"'),document.fonts.load('500 12px "Study Sans"')]);const url=new URLSearchParams(location.search);if(url.get('profile')==='2024')s=M.action(s,{type:'profile',profile:'2024'});if(url.has('pts')&&!system)s=M.action(s,{type:'seek',pts:Number(url.get('pts'))});paint();
})();
