/* Measured visual layers, shared by browser and offline export. No external assets. */
(function(root,factory){if(typeof module==='object')module.exports=factory();else root.CircleAppearance=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';const clamp=(v,a=0,b=1)=>Math.min(b,Math.max(a,v));
function roundedSdf(x,y,b){const r=Math.min(b.r,b.w/2,b.h/2),qx=Math.abs(x-b.cx)-(b.w/2-r),qy=Math.abs(y-b.cy)-(b.h/2-r);return Math.hypot(Math.max(qx,0),Math.max(qy,0))+Math.min(Math.max(qx,qy),0)-r;}
function gaussianKernel(sigma){const radius=Math.ceil(sigma*3),out=[];let sum=0;for(let i=-radius;i<=radius;i++){const w=Math.exp(-i*i/(2*sigma*sigma));out.push(w);sum+=w;}return {radius,weights:out.map(v=>v/sum)};}
function blurRGBA(src,w,h,sigma){const {radius:r,weights:k}=gaussianKernel(sigma),tmp=new Float32Array(src.length),out=new Uint8ClampedArray(src.length);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const o=(y*w+x)*4;for(let dx=-r;dx<=r;dx++){const q=(y*w+clamp(x+dx,0,w-1))*4,weight=k[dx+r];for(let c=0;c<3;c++)tmp[o+c]+=src[q+c]*weight;}}for(let y=0;y<h;y++)for(let x=0;x<w;x++){const o=(y*w+x)*4;for(let c=0;c<3;c++){let value=0;for(let dy=-r;dy<=r;dy++){const q=(clamp(y+dy,0,h-1)*w+x)*4;value+=tmp[q+c]*k[dy+r];}out[o+c]=value;}out[o+3]=src[o+3];}return out;}
const colors={tl:[255,209,22],tr:[255,75,69],br:[53,123,252],bl:[62,200,129]};
function colorAt(x,y,b){const u=clamp((x-(b.cx-b.w/2))/b.w),v=clamp((y-(b.cy-b.h/2))/b.h);return [0,1,2].map(i=>(colors.tl[i]*(1-u)+colors.tr[i]*u)*(1-v)+(colors.bl[i]*(1-u)+colors.br[i]*u)*v);}
function applyFocus(c,pose){const a=pose.appearance;if(!a||a.focus<=0)return;const b=pose.box,frame=c.getImageData(58,70,284,608),base=new Uint8ClampedArray(frame.data),w=284,h=608;const margin=Math.ceil(a.haloSigma*3+4),left=clamp(Math.floor(b.cx-b.w/2-margin)-58,0,w-1),right=clamp(Math.ceil(b.cx+b.w/2+margin)-58,0,w),top=clamp(Math.floor(b.cy-b.h/2-margin)-70,0,h-1),bottom=clamp(Math.ceil(b.cy+b.h/2+margin)-70,0,h),rw=right-left,rh=bottom-top;
let blurred=null;if(a.softness>0&&rw&&rh){const region=new Uint8ClampedArray(rw*rh*4);for(let y=0;y<rh;y++)region.set(base.subarray(((top+y)*w+left)*4,((top+y)*w+right)*4),y*rw*4);blurred=blurRGBA(region,rw,rh,a.softness);}
for(let y=0;y<h;y++)for(let x=0;x<w;x++){const o=(y*w+x)*4,gx=x+58+.5,gy=y+70+.5,d=roundedSdf(gx,gy,b),outside=clamp((d+.6)/1.2),veil=a.dim*a.focus*outside,gauss=Math.exp(-(Math.max(d,0)**2)/(2*a.haloSigma*a.haloSigma)),blurMix=a.focus*a.softMix*gauss*outside,glow=a.halo*a.focus*Math.exp(-(d*d)/(2*a.haloSigma*a.haloSigma))*outside;let color=a.colored?colorAt(gx,gy,b):[229,233,219];
if(roundedSdf(gx,gy,{cx:200,cy:360,w:284,h:636,r:30})>0)continue;for(let channel=0;channel<3;channel++){let v=base[o+channel];if(blurred&&x>=left&&x<right&&y>=top&&y<bottom)v=v*(1-blurMix)+blurred[((y-top)*rw+x-left)*4+channel]*blurMix;v=v*(1-veil)+(a.veilColor?.[channel]||0)*veil;frame.data[o+channel]=v+(color[channel]-v)*glow;}}
c.putImageData(frame,58,70);}
function drawAura(c,x,y,{strength=1,sigma=15,color=[242,242,225]}={}){if(strength<=0)return;const radius=sigma*3.4,g=c.createRadialGradient(x,y,0,x,y,radius);for(const q of [0,.15,.3,.45,.6,.8,1]){const alpha=strength*Math.exp(-((q*radius)**2)/(2*sigma*sigma));g.addColorStop(q,`rgba(${color.join(',')},${q===1?0:alpha})`);}c.fillStyle=g;c.fillRect(x-radius,y-radius,radius*2,radius*2);}
return {roundedSdf,gaussianKernel,blurRGBA,colorAt,applyFocus,drawAura};
});
