(function(){'use strict';
const scene=window.MotionScene,stage=document.getElementById('stage'),canvas=document.getElementById('scene'),ctx=canvas.getContext('2d'),tablist=document.getElementById('tabs'),workspaceControls=document.getElementById('workspace-controls'),dotlist=document.getElementById('dots'),panel=document.getElementById('panel'),status=document.getElementById('status'),previous=document.getElementById('previous'),next=document.getElementById('next'),modeAI=document.getElementById('mode-ai'),modeWorkspace=document.getElementById('mode-workspace'),replay=document.getElementById('replay'),media=window.matchMedia('(prefers-reduced-motion: reduce)');
let mode='ai',progress=0,options={},current=scene.state(0),raf=0,generation=0,destroyed=false,announced='',ready=false;const listeners=[];
function listen(el,type,fn){el.addEventListener(type,fn);listeners.push(()=>el.removeEventListener(type,fn));}function cancel(){generation++;if(raf)cancelAnimationFrame(raf);raf=0;}
function keyHandler(i){return e=>{let target;if(e.key==='ArrowRight'||e.key==='ArrowDown')target=(i+1)%3;if(e.key==='ArrowLeft'||e.key==='ArrowUp')target=(i+2)%3;if(e.key==='Home')target=0;if(e.key==='End')target=2;if(target!==undefined){e.preventDefault();(mode==='ai'?tabs:dots)[target].focus();animateTab(target);}};}
function makeButtons(data,parent,prefix){return data.map((item,i)=>{const b=document.createElement('button');b.type='button';b.className='hit';b.id=prefix+i;b.setAttribute('role','tab');b.setAttribute('aria-controls','panel');b.setAttribute('aria-label',item.name);b.textContent=item.name;parent.appendChild(b);listen(b,'click',()=>animateTab(i));listen(b,'keydown',keyHandler(i));return b;});}
const tabs=makeButtons(scene.tabs,tablist,'ai-tab-'),dots=makeButtons(scene.workspaces,dotlist,'workspace-');
function position(el,box){Object.assign(el.style,{left:box.x+'px',top:box.y+'px',width:box.width+'px',height:box.height+'px'});}
function paint(){if(destroyed)return;const w=stage.clientWidth,L=scene.layout(ctx,w,stage.clientHeight,mode);stage.style.height=w<700?Math.ceil(L.height)+'px':'';const h=stage.clientHeight,dpr=Math.min(window.devicePixelRatio||1,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);current=scene.render(ctx,w,h,progress,{...options,mode});const boxes=scene.layout(ctx,w,h,mode);tablist.hidden=mode!=='ai';workspaceControls.hidden=mode!=='workspace';modeAI.setAttribute('aria-pressed',String(mode==='ai'));modeWorkspace.setAttribute('aria-pressed',String(mode==='workspace'));for(const [group,hit]of[[tabs,boxes.hit],[dots,boxes.dots]])group.forEach((b,i)=>{position(b,hit[i]);b.setAttribute('aria-selected',String(i===current.tab));b.tabIndex=i===current.tab?0:-1;});position(previous,boxes.previous);position(next,boxes.next);const selected=(mode==='ai'?tabs:dots)[current.tab];panel.setAttribute('aria-labelledby',selected.id);const key=mode+current.tab;if(announced!==key){announced=key;document.getElementById('panel-title').textContent=current.caption;document.getElementById('description').textContent=current.description;status.textContent=current.caption+'. '+current.description;}}
// Freeze only interrupted content; normal reference playback keeps its original renderer path.
function snapshotFrame(){const copy=document.createElement('canvas');copy.width=ctx.canvas.width;copy.height=ctx.canvas.height;copy.getContext('2d').drawImage(ctx.canvas,0,0);return copy;}
function setTab(index,p=1){if(destroyed)return;const old=current.tab;cancel();options={tab:((Math.floor(Number(index)||0)%3)+3)%3,previousTab:old,transitionProgress:media.matches?1:scene.clamp(p)};paint();}
function animateTab(index){index=((index%3)+3)%3;if(destroyed||index===current.tab)return;const old=current.tab,previousFrame=!media.matches&&current.progress<1?snapshotFrame():null;cancel();options={tab:index,previousTab:old,transitionProgress:media.matches?1:0};if(previousFrame)options.previousFrame=previousFrame;paint();if(media.matches)return;const token=generation,start=performance.now();function frame(now){if(destroyed||generation!==token)return;options.transitionProgress=scene.clamp((now-start)/(scene.transitionDuration*1000));paint();if(options.transitionProgress<1)raf=requestAnimationFrame(frame);else{raf=0;delete options.previousFrame;}}raf=requestAnimationFrame(frame);}
function setProgress(p){if(destroyed)return;cancel();progress=scene.clamp(p);options={};if(media.matches){const s=scene.state(progress,{mode});options={tab:s.tab,previousTab:s.tab,transitionProgress:1};}paint();}
function setMode(value){if(destroyed)return;cancel();mode=value==='workspace'?'workspace':'ai';progress=0;options={tab:0,previousTab:0,transitionProgress:1};paint();}
function play(){if(destroyed)return;cancel();if(media.matches){setProgress(1);return;}progress=0;options={};const token=generation,start=performance.now();function frame(now){if(destroyed||generation!==token)return;progress=scene.clamp((now-start)/(scene.duration*1000));paint();if(progress<1)raf=requestAnimationFrame(frame);else raf=0;}paint();raf=requestAnimationFrame(frame);}
listen(previous,'click',()=>animateTab(current.tab+2));listen(next,'click',()=>animateTab(current.tab+1));listen(modeAI,'click',()=>setMode('ai'));listen(modeWorkspace,'click',()=>setMode('workspace'));listen(replay,'click',play);listen(window,'resize',paint);listen(media,'change',()=>{if(media.matches)setTab(current.tab,1);else paint();});
const assetReady=Promise.all(scene.assetNames.map(file=>new Promise(resolve=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>resolve(null);image.src='assets/'+file;}))).then(images=>{scene.setImages(images);ready=images.every(Boolean);if(!ready)status.textContent='Some original illustrations could not be loaded. The gallery controls remain available.';paint();});
const fontReady=document.fonts?Promise.all([document.fonts.load('400 18px "Motion Sans"'),document.fonts.load('600 28px "Motion Sans"')]).then(paint):Promise.resolve();
window.MOTION={setProgress,setTab,setMode,next:()=>animateTab(current.tab+1),previous:()=>animateTab(current.tab+2),seek:seconds=>setProgress(Number(seconds)/scene.duration),play,ready:Promise.all([assetReady,fontReady]),getState:()=>({...current,timelineProgress:progress,playing:!!raf,reducedMotion:media.matches,assetsReady:ready,destroyed}),destroy(){if(destroyed)return;cancel();options={};listeners.forEach(fn=>fn());destroyed=true;}};paint();
})();
