/* Original SVG illustrations. Shared deterministic browser/offline renderer. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.MotionScene=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const duration=3.433,transitionDuration=.5,assetNames=['ai-creative.svg','ai-models.svg','ai-features.svg','workspace-quiet.svg','workspace-shared.svg','workspace-night.svg'];let images=[];
const tabs=[{name:'AI apps',caption:'Atelier · Explore a world of possibilities',description:'An original concept-art workspace with a floating observatory.'},{name:'AI models',caption:'Vector · Make room for a bigger idea',description:'An original local-model playground with a network visualization.'},{name:'AI features in apps',caption:'Fieldwork · Build what comes next',description:'An original code editor and generative cartographic poster.'}];
const workspaces=[{name:'Quiet studio',caption:'A place to find your focus',description:'An original sunlit single-desk studio with a sculptural plant.'},{name:'Shared studio',caption:'Better ideas, together',description:'An original two-display collaborative workspace.'},{name:'After hours',caption:'Stay in your flow',description:'An original dusk workspace in blue and lavender.'}];
const clamp=v=>Math.max(0,Math.min(1,Number.isFinite(+v)?+v:0));
const ease=v=>(v=clamp(v))<.5?4*v*v*v:1-Math.pow(-2*v+2,3)/2;
function state(progress,options={}){let tab,previousTab,p;const mode=options.mode==='workspace'?'workspace':'ai';if(Number.isInteger(options.tab)){tab=((options.tab%3)+3)%3;previousTab=Number.isInteger(options.previousTab)?((options.previousTab%3)+3)%3:0;p=options.transitionProgress===undefined?1:clamp(options.transitionProgress);}else{const time=clamp(progress)*duration;const first=mode==='ai'?.325:.6,second=mode==='ai'?1.854:1.9;if(time<first){tab=0;previousTab=0;p=1;}else if(time<second){tab=1;previousTab=0;p=clamp((time-first)/transitionDuration);}else{tab=2;previousTab=1;p=clamp((time-second)/transitionDuration);}}const alpha=ease(p),selected=(mode==='ai'?tabs:workspaces)[tab];return {mode,tab,previousTab,progress:p,alpha,caption:selected.caption,description:selected.description};}
function font(ctx,size,weight=400){ctx.font=weight+' '+size+'px "Motion Sans"';}
function rr(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
function layout(ctx,w,h,mode='ai'){const narrow=w<700,S=narrow?1:w/1188;let monitor,tabsY,captionY;
if(narrow){monitor={x:20,y:102,w:w-40,h:(w-40)*.563};captionY=monitor.y+monitor.h+118;tabsY=captionY+80;}else{monitor={x:244*S,y:39*S,w:694*S,h:403*S};captionY=589*S;tabsY=684*S;}
const size=narrow?(w<360?15:17):28*S,gap=narrow?(w<360?13:19):29*S;font(ctx,size,600);const widths=tabs.map(t=>ctx.measureText(t.name).width),total=widths.reduce((a,b)=>a+b,0)+gap*2;let x=(w-total)/2;const hit=widths.map((width,i)=>{const box={x,y:tabsY-9*S,width,height:45*S,index:i};x+=width+gap;return box;});
const picture=narrow?{x:16,y:84,w:w-32,h:390}:{x:24*S,y:52*S,w:w-48*S,h:650*S};const cy=picture.y+picture.h/2;
return {narrow,S,monitor,captionY,tabsY,tabSize:size,hit,picture,previous:{x:picture.x+16*S,y:cy-26*S,width:52*S,height:52*S},next:{x:picture.x+picture.w-68*S,y:cy-26*S,width:52*S,height:52*S},dots:[0,1,2].map(i=>({x:w/2+(i-1)*32*S-16*S,y:(narrow?picture.y+picture.h+17:714*S),width:32*S,height:32*S,index:i})),height:narrow?Math.max(tabsY+94,592):761*S};}
function drawAsset(ctx,index,x,y,w,h,cover=false){if(images[index]){const image=images[index];if(cover){const scale=Math.max(w/image.width,h/image.height),sw=w/scale,sh=h/scale;ctx.drawImage(image,(image.width-sw)/2,(image.height-sh)/2,sw,sh,x,y,w,h);}else ctx.drawImage(image,x,y,w,h);return;}ctx.fillStyle='#28283b';ctx.fillRect(x,y,w,h);ctx.fillStyle='#cbc9e3';font(ctx,Math.max(12,w*.028),400);ctx.fillText('Loading original illustration…',x+w*.12,y+h*.5);}
function metal(ctx,x,y,w,h){const g=ctx.createLinearGradient(x,y,x+w,y);g.addColorStop(0,'#909696');g.addColorStop(.03,'#e5e6e3');g.addColorStop(.45,'#b9bdba');g.addColorStop(.84,'#e1e3e0');g.addColorStop(1,'#8e9391');ctx.fillStyle=g;rr(ctx,x,y,w,h,Math.min(12,w*.03));}
function drawMonitor(ctx,L,s){const m=L.monitor,S=L.narrow?m.w/694:L.S;const stand={x:m.x+m.w*.375,y:m.y+m.h-3*S,w:m.w*.249,h:124*S};metal(ctx,stand.x,stand.y,stand.w,stand.h);ctx.fillStyle='#818685';rr(ctx,stand.x,stand.y+stand.h-5*S,stand.w,5*S,2*S);metal(ctx,stand.x-3*S,stand.y+stand.h-6*S,stand.w+6*S,5*S);
const box={x:m.x+m.w*.68,y:m.y+m.h+24*S,w:214*S,h:98*S};ctx.save();ctx.shadowColor='rgba(20,20,20,.18)';ctx.shadowBlur=8*S;ctx.shadowOffsetY=5*S;metal(ctx,box.x,box.y,box.w,box.h);ctx.restore();ctx.fillStyle='#545b5b';rr(ctx,box.x+27*S,box.y+box.h-7*S,box.w-54*S,7*S,4*S);ctx.fillStyle='#303839';for(let i=0;i<2;i++)rr(ctx,box.x+(32+i*17)*S,box.y+74*S,3*S,10*S,1*S);rr(ctx,box.x+66*S,box.y+79*S,34*S,3*S,1*S);
ctx.fillStyle='#101214';rr(ctx,m.x,m.y,m.w,m.h,5*S);ctx.fillStyle='#474b4c';rr(ctx,m.x+2*S,m.y+2*S,m.w-4*S,m.h-4*S,4*S);ctx.fillStyle='#08090b';rr(ctx,m.x+4*S,m.y+4*S,m.w-8*S,m.h-8*S,3*S);
const screen={x:m.x+13*S,y:m.y+13*S,w:m.w-26*S,h:m.h-30*S};drawAsset(ctx,s.previousTab,screen.x,screen.y,screen.w,screen.h);ctx.save();ctx.globalAlpha=s.alpha;drawAsset(ctx,s.tab,screen.x,screen.y,screen.w,screen.h);ctx.restore();ctx.fillStyle='#323b3c';ctx.beginPath();ctx.arc(m.x+m.w/2,m.y+6*S,1.6*S,0,Math.PI*2);ctx.fill();
}
function centered(ctx,text,x,y,color,size,weight=400){ctx.fillStyle=color;font(ctx,size,weight);ctx.textAlign='center';ctx.fillText(text,x,y);ctx.textAlign='left';}
function drawCaption(ctx,w,L,s){ctx.save();if(s.previousTab!==s.tab){ctx.globalAlpha=1-s.alpha;centered(ctx,tabs[s.previousTab].caption,w/2,L.captionY,'#87878b',L.narrow?13:18*L.S,600);}ctx.globalAlpha=s.previousTab===s.tab?1:s.alpha;centered(ctx,tabs[s.tab].caption,w/2,L.captionY,'#87878b',L.narrow?13:18*L.S,600);ctx.restore();}
function drawWorkspace(ctx,w,L,s){const b=L.picture;ctx.save();ctx.beginPath();ctx.roundRect(b.x,b.y,b.w,b.h,26*L.S);ctx.clip();drawAsset(ctx,3+s.previousTab,b.x,b.y,b.w,b.h,true);ctx.globalAlpha=s.alpha;drawAsset(ctx,3+s.tab,b.x,b.y,b.w,b.h,true);ctx.restore();
for(const [key,dir] of [['previous',-1],['next',1]]){const r=L[key],cx=r.x+r.width/2,cy=r.y+r.height/2;ctx.fillStyle='rgba(250,250,250,.65)';ctx.beginPath();ctx.arc(cx,cy,r.width/2,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(cx-dir*3*L.S,cy-9*L.S);ctx.lineTo(cx+dir*5*L.S,cy);ctx.lineTo(cx-dir*3*L.S,cy+9*L.S);ctx.strokeStyle='#656567';ctx.lineWidth=3*L.S;ctx.stroke();}
L.dots.forEach((d,i)=>{ctx.fillStyle=i===s.tab?'#77777b':'#d6d6d9';ctx.beginPath();ctx.arc(d.x+d.width/2,d.y+d.height/2,4*L.S,0,Math.PI*2);ctx.fill();});}
function restoreInterrupted(ctx,w,h,L,s,frame){
  if(!frame)return;
  ctx.save();ctx.beginPath();
  if(s.mode==='ai')ctx.rect(0,0,w,L.tabsY-9*L.S);
  else{const b=L.picture;ctx.roundRect(b.x,b.y,b.w,b.h,26*L.S);}
  ctx.clip();ctx.globalAlpha=1-s.alpha;ctx.drawImage(frame,0,0,w,h);ctx.restore();
}
function render(ctx,w,h,progress,options={}){const s=state(progress,options),L=layout(ctx,w,h,s.mode),visual=options.previousFrame?{...s,previousTab:s.tab,alpha:1}:s;ctx.save();ctx.clearRect(0,0,w,h);ctx.fillStyle='#fafafa';ctx.fillRect(0,0,w,h);ctx.textBaseline='top';if(s.mode==='ai'){drawMonitor(ctx,L,visual);drawCaption(ctx,w,L,visual);restoreInterrupted(ctx,w,h,L,s,options.previousFrame);font(ctx,L.tabSize,600);L.hit.forEach((b,i)=>{ctx.fillStyle=i===s.tab?'#242426':'#78787b';ctx.fillText(tabs[i].name,b.x,L.tabsY);});const x=L.hit[0].x,end=L.hit[2].x+L.hit[2].width;ctx.fillStyle='#d6d6d9';ctx.fillRect(x,L.tabsY+43*L.S,end-x,1);ctx.fillStyle='#46464a';const selected=L.hit[s.tab];ctx.fillRect(selected.x,L.tabsY+43*L.S,selected.width,1);centered(ctx,'Original vector artwork · Interaction study',w/2,L.tabsY+63*L.S,'#9b9b9f',L.narrow?10:11*L.S);}else{drawWorkspace(ctx,w,L,visual);restoreInterrupted(ctx,w,h,L,s,options.previousFrame);}
ctx.fillStyle='#fafafa';ctx.fillRect(0,0,w,L.narrow?54:51*L.S);ctx.fillStyle='#d9d9dc';ctx.fillRect(0,L.narrow?53:51*L.S,w,1);ctx.fillStyle='#202023';font(ctx,L.narrow?15:20*L.S,600);ctx.fillText('FORM / STUDIO',L.narrow?24:96*L.S,L.narrow?19:18*L.S);ctx.textAlign='right';font(ctx,L.narrow?10:12*L.S);ctx.fillStyle='#74747a';ctx.fillText(s.mode==='ai'?'MOTION STUDY 07':workspaces[s.tab].name.toUpperCase()+' · '+(s.tab+1)+' / 3',w-(L.narrow?24:96*L.S),L.narrow?22:22*L.S);ctx.textAlign='left';ctx.restore();return s;}
return {render,state,layout,tabs,workspaces,duration,transitionDuration,clamp,ease,assetNames,setImages:loaded=>{images=loaded;},get assetsReady(){return images.length===6&&images.every(Boolean);}};
});
