(function(root,factory){if(typeof module==='object')module.exports=factory(require('./motion-data.js'));else root.Scene=factory(root.LabelMotion);})(this,function(Motion){'use strict';
const W=1080,H=1028,DURATION=14,ASSETS={},STILLS={labels:.2,filtered:1.2,color:3.4,loading:7.1,created:9.1};const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),ease=x=>{x=clamp(x);return x*x*(3-2*x)},mix=(a,b,p)=>a+(b-a)*p;
const colors=[['Red','#e81437'],['Orange','#ef5f05'],['Green','#0fe752'],['Blue','#307df7'],['Violet','#883df6'],['Pink','#e51797']];
const defaults=[['API','#e91337'],['Backend','#0fcfa5'],['Documentation','#ec0454'],['Frontend','#ef5f05'],['Security','#0db0ee'],['Testing','#e8b608']];
function initial(){return{query:'',mode:'labels',color:4,hover:0,selected:[],labels:defaults.map(v=>[...v]),generation:0,createdName:null};}
function fuzzy(text,q){let j=0;text=text.toLowerCase();for(const c of q.toLowerCase()){j=text.indexOf(c,j);if(j<0)return false;j++;}return true;}function rows(s){if(s.recorded?.visibleRows)return s.recorded.visibleRows.map(r=>s.labels.find(x=>x[0]===r.name)||defaults.find(x=>x[0]===r.name));return s.mode==='colors'||s.mode==='creating'?colors:s.labels.filter(x=>fuzzy(x[0],s.query));}
function action(s,a){switch(a.type){case'reset':return{...initial(),generation:s.generation+1};case'query':return s.mode==='creating'?s:{...s,query:String(a.value).slice(0,32),mode:'labels',hover:-1,createdName:null};case'hover':return{...s,hover:a.value,color:s.mode==='colors'?clamp(a.value,0,5):s.color};case'create':return s.query.trim()&&!s.labels.some(x=>x[0].toLowerCase()===s.query.trim().toLowerCase())?{...s,mode:'colors',hover:-1,createdName:s.query.trim(),generation:s.generation+1}:s;case'color':return s.mode==='colors'?{...s,color:clamp(a.value,0,5),mode:'creating',hover:-1}:s;case'complete':{if(s.mode!=='creating'||a.generation!==s.generation)return s;let name=s.createdName;return{...s,labels:[...s.labels,[name,colors[s.color][1]]].sort((a,b)=>a[0].localeCompare(b[0])),selected:[...s.selected,name],mode:'created',query:'',hover:-1};}case'settle':return s.mode==='created'&&a.generation===s.generation?{...s,mode:'labels',createdName:null}:s;case'toggle':return s.mode==='creating'?s:{...s,selected:s.selected.includes(a.name)?s.selected.filter(x=>x!==a.name):[...s.selected,a.name]};case'back':return{...s,mode:'labels',createdName:null,generation:s.generation+1};default:return s;}}
function timeline(t){t=((t%DURATION)+DURATION)%DURATION;let time=Math.min(t,Motion.duration-1/60),fade=1;if(t>=11.75&&t<12.1)fade=1-ease((t-11.75)/.35);if(t>=12.1){time=0;fade=ease((t-12.1)/.4);}let lo=0,hi=Motion.rows.length-1;while(lo<hi){const m=Math.ceil((lo+hi)/2);if(Motion.rows[m].t<=time+0.000001)lo=m;else hi=m-1;}const r=Motion.rows[lo];let s=initial();s.query=r.query;s.hover=s.query?-1:0;if(time>=1.566667){s=action(s,{type:'create'});s.color=r.color;s.hover=r.color;if(time>=6.016667){s=action(s,{type:'color',value:4});s.loadingTime=time-6.016667;if(time>=8.05){s=action(s,{type:'complete',generation:s.generation});s.successTime=time-8.05;if(time>=10.15)s=action(s,{type:'settle',generation:s.generation});}}}s.recorded=r;s.visualHeader=r.headerReveal;s.visualHeight=r.bodyHeight;s.panelWidth=r.width;if(r.frame<94)s.hover=r.visibleRows?.length?0:-1;s.fade=fade;return s;}
function metrics(s){const count=rows(s).length,create=s.mode==='labels'&&s.query.trim()&&!s.labels.some(x=>x[0].toLowerCase()===s.query.trim().toLowerCase()),header=['colors','creating','created'].includes(s.mode),body=s.recorded?.bodyHeight??99+count*80+(create?80:0)+24,width=s.panelWidth??(header||s.createdName||s.labels.length>6||s.query.length>4?633:562);return{count,create,header,body,width,top:244,headerY:167};}
function rr(c,x,y,w,h,r,fill,stroke){c.beginPath();c.roundRect(x,y,w,h,r);if(fill){c.fillStyle=fill;c.fill();}if(stroke){c.lineWidth=1.8;c.strokeStyle=stroke;c.stroke();}}
function text(c,s,x,y,size=33,col='#252525',weight=400,align='left'){c.font=`${weight} ${size}px "Replica Sans"`;c.fillStyle=col;c.textAlign=align;c.textBaseline='alphabetic';c.fillText(s,x,y);}
function tag(c,x,y){c.beginPath();c.moveTo(x-14,y);c.lineTo(x-7,y-8);c.quadraticCurveTo(x-6,y-9,x-3,y-9);c.lineTo(x+10,y-9);c.quadraticCurveTo(x+14,y-9,x+14,y-5);c.lineTo(x+14,y+5);c.quadraticCurveTo(x+14,y+9,x+10,y+9);c.lineTo(x-3,y+9);c.quadraticCurveTo(x-6,y+9,x-7,y+8);c.closePath();c.strokeStyle='#777';c.lineWidth=2.7;c.stroke();c.beginPath();c.arc(x-5,y,2,0,7);c.fillStyle='#777';c.fill();}
function dots(c,x,y,t,success){let k=0;const points=[];for(let iy=-3;iy<=3;iy++)for(let ix=-3;ix<=3;ix++)if(Math.abs(ix)+Math.abs(iy)<=3)points.push([ix*5,iy*5]);const check=[[-11,1],[-7,5],[-3,9],[1,5],[5,1],[9,-3],[13,-7]];for(const [dx,dy]of points){const phase=(Math.atan2(dy,dx)+Math.PI*2)%(Math.PI*2),wave=(Math.cos(phase-t*6)+1)/2;const close=check.some(([px,py])=>Math.hypot(px-dx,py-dy)<4);c.fillStyle=`rgba(25,25,25,${success===undefined?.15+.85*Math.pow(wave,5):mix(.15+.85*Math.pow(wave,5),close?1:.11,ease(success/.5))})`;c.fillRect(x+dx-1.55,y+dy-1.55,3.1,3.1);k++;}if(success!==undefined&&success>.3){c.save();c.globalAlpha=ease((success-.3)/.45);c.beginPath();c.moveTo(x-10,y+1);c.lineTo(x-3,y+8);c.lineTo(x+12,y-9);c.lineCap='round';c.lineJoin='round';c.strokeStyle='#171717';c.lineWidth=2.5;c.stroke();c.restore();}}
function paint(c,t,assets={},manual){const s=manual||timeline(t),m=metrics(s),rowsList=rows(s),h=s.visualHeight??m.body,head=s.visualHeader??(m.header?1:0),width=s.visualWidth??m.width,cam=s.recorded?.camera||s.cameraOverride||[1,0,0],shift=clamp((cam[0]-1)/.4)*2;c.clearRect(0,0,W,H);c.fillStyle='#fbfbfb';c.fillRect(0,0,W,H);c.save();c.globalAlpha=s.fade??1;c.translate(cam[1],cam[2]);c.scale(cam[0],cam[0]);
// A continuous backing shell lets the breadcrumb rise out of the label picker.
if(head>0){c.save();const blur=s.recorded?.headerBlur||0;if(blur>.01)c.filter=`blur(${blur}px)`;rr(c,228,244-81.5*head,width,h+81.5*head,40,'#f4f4f4','#e0e0e0');const frame=s.recorded?.frame,cy=s.recorded?.headerDot?.[1]??204+81.5*(1-head),cx=s.recorded?.headerDot?.[0];c.globalAlpha*=head;const tagAlpha=s.recorded?s.recorded.tagOpacity:s.mode==='colors'?1:0;if(tagAlpha>0){c.save();c.globalAlpha*=tagAlpha;tag(c,294,cy);c.restore();}if(s.recorded){for(const [x,y,size,alpha]of s.recorded.dots||[]){c.fillStyle=`rgba(25,25,25,${alpha})`;c.fillRect(x-size/2,y-size/2,size,size);}}else if(s.mode==='creating')dots(c,294,cy,s.loadingTime??t,undefined);else if(s.mode==='created')dots(c,294,cy,t,s.successTime??1);
let word=s.mode==='creating'?'Creating':s.mode==='created'?'Created':'Create',from=null,u=1;if(frame>=361&&frame<375){word='Creating';from='Create';u=ease((frame-361)/14);}else if(frame>=483&&frame<495){word='Created';from='Creating';u=ease((frame-483)/12);}const drawWord=(v,a,x=335.5)=>{c.save();c.globalAlpha*=a;text(c,v,x,cy+11,29.5,'#828282');c.restore();};if(from){drawWord('Creat',1);c.font='400 29.5px "Replica Sans"';const sx=335.5+c.measureText('Creat').width,first=frame<400,oldAlpha=first?1-clamp((frame-361)/7):([1,.8521,.6464,.4201,.141][frame-483]??0),newAlpha=first?ease((frame-365)/8):clamp((frame-487.5)/6);if(first)drawWord('e',oldAlpha,sx);else for(const ch of 'ing')drawWord(ch,oldAlpha,sx);drawWord(first?'ing':'ed',newAlpha,sx);}else drawWord(word,1);c.font='400 29.5px "Replica Sans"';const tw=from?mix(c.measureText(from).width,c.measureText(word).width,u):c.measureText(word).width,dx=cx??363.6+tw;c.fillStyle=colors[s.color][1];c.beginPath();c.arc(dx,cy,10,0,7);c.fill();text(c,s.createdName||'Database',dx+21.4,cy+11,29.5,'#111');c.restore();}
c.save();c.shadowColor=`rgba(25,25,25,${.35*(s.fade??1)})`;c.shadowBlur=30;c.shadowOffsetY=22;rr(c,228,244,width,h,24,'#fdfdfd','#dfdfdf');c.restore();c.save();c.beginPath();c.roundRect(228,244,width,h,24);c.clip();const disabled=s.mode==='creating';c.globalAlpha*=s.recorded?s.recorded.alpha:disabled?.476:1;const title=['colors','creating'].includes(s.mode)?'Pick color for label':s.query||'Change labels…';if(s.recorded?.caret){const [cx,cy,cw,ch]=s.recorded.caret;c.fillStyle='#518fdd';c.fillRect(cx,cy,cw,ch);}else if(!s.recorded&&s.focused&&Math.floor(t*2)%2===0){c.font='400 35px "Replica Sans"';c.fillStyle='#518fdd';c.fillRect(268+c.measureText(s.query).width,270,2.5,42);}text(c,title,268,305,35,s.query&&s.mode==='labels'?'#111':'#787878');c.beginPath();c.moveTo(229,342);c.lineTo(228+width-1,342);c.strokeStyle='#e7e7e7';c.lineWidth=1.8;c.stroke();
for(let i=0;i<rowsList.length;i++){const [label,col]=rowsList[i],y=s.recorded?.visibleRows?.[i]?.y??352+shift+i*80.4,selected=s.selected.includes(label),hover=s.hover===i;if(hover||selected)rr(c,239,y,width-22,79,20,'#f4f4f4');if(selected){rr(c,269,y+20,39,39,10,'#161616');c.beginPath();c.moveTo(277,y+41);c.lineTo(285,y+48);c.lineTo(298,y+33);c.strokeStyle='#fff';c.lineWidth=3;c.lineCap='round';c.stroke();}else if(hover&&s.mode==='labels')rr(c,269,y+20,39,39,10,'#f4f4f4','#e3e3e3');c.fillStyle=disabled&&label==='Green'?'#30dd52':col;c.beginPath();c.arc(['colors','creating'].includes(s.mode)?289:350,y+40,12.8,0,7);c.fill();text(c,label,['colors','creating'].includes(s.mode)?329:389,y+53,35,'#161616');}
if(m.create){const y=352+shift+rowsList.length*80.4,hover=s.recorded?.createHover;rr(c,240,y,width-24,79,20,hover?'#f4f4f4':'#fdfdfd');c.beginPath();c.moveTo(277,y+40);c.lineTo(301,y+40);c.moveTo(289,y+28);c.lineTo(289,y+52);c.lineWidth=3;c.lineCap='round';c.strokeStyle=hover?'#151515':'#858585';c.stroke();text(c,'Create new label: ',329,y+53,35,'#161616');const px=329+c.measureText('Create new label: ').width;c.save();c.beginPath();c.rect(px,y+6,Math.max(1,228+width-px-14),65);c.clip();text(c,'"'+s.query+'"',px,y+53,35,'#787878');c.restore();}c.restore();rr(c,136,351,73,73,39,'#f8f8f8');text(c,'+',172,404,47,'#151515',400,'center');c.restore();}
// Reconstruct the reference camera's short shutter trail using independently rendered subframes.
const surfaces=new WeakMap();
function draw(c,t,assets={},manual){const s=manual||timeline(t),r=s.recorded,n=r?.frame;if(n===undefined||!((n>=156&&n<=198)||(n>=623&&n<=654)))return paint(c,t,assets,s);const a=Motion.rows[Math.max(0,n-1)].camera,b=Motion.rows[Math.min(Motion.rows.length-1,n+1)].camera,v=b.map((x,i)=>(x-a[i])/2);if(Math.abs(v[0])*900+Math.max(Math.abs(v[1]),Math.abs(v[2]))<.8)return paint(c,t,assets,s);const mk=()=>{const z=typeof document!=='undefined'?document.createElement('canvas'):new c.canvas.constructor(W,H);z.width=W;z.height=H;if(typeof z.getContext!=='function')throw new Error('Offscreen canvas unavailable');return z;};let layers=surfaces.get(c);if(!layers){try{layers={base:mk(),sample:mk(),levels:Array.from({length:5},mk)};surfaces.set(c,layers);}catch{return paint(c,t,assets,s);}}const bc=layers.base.getContext('2d'),lc=layers.sample.getContext('2d');paint(bc,t,assets,s);for(let i=0;i<16;i++){const offset=(i/15-.5)*.8,cam=r.camera.map((x,j)=>x+offset*v[j]),z=cam[0]/r.camera[0],tx=cam[1]-r.camera[1]*z,ty=cam[2]-r.camera[2]*z;lc.globalAlpha=1;lc.fillStyle='#fbfbfb';lc.fillRect(0,0,W,H);lc.drawImage(layers.base,tx,ty,W*z,H*z);let level=0,k=i;while(k&1){lc.globalAlpha=.5;lc.drawImage(layers.levels[level],0,0);k>>=1;level++;}lc.globalAlpha=1;const dest=layers.levels[level].getContext('2d');dest.globalCompositeOperation='copy';dest.drawImage(layers.sample,0,0);dest.globalCompositeOperation='source-over';}c.save();c.globalAlpha=1;c.globalCompositeOperation='copy';c.drawImage(layers.levels[4],0,0);c.restore();}
return{W,H,FPS:60,DURATION,ASSETS,STILLS,clamp,ease,colors,defaults,initial,rows,metrics,action,timeline,draw};});
