'use strict';
(async function(){await document.fonts.ready;await document.fonts.load('400 16px "Replica Sans"');await document.fonts.load('600 16px "Replica Sans"');await document.fonts.load('400 40px Hand');await document.fonts.load('600 44px Hand');await document.fonts.load('700 48px Hand');await document.fonts.load('400 12px "Replica Mono"');await document.fonts.load('700 14px "Replica Mono"');const c=document.getElementById('canvas'),ctx=c.getContext('2d'),controls=document.getElementById('controls'),status=document.getElementById('status'),reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;let start=performance.now(),manual=reduce?Scene.initial():null,now=0,anim=null,down=null;const targets=[];
function button(label,x,y,w,h,fn){const b=document.createElement('button');b.className='hit';b.setAttribute('aria-label',label);b.style.cssText=`left:${x/Scene.W*100}%;top:${y/Scene.H*100}%;width:${w/Scene.W*100}%;height:${h/Scene.H*100}%`;b.addEventListener('click',fn);controls.append(b);targets.push({b,x,y,w,h});return b;}
function current(){return manual||Scene.timeline(now);}
function step(d){if(anim)return;const q=current(),s={index:q.index,progress:0,direction:q.direction,filter:q.filter,appYOverride:q.recorded?.appY??q.appYOverride??0,cameraOverride:q.recorded?.camera||q.cameraOverride||[1,1,0,0]};if(d<0){manual=Scene.action(s,{type:'step',value:-1});manual.progress=1;anim={at:performance.now(),dir:-1};}else{manual=s;manual.direction=-1;anim={at:performance.now(),dir:1};}status.textContent=d>0?'Next pinned meeting':'Previous pinned meeting';}
button('Previous meeting',659,237,37,45,()=>step(-1));button('Next meeting',699,237,39,45,()=>step(1));button('Reset pinned meetings',347,166,52,54,()=>{manual=Scene.initial();anim=null;});['All','Work','School','Personal'].forEach((value,i)=>button(value+' meetings',350+i*98,730,98,49,()=>{manual=Scene.action(current(),{type:'filter',value});anim=null;status.textContent=value+' meetings';}));
c.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};c.setPointerCapture(e.pointerId);});c.addEventListener('pointerup',e=>{if(!down)return;const dx=e.clientX-down.x,dy=e.clientY-down.y;if(Math.abs(dx)>25&&Math.abs(dx)>Math.abs(dy))step(dx<0?1:-1);down=null;});c.addEventListener('pointercancel',()=>down=null);
document.addEventListener('keydown',e=>{if(e.key==='ArrowRight'){e.preventDefault();step(1);}else if(e.key==='ArrowLeft'){e.preventDefault();step(-1);}else if(e.key==='Escape'){manual=null;anim=null;start=performance.now();}else if(e.code==='Space'&&e.target.tagName!=='BUTTON'){e.preventDefault();if(manual){manual=null;start=performance.now();}else manual={...current(),progress:0};}});
function frame(ts){now=(ts-start)/1000;if(anim){let p=Scene.ease((ts-anim.at)/720);manual.progress=anim.dir===1?p:1-p;if(p>=1){if(anim.dir===1)manual=Scene.action(manual,{type:'step',value:1});else manual.progress=0;anim=null;}}Scene.draw(ctx,now,{},manual);const q=current(),cam=q.recorded?.camera||q.cameraOverride||[1,1,0,0];for(const {b,x,y,w,h}of targets){b.style.left=(x*cam[0]+cam[2])/Scene.W*100+'%';b.style.top=((y+(q.recorded?.appY??q.appYOverride??0))*cam[1]+cam[3])/Scene.H*100+'%';b.style.width=w*cam[0]/Scene.W*100+'%';b.style.height=h*cam[1]/Scene.H*100+'%';}requestAnimationFrame(frame);}requestAnimationFrame(frame);
window.demo={getState:()=>({...current()}),step,reset:()=>{manual=Scene.initial();anim=null;}};})();
