import {scene,reduce,drawState,label,WIDTH,HEIGHT} from './scene.mjs';
const visual=document.querySelector('#visual'),stage=document.querySelector('.stage'),status=document.querySelector('#status'),buttons=[...document.querySelectorAll('.slider')],motion=matchMedia('(prefers-reduced-motion: reduce)');let state=reduce({}, {type:'reset'}),last=null;
function paint(){const s=drawState(state);visual.innerHTML=scene(s);buttons.forEach((b,i)=>{b.setAttribute('aria-valuenow',String(s.values[i]));b.setAttribute('aria-valuetext',label(i,s.values[i]));});}
function action(a){state=reduce(state,a);paint();}
function point(e){const b=stage.getBoundingClientRect();return {x:(e.clientX-b.left)/b.width*WIDTH,y:(e.clientY-b.top)/b.height*HEIGHT};}
buttons.forEach((button,row)=>{button.addEventListener('pointerdown',e=>{if(state.phase==='drag'&&state.pointerId!==e.pointerId)return;e.preventDefault();button.focus({preventScroll:true});button.setPointerCapture(e.pointerId);action({type:'down',row,pointerId:e.pointerId,...point(e)});});button.addEventListener('pointermove',e=>action({type:'move',pointerId:e.pointerId,...point(e)}));button.addEventListener('pointerup',e=>{if(e.pointerId!==state.pointerId)return;action({type:'up',pointerId:e.pointerId,reduced:motion.matches});if(button.hasPointerCapture(e.pointerId))button.releasePointerCapture(e.pointerId);status.textContent=`${button.getAttribute('aria-label')}: ${label(row,state.values[row])}`;});for(const name of ['pointercancel','lostpointercapture'])button.addEventListener(name,e=>action({type:'cancel',pointerId:e.pointerId}));button.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key)){e.preventDefault();action({type:'key',row,key:e.key});}});});
addEventListener('keydown',e=>{if(e.key==='Escape'||e.key.toLowerCase()==='r'){status.textContent='';action({type:'reset'});}});
motion.addEventListener?.('change',()=>{action({type:'motion',reduced:motion.matches});});
function frame(now){const dt=last===null?0:(now-last)/1000;last=now;if(!motion.matches){state=reduce(state,{type:'tick',dt});paint();}requestAnimationFrame(frame);}paint();requestAnimationFrame(frame);
