import {createRequire} from 'node:module';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';import {spawnSync} from 'node:child_process';import {scene,demoState,DURATION,WIDTH,HEIGHT} from './scene.mjs';
const sharp=createRequire(import.meta.url)('sharp'),root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),out=path.join(root,'preview'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'angry-sliders-'));fs.mkdirSync(out,{recursive:true});const FPS=60,N=Math.round(DURATION*FPS);
for(const [name,t]of [['poster',0],['fov-pull',2.73],['bloom-pull',5.82],['exposure-flight',9.07],['samples-pull',14.16],['samples-flight',14.64],['settled',17.1]])await sharp(Buffer.from(scene(demoState(t)))).png().toFile(path.join(out,`${name}.png`));
if(process.argv.includes('--stills')){fs.rmSync(tmp,{recursive:true,force:true});process.exit(0);}
for(let f=0;f<N;f++)await sharp(Buffer.from(scene(demoState(f/FPS))),{density:144}).png().toFile(path.join(tmp,`${String(f).padStart(4,'0')}.png`));
function ff(args){const p=spawnSync('ffmpeg',['-y','-v','error',...args],{stdio:'inherit'});if(p.status!==0)throw Error('FFmpeg failed');}
ff(['-framerate',String(FPS),'-i',path.join(tmp,'%04d.png'),'-c:v','libx264','-crf','17','-preset','fast','-pix_fmt','yuv420p','-movflags','+faststart',path.join(out,'angry-sliders.mp4')]);
ff(['-framerate',String(FPS),'-i',path.join(tmp,'%04d.png'),'-filter_complex','fps=30,scale=733:794:flags=lanczos,split[a][b];[a]palettegen=max_colors=192[p];[b][p]paletteuse=dither=bayer:bayer_scale=3','-loop','0',path.join(out,'angry-sliders.gif')]);
fs.writeFileSync(path.join(out,'render-info.json'),JSON.stringify({renderer:'sharp/librsvg rendering of the same parametric SVG scene used in the browser',browser_capture:false,reference_audio_copied:false,audio:'Silent visual reconstruction. Original has an audio track, which is not reproduced.',working_size:[WIDTH,HEIGHT],mp4_size:[WIDTH*2,HEIGHT*2],gif_size:[WIDTH,HEIGHT],fps:FPS,frames:N,duration_seconds:DURATION,source_timing:'990 actual VFR controls, including a preserved 0.083333–0.416667 capture hold',loop:'Full original four-slider sequence; added neutral reset from 17.8–18.55s followed by initial hold',versions:sharp.versions},null,2));fs.rmSync(tmp,{recursive:true,force:true});console.log(`Rendered ${N} full-resolution frames and a clean silent GIF/MP4 loop.`);
