import {CONTROLS} from './controls.mjs';
export const WIDTH=733,HEIGHT=794,DURATION=19.2;
export const Y=[289,367,445,523],MIN=[-3,0,20,1],MAX=[3,100,120,256],INITIAL=[.4,35,72,64],LABELS=['Exposure','Bloom','Field of view','Samples'];
export const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const mix=(a,b,p)=>a+(b-a)*p,n=v=>Number(v.toFixed(4)),clone=v=>structuredClone(v);
export const valueX=(i,v)=>173+(v-MIN[i])/(MAX[i]-MIN[i])*385;
export const xValue=(i,x)=>{const v=MIN[i]+clamp((x-173)/385)*(MAX[i]-MIN[i]);return i===0?Math.round(v*10)/10:Math.round(v);};
export const label=(i,v)=>i===0?`${v>=0?'+':''}${v.toFixed(1)} EV`:i===1?`${Math.round(v)}%`:i===2?`${Math.round(v)}°`:String(Math.round(v));
function interpolate(a,b,u){if(Array.isArray(a))return a.map((v,j)=>interpolate(v,b[j],u));if(typeof a==='number')return mix(a,b,u);return a;}
export function nativeState(t){let lo=0,hi=CONTROLS.length-1;while(lo+1<hi){const m=(lo+hi)>>1;if(CONTROLS[m].t<=t)lo=m;else hi=m;}const a=CONTROLS[lo],b=CONTROLS[hi],u=b.t-a.t>.08?0:clamp((t-a.t)/(b.t-a.t));if(t>=b.t)return clone(b);const s=clone(a);for(const k of ['values','fills'])s[k]=interpolate(a[k],b[k],u);if(a.active===b.active)for(const k of ['ball','label','target','prediction','arc','ring','white','anchors','bands','residual'])s[k]=interpolate(a[k],b[k],u);s.cursor=[mix(a.cursor[0],b.cursor[0],u),mix(a.cursor[1],b.cursor[1],u),a.cursor[2],a.cursor[3]];s.t=t;return s;}
export function demoState(t){t=((t%DURATION)+DURATION)%DURATION;const s=nativeState(t);if(t>17.8){const p=clamp((t-17.8)/.75),q=p*p*(3-2*p);s.active=-1;s.values=s.values.map((v,i)=>mix(v,INITIAL[i],q));s.fills=s.fills.map((v,i)=>interpolate(v,CONTROLS[0].fills[i],q));s.cursor=[282,604,0,q];s.arc=s.prediction=0;s.bands.forEach(v=>v[4]=0);}return s;}
export function projection(i,anchor,px,py){let dx=px-anchor,dy=py-Y[i],len=Math.hypot(dx,dy),scale=len?90*Math.tanh(len/90)/len:1;dx*=scale;dy*=scale;const bx=anchor+dx,by=Y[i]+dy,lambda=19.5,disc=dy*dy-2*lambda*dy;let q=disc>=0?(dy+Math.sqrt(disc))/lambda:0;q=Math.max(0,q);const target=clamp(q?bx-dx*q:bx,173,558);return {ball:[bx,by],target,value:xValue(i,target),q,dx,dy};}
export function reduce(s,a){
 if(a.type==='reset')return {mode:'demo',time:0,values:INITIAL.slice(),selected:-1,phase:'idle',pointerId:null,epoch:0};
 if(a.type==='motion'&&a.reduced)return {...s,time:s.mode==='demo'?0:s.time,phase:s.phase==='flight'?'idle':s.phase,flight:null};
 if(a.type==='down'){if(s.phase==='drag'&&s.pointerId!==a.pointerId)return s;let values=s.mode==='demo'?demoState(s.time).values.slice():s.values.slice(),i=a.row;if(Math.abs(a.x-valueX(i,values[i]))>14)values[i]=xValue(i,a.x);return {...s,mode:'interactive',values,selected:i,phase:'drag',anchor:valueX(i,values[i]),pointerId:a.pointerId,drag:projection(i,valueX(i,values[i]),a.x,a.y),flight:null,epoch:s.epoch+1};}
 if(a.type==='move'){if(s.phase!=='drag'||a.pointerId!==s.pointerId)return s;return {...s,drag:projection(s.selected,s.anchor,a.x,a.y)};}
 if(a.type==='cancel'){if(s.phase!=='drag'||a.pointerId!==s.pointerId)return s;return {...s,phase:'idle',pointerId:null,drag:null,flight:null};}
 if(a.type==='up'){if(s.phase!=='drag'||a.pointerId!==s.pointerId)return s;const i=s.selected,d=s.drag,values=s.values.slice();values[i]=d.value;if(a.reduced||d.q<=.05)return {...s,phase:'idle',pointerId:null,values,drag:null};let T=clamp(d.q/11,.03,.8),end=valueX(i,d.value),g=2*(Y[i]-d.ball[1]+d.dy*11*T)/(T*T);return {...s,phase:'flight',pointerId:null,values,flight:{start:d.ball,end,T,vy:-d.dy*11,g,elapsed:0,epoch:s.epoch},drag:null};}
 if(a.type==='key'){const i=a.row,values=s.mode==='demo'?demoState(s.time).values.slice():s.values.slice(),step=i===0?.1:1;values[i]=a.key==='Home'?MIN[i]:a.key==='End'?MAX[i]:clamp(values[i]+(a.key==='ArrowLeft'||a.key==='ArrowDown'?-step:step),MIN[i],MAX[i]);return {...s,mode:'interactive',phase:'idle',values,selected:i,flight:null,drag:null,pointerId:null,epoch:s.epoch+1};}
 if(a.type==='tick'){const dt=Number.isFinite(a.dt)?clamp(a.dt,0,.1):0;if(s.mode==='demo')return {...s,time:(s.time+dt)%DURATION};if(s.phase==='flight'){const f={...s.flight,elapsed:s.flight.elapsed+dt};return {...s,flight:f,phase:f.elapsed>f.T+.6?'idle':'flight'};}}
 return s;
}
export function drawState(s){if(s.mode==='demo')return demoState(s.time);const i=s.selected,out={t:0,active:i,anchor:s.anchor,values:s.values.slice(),ball:i>=0?[valueX(i,s.values[i]),Y[i]]:[0,0],cursor:[0,0,0,0],fills:s.values.map((v,j)=>[valueX(j,v)-8,1]),label:0,target:0,prediction:0,arc:0,ring:1,white:1,anchors:0,residual:[0,0,0],bands:[[0,0,0,0,0],[0,0,0,0,0]]};
 if(s.phase==='drag'){const d=s.drag;out.ball=d.ball;out.values[i]=d.value;out.target=d.target;out.label=1;out.prediction=clamp(Math.hypot(d.dx,d.dy)/12);out.arc=d.q>.05?1:0;out.white=0;out.anchors=1;out.fills[i]=[s.anchor,.17];out.bands=[[...d.ball,s.anchor-7,Y[i],1],[...d.ball,s.anchor+7,Y[i],1]];}
 if(s.phase==='flight'){const f=s.flight,t=Math.min(f.elapsed,f.T),p=t/f.T;out.ball=[mix(f.start[0],f.end,p),f.start[1]+f.vy*t+.5*f.g*t*t];if(f.elapsed>=f.T){let b=f.elapsed-f.T;out.ball[1]=Y[i]-12*Math.exp(-6*b)*Math.abs(Math.sin(18*b));}out.label=1-clamp((f.elapsed-f.T)/.45);out.white=clamp(f.elapsed/.06);out.fills[i]=[f.end-8,mix(.17,1,clamp((f.elapsed-f.T-.2)/.35))];}
 return out;
}
function rgb(a,b,p){return '#'+a.map((v,i)=>Math.round(mix(v,b[i],p)).toString(16).padStart(2,'0')).join('');}
const PURPLE='#5b50e7',BG='#1a191e';
function cursor(c){if(!c[3])return '';const [x,y,type,opacity]=c;const arrow='M0 0L9.3 9.8L6 10.1L8.6 14.4L6.2 15.8L3.5 11.1L.2 13.8Z',grab='M2 3Q.6 1 2.3 .6Q4-.1 4.7 3V1.4Q6-.4 7.3 1.3V3Q8.5 .5 9.6 1.6V3Q11 1.3 12.2 2.8L13 6Q13 11 8 12Q3 13 1 9L0 6Q-.5 4 1 4L3 6Z',hand='M3 9L2 4Q2 2 3.4 2Q5 2 5 4V8V1.5Q5-.3 6.6 0Q8 0 8 2V8L8.5 3Q8.7 1.5 10 2Q11 2 11 4V8L11.5 4Q13 2 14 4V10L15 7Q16 6 16 8V12Q16 17 11 18.5Q6 20 3 16L0 12Q-1 10 1 9Q2 9 3 11Z';return `<g opacity="${n(opacity)}" transform="translate(${n(x+(type===0?-1:1))} ${n(y+(type===0?-2:0))})"><path d="${type===0?arrow:type===1?hand:grab}" fill="${type===0?'#050505':'#fff'}" stroke="${type===0?'#dfdee6':'#050505'}" stroke-width="${type===0?.9:1.25}" stroke-linejoin="round" stroke-linecap="round"/></g>`;}
export function scene(s){let out=`<svg xmlns="http://www.w3.org/2000/svg" width="733" height="794" viewBox="0 0 733 794"><rect width="733" height="794" fill="${BG}"/>`;for(let i=0;i<4;i++){const y=Y[i],color=i===s.active?rgb([195,194,202],[91,80,231],s.label):'#c3c2ca';out+=`<text x="165.5" y="${y-23}" fill="#96959d" font-family="Arial,Helvetica,sans-serif" font-size="13.5">${LABELS[i]}</text><text x="566" y="${y-23}" text-anchor="end" fill="${color}" font-family="DejaVu Sans Mono,monospace" font-size="12">${label(i,s.values[i])}</text><path d="M173 ${y}H558" fill="none" stroke="#353439" stroke-width="2" stroke-linecap="round"/><path d="M173 ${y}H${n(Math.max(173,s.fills[i][0]))}" fill="none" stroke="#e0dfe4" opacity="${n(s.fills[i][1])}" stroke-width="2" stroke-linecap="round"/>`;if(i!==s.active)out+=`<circle cx="${n(valueX(i,s.values[i]))}" cy="${y}" r="6.35" fill="#ebeaf0" stroke="${BG}" stroke-width="1.8" paint-order="stroke fill"/>`;}
 if(s.active>=0){const i=s.active,[bx,by]=s.ball,anchor=s.anchor??(i===0?391.167:i===1?307.75:i===2?373.2:268.118),dx=bx-anchor,dy=by-Y[i];if(s.arc>.001){let q=Math.abs(dx)>3?(s.target-bx)/(-dx):(dy+Math.sqrt(Math.max(0,dy*dy-39*dy)))/19.5;q=clamp(q,.1,10);const control=by-dy*q/2;for(let j=1;j<20;j++){const p=j/20,x=mix(bx,s.target,p),y=(1-p)**2*by+2*(1-p)*p*control+p*p*Y[i];out+=`<circle cx="${n(x)}" cy="${n(y)}" r="1.6" fill="#72717a" opacity="${n(s.arc*.7)}"/>`;}}
 if(s.anchors>.001)for(const ax of [anchor-7,anchor+7])out+=`<circle cx="${ax}" cy="${Y[i]}" r="1.6" fill="#75747c" opacity="${n(s.anchors)}"/>`;
 if(s.residual?.[2]>.001)for(const ax of [anchor-7,anchor+7])out+=`<path d="M${n(s.residual[0])} ${n(s.residual[1])}L${ax} ${Y[i]}" fill="none" stroke="${PURPLE}" stroke-width="1.2" opacity="${n(s.residual[2])}" stroke-linecap="round"/>`;
 for(const b of s.bands)if(b[4]>.001)out+=`<path d="M${n(b[0])} ${n(b[1])}L${n(b[2])} ${n(b[3])}" fill="none" stroke="${PURPLE}" stroke-width="1.2" opacity="${n(b[4])}" stroke-linecap="round"/>`;
 if(s.prediction>.001)out+=`<g opacity="${n(s.prediction)}"><path d="M${n(s.target)} ${Y[i]-6}V${Y[i]+6}" stroke="${PURPLE}" stroke-width="1.5"/><text x="${n(s.target)}" y="${Y[i]-13}" fill="${PURPLE}" text-anchor="middle" font-size="10" font-family="DejaVu Sans Mono,monospace">${label(i,s.values[i])}</text></g>`;
 out+=`<circle cx="${n(bx)}" cy="${n(by)}" r="8" fill="${PURPLE}" opacity="${n(Math.max(s.ring,1-s.white))}"/><circle cx="${n(bx)}" cy="${n(by)}" r="6.25" fill="#ebeaf0" opacity="${n(s.white)}"/>`;}
 return out+cursor(s.cursor)+'</svg>';
}
