(function(){'use strict';const S=window.TaskCardScene,art=document.getElementById('art'),stage=document.getElementById('stage'),card=document.getElementById('card'),status=document.getElementById('status'),pref=window.matchMedia('(prefers-reduced-motion: reduce)');let reduced=pref.matches,automatic=!reduced,epoch=performance.now(),index=0,animation=null,drag=null;
function steady(k){return S.state(k<4?k*66/60:270/60);}
function scene(now){if(automatic)return S.state((now-epoch)/1000);if(animation){const elapsed=(now-animation.started)/1000,local=animation.local+elapsed*60;if(local>=66){index=Math.min(4,index+1);animation=null;return steady(index);}const s=S.state((index*66+local)/60);s.phone=[331,35,299,650];if(animation.direction!==(index%2?1:-1)){for(const c of s.cards)if(c.k===index){c.dx=-(c.dx||0);c.angle=-(c.angle||0);}if(s.touch)s.touch[0]=960-s.touch[0]-s.touch[2];}return s;}let s=steady(index);if(drag&&index<4){const c=s.cards.find(c=>c.k===index);c.dx=drag.dx;c.angle=drag.dx*.035;s.touch=null;}return s;}
function takeControl(){if(automatic){const s=scene(performance.now());index=Math.min(4,s.active);automatic=false;animation=null;}}
function advance(direction){takeControl();if(index>=4){index=0;animation=null;status.textContent='Task stack restarted';return;}if(animation)return;if(reduced){index++;status.textContent=index===4?'All tasks complete':S.CARDS[index].title.join(' ');return;}animation={started:performance.now(),local:12,direction};status.textContent='Task dismissed';}
function replay(){index=0;drag=null;animation=null;epoch=performance.now();automatic=!reduced;status.textContent='Task stack restarted';}
for(const [id,dir] of [['snooze',-1],['complete',1],['next',-1]])document.getElementById(id).addEventListener('click',()=>advance(dir));
card.addEventListener('pointerdown',e=>{takeControl();if(index>=4||animation)return;card.setPointerCapture?.(e.pointerId);drag={start:e.clientX,dx:0};});card.addEventListener('pointermove',e=>{if(drag)drag.dx=(e.clientX-drag.start)*S.W/stage.getBoundingClientRect().width;});function end(){if(!drag)return;const dx=drag.dx;drag=null;if(Math.abs(dx)>35)advance(Math.sign(dx));}card.addEventListener('pointerup',end);card.addEventListener('pointercancel',()=>{drag=null;});card.addEventListener('keydown',e=>{if(['Enter',' ','ArrowRight','ArrowLeft'].includes(e.key)){e.preventDefault();advance(e.key==='ArrowRight'?1:-1);}});
document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='r')replay();if(e.key==='Escape'){takeControl();animation=null;drag=null;}});pref.addEventListener?.('change',e=>{reduced=e.matches;if(reduced){takeControl();animation=null;drag=null;}});function paint(now){const s=scene(now);art.innerHTML=S.svg(0,s);card.setAttribute('aria-label',s.active===4?'All tasks complete. Press R to replay':S.CARDS[Math.min(3,s.active)].title.join(' ')+'. Swipe or press Enter to dismiss.');window.requestAnimationFrame(paint);}window.TaskCardDemo={advance,replay,getState:()=>({automatic,index,reduced,animating:!!animation,scene:scene(performance.now())})};paint(epoch);})();
