import test from 'node:test';import assert from 'node:assert/strict';
import {SPEC,geometry,frame,previousRowOffset,springForDistance,shapeEase} from '../src/motion.mjs';
const c={top:560,bottom:616,left:140,right:820,width:680,height:56};
const b={top:468,bottom:512,left:542,right:820,width:278,height:44};
const g=geometry(c,b);
const close=(a,b,e=1e-6)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`);
test('verified default durations',()=>assert.deepEqual([SPEC.travelMs,SPEC.shapeMs,SPEC.receiptExtraMs],[600,190,200]));
test('start aligns composer right and top when body fits',()=>{const f=frame(g,0);close(f.x,0);close(f.y,92);close(f.extraWidth,402);});
test('tall message aligns composer bottom',()=>close(geometry(c,{...b,height:140}).y,8));
test('spring is normalized to 600 ms',()=>{const f=frame(g,600);close(f.x,0);close(f.y,0);close(f.scaleX,1);});
test('width morph is complete by 190 ms',()=>close(frame(g,190).extraWidth,0));
test('width curve is not simple linear',()=>assert.notEqual(shapeEase(.5),.5));
test('compression reaches its specified size at one third',()=>{close(frame(g,200).scaleX,g.minScaleX);close(frame(g,200).scaleY,g.minScaleY);});
test('size factor follows both message dimensions',()=>{const big=geometry(c,{...b,width:400,height:120});close(big.minScaleX,1-18/400);close(big.minScaleY,1-4/120);});
test('scale clamp prevents pathological skinny collapse',()=>{const skinny=geometry(c,{...b,width:1,height:400});close(skinny.minScaleX,.5);});
test('receipt waits 800 ms, not network completion',()=>{assert.equal(frame(g,799).receiptVisible,false);assert.equal(frame(g,800).receiptVisible,true);});
test('zoom compensation preserves CSS motion',()=>{const scale=o=>Object.fromEntries(Object.entries(o).map(([k,v])=>[k,v*2]));const z=geometry(scale(c),scale(b),2);close(z.y,g.y);close(z.extraWidth,g.extraWidth);});
test('zero distance remains finite and critically damped',()=>{const s=springForDistance(0);assert.equal(s.zeta,1);assert.ok(s.samples.every(Number.isFinite));});
test('damping changes with travel distance',()=>assert.ok(springForDistance(400).damping>springForDistance(20).damping));
test('spring curve has 60 rounded CSS samples',()=>{assert.equal(g.spring.samples.length,60);assert.ok(g.spring.samples.every(x=>Math.abs(x*1e4-Math.round(x*1e4))<1e-8));});
test('reduced motion is instantaneous and does not retain hold',()=>{const f=frame(g,0,{reducedMotion:true});assert.deepEqual([f.x,f.y,f.scaleX,f.active,f.receiptVisible],[0,0,1,false,true]);});
test('existing-row correction ends at 190 ms',()=>{close(previousRowOffset(140,120,0),20);close(previousRowOffset(140,120,190),0);});
test('invalid zoom is rejected',()=>assert.throws(()=>geometry(c,b,0),RangeError));
