(function(){
  'use strict';
  const stage=document.getElementById('stage'),art=document.getElementById('art'),controls=document.getElementById('controls'),play=document.getElementById('play'),status=document.getElementById('status');
  const model=new TagModel.Picker();let mode='recorded',playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,time=0,last=performance.now(),row=TagScene.observed(0),signature='';
  function adopt(){if(mode==='recorded'){model.adopt(row);mode='live';playing=false;signature='';}return model;}
  function dispatch(box){const m=adopt();if(box.kind==='open')m.open?m.close():m.show();if(box.kind==='toggle')m.toggle(box.id);if(box.kind==='create')m.beginCreate();if(box.kind==='color')m.commit(box.id);draw();}
  function semantic(){const boxes=TagScene.hitboxes(row);const key=JSON.stringify(boxes.map(x=>[x.kind,x.id,x.x,x.y,x.w,x.h,x.selected]));if(key===signature)return;signature=key;const focused=document.activeElement?.dataset?.kind;controls.replaceChildren();for(const box of boxes){const input=box.kind==='query'||box.kind==='colorQuery',el=document.createElement(input?'input':'button');el.dataset.kind=box.kind;el.setAttribute('aria-label',box.label);el.style.left=box.x/12+'%';el.style.top=box.y/12.48+'%';el.style.width=box.w/12+'%';el.style.height=box.h/12.48+'%';if(input){el.type='text';el.value=box.kind==='query'?row.query:row.colorQuery||'';el.autocomplete='off';el.spellcheck=false;el.maxLength=40;el.addEventListener('focus',()=>{adopt();});el.addEventListener('input',()=>{const start=el.selectionStart;const m=adopt();box.kind==='query'?m.search(el.value):m.searchColors(el.value);draw();const next=controls.querySelector('input[data-kind="'+box.kind+'"]');next?.focus();next?.setSelectionRange(start,start);});}else{el.type='button';if(box.selected!==undefined)el.setAttribute('aria-pressed',String(box.selected));el.addEventListener('click',()=>dispatch(box));}controls.append(el);}if(focused)controls.querySelector('input[data-kind="'+focused+'"]')?.focus();}
  function draw(){row=mode==='recorded'?TagScene.observed(time):model.snapshot();art.innerHTML=TagScene.render(row);semantic();play.textContent=playing?'Pause':'Play';status.textContent=mode==='recorded'?'Recorded motion':'Interactive picker';}
  play.addEventListener('click',()=>{if(mode==='live'){mode='recorded';time=0;signature='';}playing=!playing;last=performance.now();draw();});
  document.getElementById('replay').addEventListener('click',()=>{mode='recorded';time=0;playing=!matchMedia('(prefers-reduced-motion: reduce)').matches;signature='';last=performance.now();draw();});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();adopt().escape();draw();}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();adopt().move(e.key==='ArrowDown'?1:-1);draw();}else if(e.key==='Enter'&&document.activeElement?.tagName!=='BUTTON'){e.preventDefault();adopt().enter();draw();}else if(e.key===' '&&document.activeElement?.tagName!=='INPUT'&&document.activeElement?.tagName!=='BUTTON'){e.preventDefault();playing=!playing;last=performance.now();draw();}});
  stage.addEventListener('pointerdown',e=>{if(e.target===controls&&row.open){adopt().close();draw();}});
  function tick(now){if(playing&&mode==='recorded'){time=(time+Math.min(.1,(now-last)/1000))%TagScene.DURATION;draw();}last=now;requestAnimationFrame(tick);}draw();requestAnimationFrame(tick);
})();
