const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),S=require('./scene.js');let b={};vm.runInNewContext(fs.readFileSync(__dirname+'/assets.js','utf8')+fs.readFileSync(__dirname+'/particles.js','utf8')+';this.a=ASSETS;this.p=PARTICLES;',b);
for(const [t,to]of [[0,0],[1.75,1],[3.2,1],[4.7,0],[6.1,0],[7.5,1],[9,1],[9.7,0],[11,0]])assert.equal(S.state(t).to,to);
for(let i=0;i<680;i++){const t=i/60,s=S.state(t),c=S.cameraAt(t),rect=S.buttonBounds(t);assert.ok(s.p>=0&&s.p<=1);assert.ok(c.every(Number.isFinite));assert.ok(Object.values(rect).every(Number.isFinite));assert.ok(rect.x>0&&rect.x+rect.width<1000&&rect.y>0&&rect.y+rect.height<1000);}
assert.equal(S.svg(0,b.a,b.p),S.svg(S.DURATION,b.a,b.p));for(let i=0;i<271;i+=6)assert.ok(!/NaN|undefined|Infinity/.test(S.svg(i/24,b.a,b.p).replace(/data:image\/png;base64,[^"]+/g,'')));
function controller(reduce){let now=0,raf=[],key,els={};const el=id=>els[id]||(els[id]={style:{},events:{},attrs:{},innerHTML:'',addEventListener(n,f){this.events[n]=f},setAttribute(k,v){this.attrs[k]=v}});const ctx={Scene:S,ASSETS:b.a,PARTICLES:b.p,document:{getElementById:el},performance:{now:()=>now},matchMedia:()=>({matches:reduce}),addEventListener:(n,f)=>key=f,requestAnimationFrame:f=>raf.push(f)};vm.runInNewContext(fs.readFileSync(__dirname+'/app.js','utf8'),ctx);const step=(n=1)=>{for(let i=0;i<n;i++){now+=1000/60;raf.shift()(now)}};step();el('toggle').events.click();step(10);el('toggle').events.click();el('toggle').events.click();step(100);assert.equal(el('toggle').attrs['aria-pressed'],'true');el('toggle').events.click();step(10);el('toggle').events.click();step(180);assert.equal(el('toggle').attrs['aria-pressed'],'true');key({key:'Escape'});step();assert.equal(el('toggle').attrs['aria-pressed'],'false');assert.ok(parseFloat(el('toggle').style.width)>20);}
controller(false);controller(true);
{let now=0,raf=[],nodes={};const el=id=>nodes[id]||(nodes[id]={style:{},events:{},innerHTML:'',addEventListener(n,f){this.events[n]=f},setAttribute(){}});const ctx={Scene:S,ASSETS:b.a,PARTICLES:b.p,document:{getElementById:el},performance:{now:()=>now},matchMedia:()=>({matches:false}),addEventListener(){},requestAnimationFrame:f=>raf.push(f)};vm.runInNewContext(fs.readFileSync(__dirname+'/app.js','utf8')+';this.inspect=()=>({manual,requested});',ctx);for(let i=0;i<110;i++){now+=1000/60;raf.shift()(now);}const previous=S.state(now/1000);el('toggle').events.click();assert.deepEqual(JSON.parse(JSON.stringify(ctx.inspect().manual)),previous);for(let i=0;i<200;i++){now+=1000/60;raf.shift()(now);}assert.equal(ctx.inspect().manual.to,0);}
assert.ok(fs.readFileSync(__dirname+'/app.js','utf8').includes('document.fonts.load'));
console.log(JSON.stringify({passed:true,checks:['Both source show/hide cycles and stable holds','680 finite camera/state/hit-area samples','46 shared-scene SVG samples','Exact loop equality','Repeated clicks and latest-target queue','Interrupted automatic transition completion','Escape','Reduced motion','Font-load gate present'],particles:b.p.map(a=>a.length),runtime:'Node VM event mocks; no real browser runtime verification'},null,2));
