(function(root,factory){const api=factory();if(typeof module==='object')module.exports=api;else root.RulerScene=api;})(globalThis,function(){
'use strict';const W=1344,H=460,Type=typeof module==='object'?require('./type.js'):globalThis.RulerType,Metrics=typeof module==='object'?require('./label-metrics.js'):globalThis.RulerLabelMetrics;
const n=v=>Number(v.toFixed(4)),clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const color=(a,b,p)=>`rgb(${a.map((x,i)=>n(x+(b[i]-x)*clamp(p))).join(',')})`;
function text(value,x,y,size,fill,weight=0){const chars=String(value),scale=size/Type.unitsPerEm,width=[...chars].reduce((sum,ch)=>sum+Type.glyphs[ch].advance*scale,0);let left=x-width/2,out='';for(const ch of chars){const g=Type.glyphs[ch];out+=`<path d="${g.path}" transform="translate(${n(left)} ${y}) scale(${n(scale)} ${n(-scale)})" fill="${fill}" stroke="${fill}" stroke-width="${n(weight*Type.unitsPerEm/size)}" stroke-linejoin="round"/>`;left+=g.advance*scale;}const m=Metrics[String(value)]||{dx:0,dy:0,sx:1,sy:1};return `<g transform="translate(${n(x+m.dx)} ${n(y+m.dy)}) scale(${n(m.sx)} ${n(m.sy)}) translate(${n(-x)} ${n(-y)})">${out}</g>`;}
function render(s){let out=`<svg xmlns="http://www.w3.org/2000/svg" width="1344" height="460" viewBox="0 0 1344 460" role="img" aria-label="Signed fractional ruler"><defs><linearGradient id="fade" gradientUnits="userSpaceOnUse" x1="0" x2="1344"><stop offset="0" stop-color="white" stop-opacity="0"/><stop offset=".01116" stop-color="white" stop-opacity="0"/><stop offset=".15" stop-color="white"/><stop offset=".85" stop-color="white"/><stop offset=".98884" stop-color="white" stop-opacity="0"/><stop offset="1" stop-color="white" stop-opacity="0"/></linearGradient><mask id="ruler-mask"><rect width="1344" height="260" fill="url(#fade)"/></mask><filter id="ring-soft" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="1.6"/></filter></defs><rect width="1344" height="460" fill="#191919"/><g mask="url(#ruler-mask)">`;
for(let v=-90;v<=90;v++){const x=672.5+15*v+s.offset;if(x< -50||x>1394)continue;const major=v%5===0,selected=s.selected&&v>=s.selected[0]&&v<=s.selected[1],p=s.tickMix?s.tickMix[v+90]:(selected?1:0),ink=color(major?[230,230,230]:[100,100,100],[0,130,253],p);out+=`<rect x="${n(x-1.5)}" y="${major?214:230}" width="3" height="${major?32:16}" rx="1.5" fill="${ink}"/>`;if(major){const q=s.labelMix?s.labelMix[(v+90)/5]:(selected?1:0);out+=text(v,x-1.1,190,26,color([150,150,150],[230,230,230],q),.45*q);}}
out+='</g><circle cx="672" cy="284" r="4" fill="#e8e8e8"/>';
for(const [k,r] of (s.rings||[]).entries()){const customized=r.blur!=null&&Math.abs(r.blur-1.6)>.0001;if(customized)out+=`<defs><filter id="ring-release-${k}" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="${n(r.blur)}"/></filter></defs>`;out+=`<circle cx="${n(r.x)}" cy="${n(r.y)}" r="${n(r.r)}" fill="none" stroke="#1967eb" stroke-width="${n(r.w||6)}" opacity="${n(r.alpha)}" filter="url(#${customized?`ring-release-${k}`:'ring-soft'})"/>`;}
if(s.cursor){const c=s.cursor;if(c.kind==='resize')out+=`<path d="M-15 0L-5 -10V-4H5V-10L15 0L5 10V4H-5V10Z" transform="translate(${n(c.x)} ${n(c.y)}) scale(${n((c.w||31)/32)} ${n((c.h||23)/22)})" fill="#070707" stroke="white" stroke-width="1.5" stroke-linejoin="miter"/>`;else out+=`<path d="M0 0V26L6.5 20.5L11.5 31.5L16 29.5L11 19H21Z" transform="translate(${n(c.x-c.w/2)} ${n(c.y-c.h/2)}) scale(.95)" fill="#080808" stroke="white" stroke-width="1.5"/>`;}
return out+'</svg>';}
return{W,H,render};});
