(function(root,factory){const api=factory(typeof module==='object'?require('./type-metrics.js'):root.CalendarTypeMetrics);if(typeof module==='object')module.exports=api;else root.CalendarScene=api;})(globalThis,function(metrics){
'use strict';const W=1318,H=812,num=v=>Number(v.toFixed(4)),esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function fittedText(text,box){if(!box||!metrics[text])return '';const m=metrics[text];return `<g transform="translate(${num(box.x)} ${num(box.y)}) scale(${num(box.w/m.w)} ${num(box.h/m.h)}) translate(${-m.x} ${-m.y})"><text x="0" y="100" font-family="Inter,Arial,sans-serif" font-size="100" font-weight="${m.weight}" fill="white">${esc(text)}</text></g>`;}
function render(state){const g=state.guide;let out=`<svg xmlns="http://www.w3.org/2000/svg" width="1318" height="812" viewBox="0 0 1318 812" role="img" aria-label="Calendar event creation"><rect width="1318" height="812" fill="#191919"/>`;
for(let i=0;i<5;i++){const y=145+i*124;out+=`<path d="M390 ${y}H930" stroke="#2c2c2c" stroke-width="4"/><text x="309" y="${y+8}" font-family="Inter,Arial,sans-serif" font-size="25" fill="#676767">${i+1} PM</text>`;}
if(state.ring){const r=state.ring;out+=`<circle cx="${num(r.x)}" cy="${num(r.y)}" r="${num(r.r)}" fill="none" stroke="#1967eb" stroke-width="${num(r.w??6)}" opacity="${num(Math.min(2,r.alpha)*.5)}"/>`;}
if(state.event){const e=state.event;out+=`<defs><clipPath id="event-clip"><rect x="390" y="${num(e.y)}" width="540" height="${num(Math.max(0,e.h))}" rx="12"/></clipPath></defs><g opacity="${num(e.alpha)}" clip-path="url(#event-clip)"><rect x="390" y="${num(e.y)}" width="540" height="${num(Math.max(0,e.h))}" rx="12" fill="${e.paint?`rgb(${e.paint.map(Math.round).join(',')})`:'#0082fd'}"/>`;
if(e.ink){out+=fittedText(e.label,e.ink[0])+fittedText('New Event',e.ink[1]);}else{out+=`<text x="406" y="${num(e.baseline||e.y+35)}" font-family="Inter,Arial,sans-serif" font-size="${num(e.font||26)}" fill="white">${esc(e.label)}</text><text x="406" y="${num(e.y+71)}" font-family="Inter,Arial,sans-serif" font-size="28" font-weight="500" fill="white">New Event</text>`;}out+='</g>';}
if(state.event&&state.ring){const r=state.ring;out+=`<circle clip-path="url(#event-clip)" cx="${num(r.x)}" cy="${num(r.y)}" r="${num(r.r)}" fill="none" stroke="#0032f5" stroke-width="${num(r.w??6)}" opacity="${num(Math.min(2,r.alpha)*state.event.alpha*.125)}"/>`;}
if(g){const c=Math.round(g.c);out+=`<rect x="${num(g.x)}" y="${num(g.y)}" width="${num(g.w)}" height="${num(g.h)}" rx="${num(g.h/2)}" fill="rgb(${c},${c},${c})"/>`;}
return out+'</svg>';}
return{W,H,render};});
