import {createRequire} from 'node:module';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';import {spawnSync} from 'node:child_process';import {scene,demoState,DURATION,WIDTH,HEIGHT} from './scene.mjs';
const require=createRequire(import.meta.url),sharp=require('sharp');const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),out=path.join(root,'preview'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'luminous-tabs-'));fs.mkdirSync(out,{recursive:true});
const FPS=30,N=Math.round(DURATION*FPS);
for(let f=0;f<N;f++)await sharp(Buffer.from(scene(demoState(f/FPS)))).png().toFile(path.join(tmp,`${String(f).padStart(4,'0')}.png`));
for(const [name,t] of [['poster',1.3],['idle',0],['email-onset',.6],['email-collapse',2.3],['attachment-onset',3.5],['attachment-active',4.2]])await sharp(Buffer.from(scene(demoState(t)))).png().toFile(path.join(out,`${name}.png`));
function ff(args){const p=spawnSync('ffmpeg',['-y','-v','error',...args],{stdio:'inherit'});if(p.status!==0)throw Error('ffmpeg failed');}
ff(['-framerate',String(FPS),'-i',path.join(tmp,'%04d.png'),'-c:v','libx264','-crf','17','-preset','fast','-pix_fmt','yuv420p','-movflags','+faststart',path.join(out,'luminous-tabs.mp4')]);
ff(['-i',path.join(out,'luminous-tabs.mp4'),'-filter_complex','fps=20,scale=716:-1:flags=lanczos,split[a][b];[a]palettegen=max_colors=192[p];[b][p]paletteuse=dither=bayer:bayer_scale=3','-loop','0',path.join(out,'luminous-tabs.gif')]);
fs.writeFileSync(path.join(out,'render-info.json'),JSON.stringify({renderer:'sharp/librsvg offline rasterization of the same scene.mjs SVG used by browser demo',browser_capture:false,versions:sharp.versions,width:WIDTH,height:HEIGHT,fps:FPS,frames:N,duration_seconds:DURATION,loop:'Complete observed 6-second sequence; neutral endpoints create clean loop; no captions or overlays'},null,2));
fs.rmSync(tmp,{recursive:true,force:true});console.log(`Rendered ${N} frames and looping GIF.`);
