'use strict';const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),M=require('../src/motion.js');
async function harness({reduced=false,width=400,profile='2024'}={}){let now=0,next=0,frames=new Map(),render=0,focus=null;class El{constructor(id=''){this.id=id;this.handlers={};this.dataset={};this.value='';this.checked=false;this.disabled=false;this.hidden=false;this.interactive=false;this.capture=null;}addEventListener(t,f){(this.handlers[t]||=[]).push(f);}emit(t,data={}){const e={target:this,preventDefault(){this.prevented=true;},...data};for(const f of this.handlers[t]||[])f(e);return e;}getContext(){return {};}getBoundingClientRect(){return {left:30,top:20,width,height:width*1.8};}setPointerCapture(id){this.capture=id;}hasPointerCapture(id){return this.capture===id;}releasePointerCapture(id){if(this.capture===id)this.capture=null;this.emit('lostpointercapture',{pointerId:id});}focus(){focus=this.id;}closest(){return this.interactive?this:null;}}
const ids=['profile','scene','timeline','time','replay','reduced','reduced-note','status','select','cancel','reverse'];const e=Object.fromEntries(ids.map(id=>[id,new El(id)]));for(const id of ['timeline','replay','reduced','select','cancel','reverse'])e[id].interactive=true;const document=new El();document.getElementById=id=>e[id];document.hidden=false;document.fonts={load:async()=>[]};const media=new El();media.matches=reduced;const context={window:{CircleMotion:M,CircleScene:{draw(){render++;}}},document,matchMedia:()=>media,performance:{now:()=>now},requestAnimationFrame:f=>{frames.set(++next,f);return next;},cancelAnimationFrame:id=>frames.delete(id),location:{search:profile==='2024'?'?profile=2024':''},URLSearchParams,console};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../src/app.js'),'utf8'),context);await new Promise(r=>setImmediate(r));return {e,document,media,get frames(){return frames.size;},get render(){return render;},get focus(){return focus;},step(dt=1/60){now+=dt*1000;const list=[...frames.values()];frames.clear();list.forEach(f=>f(now));},advance(t){for(let i=0;i<t*60;i++)this.step();},point(x,y){return {clientX:30+x*width/400,clientY:20+y*width/400,pointerId:8,button:0};}};}
test('adapter has no idle RAF and initializes accessible status',async()=>{const h=await harness();assert.equal(h.frames,0);assert.equal(h.e.scene.dataset.mode,'idle');assert.match(h.e.status.textContent,/local samples/);});
test('keyboard select, escape, focus exclusion, and ignored key-repeat',async()=>{const h=await harness();h.document.emit('keydown',{key:'Enter',target:h.e.timeline});assert.equal(h.frames,0);h.document.emit('keydown',{key:'Enter',repeat:true});assert.equal(h.frames,0);h.document.emit('keydown',{key:'Enter'});h.advance(1);assert.equal(h.e.scene.dataset.progress,'1.000000');h.document.emit('keydown',{key:'Escape'});h.advance(1);assert.equal(h.e.scene.dataset.mode,'idle');assert.equal(h.frames,0);});
test('actual pointer adapter converts responsive coordinates, captures, selects, repeats',async()=>{for(const width of [280,350,400,600]){const h=await harness({width});for(let pass=0;pass<3;pass++){h.e.scene.emit('pointerdown',h.point(265,160));for(let i=1;i<90;i++){const a=i/89*Math.PI*2;h.e.scene.emit('pointermove',h.point(222+43*Math.cos(a),160+33*Math.sin(a)));}h.e.scene.emit('pointerup',h.point(265,160));h.advance(1);assert.equal(h.e.scene.dataset.target,'glasses');assert.equal(h.focus,'scene');assert.equal(h.e.scene.capture,null);h.e.cancel.emit('click');h.advance(.6);assert.equal(h.e.scene.dataset.mode,'idle');}}});
test('pointercancel, lost capture, and Escape cannot release stale selection',async()=>{for(const type of ['pointercancel','lostpointercapture','Escape']){const h=await harness();h.e.scene.emit('pointerdown',h.point(265,160));if(type==='Escape')h.document.emit('keydown',{key:'Escape'});else h.e.scene.emit(type,h.point(260,160));h.e.scene.emit('pointerup',h.point(265,160));assert.equal(h.e.scene.dataset.mode,'idle');assert.equal(h.frames,0);}});
test('new pointer drawing interrupts source replay with one live frame at most',async()=>{const h=await harness();h.e.replay.emit('click');h.advance(.2);h.e.scene.emit('pointerdown',h.point(265,160));assert.equal(h.e.scene.dataset.mode,'drawing');assert.equal(h.frames,0);h.e.scene.emit('pointercancel',h.point(265,160));assert.equal(h.e.scene.dataset.mode,'idle');});
test('reverse preserves current phase and scrub cancels scheduled replay',async()=>{const h=await harness();h.e.replay.emit('click');h.advance(2.4);const before=h.e.scene.dataset.pts;h.e.reverse.emit('click');assert.equal(h.e.scene.dataset.pts,before);h.advance(.4);assert.ok(Number(h.e.scene.dataset.pts)<Number(before));h.e.timeline.value='5.75';h.e.timeline.emit('input');assert.equal(h.e.scene.dataset.pts,'5.750000');assert.equal(h.frames,0);});
test('reduced motion and live OS changes cancel motion; dismissal is truly idle',async()=>{const h=await harness({reduced:true});assert.equal(h.e.replay.disabled,true);assert.equal(h.e.timeline.disabled,true);h.e.select.emit('click');assert.equal(h.frames,0);assert.equal(h.e.scene.dataset.progress,'1.000000');h.e.cancel.emit('click');assert.equal(h.e.scene.dataset.mode,'idle');assert.equal(h.e.scene.dataset.target,'');const j=await harness();j.e.replay.emit('click');j.advance(.3);j.media.emit('change',{matches:true});assert.equal(j.frames,0);assert.equal(j.e.scene.dataset.mode,'idle');});
test('visibility pauses playback and resumes without elapsed background jump',async()=>{const h=await harness();h.e.replay.emit('click');h.advance(.5);const before=h.e.scene.dataset.pts;h.document.hidden=true;h.document.emit('visibilitychange');h.step(60);assert.equal(h.e.scene.dataset.pts,before);assert.equal(h.frames,0);h.document.hidden=false;h.document.emit('visibilitychange');h.step();assert.ok(Number(h.e.scene.dataset.pts)-Number(before)<.02);});
test('manual reduced preference survives system preference cycle',async()=>{const h=await harness();h.e.reduced.checked=true;h.e.reduced.emit('change');h.media.emit('change',{matches:true});h.media.emit('change',{matches:false});assert.equal(h.e.reduced.checked,true);assert.equal(h.e.replay.disabled,true);});
test('2026 default selects outfit and profile switch exposes historical timing',async()=>{const h=await harness({profile:'2026'});assert.equal(h.e.profile.value,'2026');assert.match(h.e.select.textContent,/outfit/);assert.equal(h.e.timeline.min,'4.6');h.e.select.emit('click');h.advance(1);assert.equal(h.e.scene.dataset.target,'outfit');h.e.profile.value='2024';h.e.profile.emit('change');assert.equal(h.e.scene.dataset.mode,'idle');assert.equal(h.e.timeline.min,'3.5');assert.match(h.e.select.textContent,/sunglasses/);});
test('2026 source pointer path selects outfit through responsive adapter',async()=>{for(const width of [280,400]){const h=await harness({profile:'2026',width}),path=M.currentStroke;h.e.scene.emit('pointerdown',h.point(path[0].x,path[0].y));for(const p of path.slice(1))h.e.scene.emit('pointermove',h.point(p.x,p.y));h.e.scene.emit('pointerup',h.point(path.at(-1).x,path.at(-1).y));h.advance(1);assert.equal(h.e.scene.dataset.target,'outfit');h.e.cancel.emit('click');h.advance(1);assert.equal(h.e.scene.dataset.mode,'idle');}});
test('2026 reduced motion stays instant after reference switch',async()=>{const h=await harness({profile:'2026',reduced:true});h.e.select.emit('click');assert.equal(h.e.scene.dataset.progress,'1.000000');assert.equal(h.frames,0);h.e.profile.value='2024';h.e.profile.emit('change');assert.equal(h.e.replay.disabled,true);});
