'use strict';const {test}=require('node:test'),assert=require('node:assert/strict'),{createCanvas}=require('@napi-rs/canvas'),M=require('../src/motion.js'),A=require('../src/appearance.js'),S=require('../src/scene.js');
function canvas(){const c=createCanvas(400,720),ctx=c.getContext('2d');ctx.fillStyle='#686868';ctx.fillRect(0,0,400,720);return {c,ctx};}function rgb(c,x,y){return [...c.getImageData(x,y,1,1).data].slice(0,3);}function pixels(p){const {ctx}=canvas();S.draw(ctx,p);return ctx.getImageData(0,0,400,720).data;}
test('Gaussian kernel normalized; convolution preserves constant light and softens an impulse',()=>{const k=A.gaussianKernel(2);assert.ok(Math.abs(k.weights.reduce((a,b)=>a+b,0)-1)<1e-12);const constant=new Uint8ClampedArray(17*17*4).fill(100),b=A.blurRGBA(constant,17,17,2);for(let i=0;i<b.length;i++)assert.equal(b[i],100);const point=new Uint8ClampedArray(17*17*4);point[(8*17+8)*4]=255;const blur=A.blurRGBA(point,17,17,2);assert.ok(blur[(8*17+8)*4]>blur[(8*17+11)*4]);assert.ok(blur[(8*17+11)*4]>0);});
test('2026 fades trace before the separate box appears; brightness and scale settle separately',()=>{assert.equal(M.currentReference(5.733).boxAlpha,0);assert.ok(M.currentReference(5.78).traceAlpha<1);assert.equal(M.currentReference(5.84).traceAlpha,0);assert.equal(M.currentReference(5.84).boxAlpha,0);const first=M.currentReference(5.867),last=M.currentReference(6.7);assert.ok(first.boxAlpha>0&&first.boxAlpha<last.boxAlpha);assert.ok(first.box.w<last.box.w);assert.ok(first.sheetY>last.sheetY);assert.ok(first.sceneTransform.scale>last.sceneTransform.scale);});
test('sharp aperture keeps all inner pixel edges unchanged',()=>{const {ctx}=canvas();for(let y=180;y<335;y+=3){ctx.fillStyle=y%2?'#ffffff':'#101010';ctx.fillRect(170,y,60,3);}const before=ctx.getImageData(170,180,60,150).data;A.applyFocus(ctx,M.currentReference(6.7));const after=ctx.getImageData(170,180,60,150).data;assert.deepEqual(after,before);});
test('outside dims but does not invent full-screen Gaussian blur',()=>{const {ctx}=canvas();ctx.fillStyle='#ffffff';ctx.fillRect(85,240,7,30);ctx.fillStyle='#000000';ctx.fillRect(92,240,7,30);A.applyFocus(ctx,M.currentReference(6.7));const white=rgb(ctx,90,250)[0],black=rgb(ctx,94,250)[0];assert.ok(white>95&&white<125);assert.equal(black,0);});
test('halo has spatially decaying energy over tens of pixels, not just a bright outline',()=>{const a=canvas(),b=canvas(),pose=M.currentReference(6.7);A.applyFocus(a.ctx,pose);A.applyFocus(b.ctx,{...pose,appearance:{...pose.appearance,halo:0}});const y=pose.box.cy-pose.box.h/2+20,x=pose.box.cx+pose.box.w/2;let previous=Infinity;for(const d of [3,10,18,28]){const energy=rgb(a.ctx,Math.round(x+d),Math.round(y))[0]-rgb(b.ctx,Math.round(x+d),Math.round(y))[0];assert.ok(energy<previous);assert.ok(energy>=0);previous=energy;}assert.ok(rgb(a.ctx,Math.round(x+18),Math.round(y))[0]>rgb(b.ctx,Math.round(x+18),Math.round(y))[0]+8);});
test('four-color halo matches observed corner order',()=>{const {ctx}=canvas(),p=M.currentReference(6.7),b=p.box;A.applyFocus(ctx,p);const tl=rgb(ctx,b.cx-b.w/2-8|0,b.cy-b.h/2+18|0),tr=rgb(ctx,b.cx+b.w/2+8|0,b.cy-b.h/2+18|0),br=rgb(ctx,b.cx+b.w/2+8|0,b.cy+b.h/2-18|0),bl=rgb(ctx,b.cx-b.w/2-8|0,b.cy+b.h/2-18|0);assert.ok(tl[0]>tl[2]&&tl[1]>tl[2]);assert.ok(tr[0]>tr[1]);assert.ok(br[2]>br[0]);assert.ok(bl[1]>bl[0]);});
test('effect never paints outside the rounded screen boundary',()=>{const {ctx}=canvas();const before=rgb(ctx,60,675);A.applyFocus(ctx,M.currentReference(6.7));assert.deepEqual(rgb(ctx,60,675),before);assert.deepEqual(rgb(ctx,10,100),[104,104,104]);});
test('trace halo produces actual extra pixels and pointer aura is independent',()=>{const p=M.currentReference(5.15),a=pixels({...p,pointerAlpha:0}),b=pixels({...p,pointerAlpha:0,traceGlow:0});let extra=0;for(let i=0;i<a.length;i+=4)if(a[i]+a[i+1]+a[i+2]>b[i]+b[i+1]+b[i+2]+3)extra++;assert.ok(extra>200);const full=pixels(p),none=pixels({...p,pointerAura:0});let aura=0;for(let i=0;i<full.length;i+=4)if(full[i]+full[i+1]+full[i+2]>none[i]+none[i+1]+none[i+2]+6)aura++;assert.ok(aura>300);});
test('current local outfit selection, repeat, reverse, cancel, and reduced motion',()=>{let s=M.initial(false,'2026');s=M.action(s,{type:'start',point:M.currentStroke[0]});for(const point of M.currentStroke.slice(1))s=M.action(s,{type:'move',point});s=M.action(s,{type:'release'});assert.equal(s.target,'outfit');s=M.tick(s,.1);const before=M.pose(s);s=M.action(s,{type:'reverse'});assert.deepEqual(M.pose(s),before);s=M.action(s,{type:'reduced',enabled:true});s=M.action(s,{type:'select'});assert.equal(M.pose(s).boxAlpha,1);s=M.action(s,{type:'cancel'});assert.equal(M.pose(s).appearance.focus,0);assert.equal(s.mode,'idle');});
test('both source modes and shared renderer are deterministically replayable',()=>{for(const p of [M.reference(5.8),M.currentReference(5.9),M.currentReference(6.7)])assert.deepEqual(pixels(p),pixels(p));});
test('first observed box frame uses exact rational source PTS, no rounded-literal delay',()=>{assert.equal(M.currentReference(175/30).boxAlpha,0);assert.ok(M.currentReference(176/30).boxAlpha>0);});
test('first box frame has a gradual exterior veil and glow, not settled intensity',()=>{const first=M.currentReference(176/30),next=M.currentReference(177/30),settled=M.currentReference(6.5);assert.ok(first.appearance.dim<.20);assert.ok(next.appearance.dim>first.appearance.dim);assert.ok(next.appearance.halo>first.appearance.halo);assert.ok(settled.appearance.dim>next.appearance.dim);});
