'use strict';const {test}=require('node:test'),assert=require('node:assert/strict'),M=require('../src/motion.js');
function circle(cx,cy,rx,ry,n=90){return Array.from({length:n},(_,i)=>({x:cx+rx*Math.cos(i/(n-1)*Math.PI*2),y:cy+ry*Math.sin(i/(n-1)*Math.PI*2)}));}
function draw(points){let s=M.action(M.initial(),{type:'start',point:points[0]});for(const p of points.slice(1))s=M.action(s,{type:'move',point:p});return M.action(s,{type:'release'});}
function advance(s,t){for(let i=0;i<t*120;i++)s=M.tick(s,1/120);return s;}
test('source PTS endpoints, ordered sheet rise and finite measured geometry',()=>{let last=Infinity;for(let t=3.5;t<6.701;t+=1/240){const p=M.reference(t);assert.ok(p.sheetY<=last+1e-9);last=p.sheetY;for(const v of Object.values(p.box))assert.ok(Number.isFinite(v));assert.ok(p.box.w>0);assert.ok(p.box.h>0);assert.ok(p.dim>=0&&p.dim<.2);}assert.equal(M.reference(6.7).sheetY,399);assert.equal(M.reference(3.5).draw,0);assert.equal(M.reference(6.7).gaps,1);});
test('freehand polygon selects sunglasses and a distinct tote locally',()=>{assert.equal(draw(circle(222,160,42,31)).target,'glasses');assert.equal(draw(circle(141,452,55,49)).target,'bag');assert.equal(draw(circle(302,375,20,20)).target,null);});
test('tiny strokes, open paths, overbroad loops and taps do not invent results',()=>{for(const points of [[{x:222,y:160}],circle(222,160,3,3),circle(222,160,45,30).slice(0,40),circle(200,360,195,340)])assert.equal(M.detect(points),null);});
test('repeat 30 selections and cancels without stale result state',()=>{let s=M.initial();for(let i=0;i<30;i++){s=M.action(s,{type:'select'});s=advance(s,1);assert.equal(s.p,1);s=M.action(s,{type:'cancel'});s=advance(s,.6);assert.equal(s.mode,'idle');assert.equal(s.target,null);assert.equal(s.points.length,0);assert.equal(M.active(s),false);}});
test('reversal is continuous at the call boundary and reaches both endpoints',()=>{let s=M.action(M.initial(),{type:'select'});s=advance(s,.35);const before=M.pose(s);s=M.action(s,{type:'reverse'});assert.deepEqual(M.pose(s),before);s=advance(s,.5);assert.equal(s.p,0);s=M.action(s,{type:'select'});s=advance(s,.2);s=M.action(s,{type:'reverse'});s=advance(s,.08);s=M.action(s,{type:'reverse'});s=advance(s,1);assert.equal(s.p,1);});
test('cancel while drawing clears path and cannot later release a stale result',()=>{let s=M.action(M.initial(),{type:'start',point:{x:220,y:150}});s=M.action(s,{type:'cancel'});s=M.action(s,{type:'release'});assert.equal(s.mode,'idle');assert.equal(s.target,null);});
test('reduced motion snaps, prevents replay, and accepts pointer selection',()=>{let s=M.action(M.initial(true),{type:'select'});assert.equal(s.p,1);assert.equal(M.active(s),false);s=M.action(s,{type:'cancel'});assert.equal(s.p,0);s=M.action(s,{type:'replay'});assert.notEqual(s.mode,'reference');s=M.action(M.initial(),{type:'replay'});s=M.tick(s,.1);s=M.action(s,{type:'reduced',enabled:true});assert.equal(s.mode,'idle');assert.equal(s.playing,false);});
test('source replay and scrub remain separate from interactive extensions',()=>{let s=M.action(M.initial(),{type:'replay'});s=advance(s,4);assert.equal(s.pts,M.END);assert.equal(s.playing,false);s=M.action(s,{type:'reverse'});s=advance(s,4);assert.equal(s.pts,M.START);assert.equal(s.playing,false);s=M.action(s,{type:'seek',pts:5.75});assert.equal(s.pts,5.75);assert.equal(s.playing,false);assert.equal(M.pose(s).kind,'reference');});
test('responsive coordinate conversion preserves circle positions at 280, 350, 400, 600px',()=>{for(const width of [280,350,400,600]){const r={left:31,top:67,width,height:width*1.8};const p=M.pointFromClient(r.left+222*width/400,r.top+160*width/400,r);assert.ok(Math.abs(p.x-222)<1e-9);assert.ok(Math.abs(p.y-160)<1e-9);}});
test('deterministic replay, finite zero-length resampling, and input caps',()=>{assert.deepEqual(M.reference(5.812),M.reference(5.812));assert.equal(M.resample([{x:1,y:1},{x:1,y:1}]).length,128);let s=M.action(M.initial(),{type:'start',point:{x:1,y:1}});for(let i=0;i<5000;i++)s=M.action(s,{type:'move',point:{x:i%300,y:i%600}});assert.ok(s.points.length<=1200);});
