(function(root,factory){if(typeof module==='object')module.exports=factory(require('./motion-data.js'),require('./pulse-data.js'));else root.Scene=factory(CURSOR_TRACK,PULSE_TRACK);})(this,function(track,pulseTrack){'use strict';
const W=1080,H=852,DURATION=16.8,clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),ease=x=>{x=clamp(x);return x*x*(3-2*x)};
const rows=[{name:'San Francisco',offset:-7,color:'#2c71f7',ink:'#3156b2',edge:'#b6d4fb'},{name:'New York',offset:-4,color:'#7d33f6',ink:'#7629bc',edge:'#d8ccfd'},{name:'São Paulo',offset:-3,color:'#f0004c',ink:'#b0063e',edge:'#ffbed4'},{name:'London',offset:1,color:'#f28b08',ink:'#b77428',edge:'#f9e67c'}];
function xAt(t){t=t>=0&&t<DURATION?t:((t%DURATION)+DURATION)%DURATION;if(t>14.7)return track[track.length-1][1]+(track[0][1]-track[track.length-1][1])*ease((t-14.85)/.85);let lo=0,hi=track.length-1;while(lo+1<hi){const m=(lo+hi)>>1;if(track[m][0]<=t)lo=m;else hi=m;}const a=track[lo],b=track[hi];return a[1]+(b[1]-a[1])*clamp((t-a[0])/(b[0]-a[0]));}
function pulseAt(t){t=t>=0&&t<DURATION?t:((t%DURATION)+DURATION)%DURATION;if(t<pulseTrack[0][0]||t>pulseTrack[pulseTrack.length-1][0])return null;let lo=0,hi=pulseTrack.length-1;while(lo+1<hi){const m=(lo+hi)>>1;if(pulseTrack[m][0]<=t)lo=m;else hi=m;}const a=pulseTrack[lo],b=pulseTrack[hi],q=clamp((t-a[0])/(b[0]-a[0]));return a[1].map((v,i)=>v+(b[1][i]-v)*q);}
function times(hour){return rows.map(r=>{let n=hour+r.offset;return{hour:(n+24)%24,day:Math.floor(n/24),working:(n+24)%24>=9&&(n+24)%24<18};});}
function selectedAt(t){t=t>=0&&t<DURATION?t:((t%DURATION)+DURATION)%DURATION;if(t>14.7)return{hour:t>14.85?5:16,color:t>14.85?[24,24,24]:track[track.length-1].slice(3)};let lo=0,hi=track.length-1;while(lo+1<hi){const m=(lo+hi)>>1;if(track[m][0]<=t)lo=m;else hi=m;}const q=clamp((t-track[lo][0])/(track[hi][0]-track[lo][0]));return{hour:track[lo][2],color:[3,4,5].map(k=>Math.round(track[lo][k]+(track[hi][k]-track[lo][k])*q))};}
function state(t,manual){const reference=selectedAt(t);const position=typeof manual==='object'?manual.position:manual;const x=position===undefined?xAt(t):392+position*14.6;const h=manual===undefined?reference.hour:typeof manual==='object'?manual.hour:Math.round(clamp(manual,0,23));const local=times(h),count=local.filter(r=>r.working).length;return{x,h,local,count,color:manual===undefined?reference.color:count===4?[22,182,133]:[24,25,27]};}
function footerText(hour){const local=times(hour),count=local.filter(r=>r.working).length;if(!count)return 'Off hours everywhere';if(count===4)return 'Works for everyone';const off=local.findIndex(r=>!r.working);return count+' of 4'+(count===3?', '+(local[off].hour<9?'early':'late')+' in '+rows[off].name:' in working hours');}
const events=track.filter((a,i)=>i===0||a[2]!==track[i-1][2]).map((a,i,all)=>({t:a[0],h:a[2],previous:i?all[i-1][2]:a[2]}));
function appearance(t,manual){let current=state(t,manual).h,old=current,elapsed=1;if(manual&&typeof manual==='object'&&manual.previousHour!==undefined){old=manual.previousHour;elapsed=manual.elapsed===undefined?1:manual.elapsed;}else if(manual===undefined){const nt=t>=0&&t<DURATION?t:((t%DURATION)+DURATION)%DURATION;let e=events[0];for(const item of events)if(item.t<=nt)e=item;else break;old=e.previous;elapsed=nt-e.t+.008;if(nt>14.85){old=16;elapsed=nt-14.85;}}const local=times(current),before=times(old),q=clamp(elapsed/.2),mix=x=>1-Math.pow(1-x,2),colors=rows.map((r,i)=>{const to=local[i].working?r.ink:'#97979e',from=before[i].working?r.ink:'#97979e';const parse=v=>[1,3,5].map(k=>parseInt(v.slice(k,k+2),16));const a=parse(from),b=parse(to);return 'rgb('+a.map((v,k)=>Math.round(v+(b[k]-v)*mix(q))).join(',')+')';});let change=null;const nowText=footerText(current);if(manual===undefined){const nt=t>=0&&t<DURATION?t:((t%DURATION)+DURATION)%DURATION;for(const e of events)if(e.t<=nt&&footerText(e.h)!==footerText(e.previous))change=e;else if(e.t>nt)break;if(nt>14.85)change={t:14.85,h:5,previous:16};if(change){old=change.previous;elapsed=nt-change.t+.008;}}const textQ=1-Math.pow(1-clamp(elapsed/.12),2),pillQ=clamp(elapsed/.18),fromFour=times(old).filter(r=>r.working).length===4,toFour=local.filter(r=>r.working).length===4;return{colors,current,old,textQ,oldText:footerText(old),nowText,pill:fromFour+(toFour-fromFour)*mix(pillQ)};}
const tx=(x,y,s,text,color='#17171a',weight=400,mono=false)=>`<text x="${x}" y="${y}" font-size="${s}" font-weight="${weight}" fill="${color}"${mono?' style="font-family:Liberation Mono,DejaVu Sans Mono,monospace"':''}>${text}</text>`;
function svg(t,manual){const s=state(t,manual),a=appearance(t,manual),green=`rgb(${s.color.join(',')})`,pulse=pulseAt(typeof manual==='object'?manual.pulseTime||0:manual===undefined?t:0);let body='';[0,6,12,18].forEach(h=>body+=tx(386+h*14.6,339,11,String(h).padStart(2,'0'),'#95959b',400,true));body+=tx(734,339,11,'UTC','#99999e',400,true).replace('<text ','<text text-anchor="end" ');
rows.forEach((r,i)=>{const top=352.5+i*42.7;body+=`<circle cx="270" cy="${top+8.5}" r="3.5" fill="${r.color}"/>${tx(280,top+12.5,13.5,r.name,'#19191c',500)}${tx(280,top+28,10.5,'UTC'+(r.offset<0?'−':'+')+Math.abs(r.offset),'#939398')}`;for(let h=0;h<24;h++){const local=(h+r.offset+24)%24,color=local>=9&&local<18?r.color:(local===8||local===18?r.edge:'#f0f0f0');body+=`<rect x="${385.8+h*14.6}" y="${top}" width="12.3" height="33.5" rx="2.8" fill="${color}" opacity="${pulse?pulse[i*24+h]:1}"/>`;}const v=s.local[i];body+=tx(752,top+21,13,String(v.hour).padStart(2,'0')+':00',a.colors[i],400,true);if(v.day)body+=tx(796,top+20.5,10,(v.day>0?'+':'')+v.day+'d','#99999e',400,true);});
const drawFooter=(text,opacity,y)=>`<g opacity="${opacity}" transform="translate(0 ${y})">${tx(280,571,13.7,text,text==='Works for everyone'?'#147b55':'#62626c')}</g>`;
const footer=a.oldText===a.nowText?drawFooter(a.nowText,1,0):drawFooter(a.oldText,1-a.textQ,-4*a.textQ)+drawFooter(a.nowText,a.textQ,5*(1-a.textQ));
return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="852" viewBox="0 0 1080 852"><style>text{font-family:Arial,Helvetica,sans-serif}</style><defs><filter id="shadow" x="-25%" y="-30%" width="150%" height="180%"><feGaussianBlur stdDeviation="14"/></filter></defs><rect width="1080" height="852" fill="#fdfdfd"/><rect x="237" y="265" width="608" height="345" rx="31" fill="#25252a" opacity=".08" filter="url(#shadow)"/><rect x="237" y="250" width="608" height="357" rx="31" fill="#d4d4d6"/><rect x="237" y="248" width="608" height="357" rx="31" fill="#f0f0f0"/>${tx(264,289,16.3,'Meeting Finder','#17171b',600)}<rect x="728" y="272" width="89" height="23" rx="12" fill="#e4e4e8"/>${tx(773,288,12.4,String(s.h).padStart(2,'0')+':00 UTC','#64646e',400,true).replace('<text ','<text text-anchor="middle" ')}<rect x="249" y="310" width="583" height="222" rx="19" fill="#fdfdfd"/>${body}<rect x="${s.x-9}" y="333.5" width="18" height="5.5" rx="3" fill="${green}"/><rect x="${s.x-8.5}" y="353.1" width="17" height="160" rx="7" fill="${s.count===4?'#10c48d':'#333'}" fill-opacity=".04" stroke="${s.count===4?'#10c48d':'#18181b'}" stroke-width="2"/><rect x="254" y="551.5" width="158" height="29" rx="14.5" fill="#e7fff1" opacity="${a.pill}"/><circle cx="268" cy="566" r="3.5" fill="#cacacf"/><circle cx="268" cy="566" r="3.5" fill="#10c48d" opacity="${a.pill}"/>${footer}<rect x="680" y="548" width="137" height="36" rx="18" fill="#18181b"/><circle cx="702" cy="566" r="5.1" fill="none" stroke="white" stroke-width="1.4"/><path d="M702 562v4l2 2" stroke="white" stroke-width="1.2" fill="none"/>${tx(714,571,13.3,'Find best time','#fff')}</svg>`;}
return{W,H,DURATION,rows,footerText,appearance,xAt,selectedAt,pulseAt,times,state,svg};});
